/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORT1' to the base of port 'bport1'
#ifndef BPORT1
#error BPORT1 is undefined. It needs to be set to the port base address
#endif


#define BPORT1_AB_POFFSET               0x0
#define BPORT1_AB_USDHC_DS_ADDR_POFFSET  0x0
#define BPORT1_AB_USDHC_DS_ADDR         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_DS_ADDR_POFFSET)
#define BPORT1_AB_USDHC_DS_ADDR_BLKCNT  (0xffff << 16)
#define BPORT1_AB_USDHC_DS_ADDR_BLKCNT_GET(_v)  ((_v >> 16) & 0xffff)
#define BPORT1_AB_USDHC_DS_ADDR_BLKSIZE  0x1fff
#define BPORT1_AB_USDHC_DS_ADDR_BLKSIZE_GET(_v)  (_v & 0x1fff)

#define BPORT1_AB_USDHC_BLK_ATT_POFFSET  0x4
#define BPORT1_AB_USDHC_BLK_ATT         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_BLK_ATT_POFFSET)

#define BPORT1_AB_USDHC_CMD_ARG_POFFSET  0x8
#define BPORT1_AB_USDHC_CMD_ARG         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_CMD_ARG_POFFSET)

#define BPORT1_AB_USDHC_CMD_XFR_TYP_POFFSET  0xc
#define BPORT1_AB_USDHC_CMD_XFR_TYP     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_CMD_XFR_TYP_POFFSET)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CMDINX  (0x3f << 24)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CMDINX_GET(_v)  ((_v >> 24) & 0x3f)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CMDTYP  (0x3 << 22)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CMDTYP_GET(_v)  ((_v >> 22) & 0x3)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_DPSEL  (0x1 << 21)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_DPSEL_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CICEN  (0x1 << 20)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CICEN_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CCCEN  (0x1 << 19)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_CCCEN_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_RSPTYP  (0x3 << 16)
#define BPORT1_AB_USDHC_CMD_XFR_TYP_RSPTYP_GET(_v)  ((_v >> 16) & 0x3)

#define BPORT1_AB_USDHC_CMD_RSP0_POFFSET  0x10
#define BPORT1_AB_USDHC_CMD_RSP0        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_CMD_RSP0_POFFSET)

#define BPORT1_AB_USDHC_CMD_RSP1_POFFSET  0x14
#define BPORT1_AB_USDHC_CMD_RSP1        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_CMD_RSP1_POFFSET)

#define BPORT1_AB_USDHC_CMD_RSP2_POFFSET  0x18
#define BPORT1_AB_USDHC_CMD_RSP2        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_CMD_RSP2_POFFSET)

#define BPORT1_AB_USDHC_CMD_RSP3_POFFSET  0x1c
#define BPORT1_AB_USDHC_CMD_RSP3        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_CMD_RSP3_POFFSET)

#define BPORT1_AB_USDHC_DATA_BUFF_ACC_PORT_POFFSET  0x20
#define BPORT1_AB_USDHC_DATA_BUFF_ACC_PORT  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_DATA_BUFF_ACC_PORT_POFFSET)

#define BPORT1_AB_USDHC_PRES_STATE_POFFSET  0x24
#define BPORT1_AB_USDHC_PRES_STATE      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_PRES_STATE_POFFSET)
#define BPORT1_AB_USDHC_PRES_STATE_DLSL  (0xff << 24)
#define BPORT1_AB_USDHC_PRES_STATE_DLSL_GET(_v)  ((_v >> 24) & 0xff)
#define BPORT1_AB_USDHC_PRES_STATE_CLSL  (0x1 << 23)
#define BPORT1_AB_USDHC_PRES_STATE_CLSL_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_WPSPL  (0x1 << 19)
#define BPORT1_AB_USDHC_PRES_STATE_WPSPL_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_CDPL  (0x1 << 18)
#define BPORT1_AB_USDHC_PRES_STATE_CDPL_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_CINST  (0x1 << 16)
#define BPORT1_AB_USDHC_PRES_STATE_CINST_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_RTR  (0x1 << 12)
#define BPORT1_AB_USDHC_PRES_STATE_RTR_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_BREN  (0x1 << 11)
#define BPORT1_AB_USDHC_PRES_STATE_BREN_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_BWEN  (0x1 << 10)
#define BPORT1_AB_USDHC_PRES_STATE_BWEN_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_RTA  (0x1 << 9)
#define BPORT1_AB_USDHC_PRES_STATE_RTA_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_WTA  (0x1 << 8)
#define BPORT1_AB_USDHC_PRES_STATE_WTA_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_SDOFF  (0x1 << 7)
#define BPORT1_AB_USDHC_PRES_STATE_SDOFF_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_PEROFF  (0x1 << 6)
#define BPORT1_AB_USDHC_PRES_STATE_PEROFF_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_HCKOFF  (0x1 << 5)
#define BPORT1_AB_USDHC_PRES_STATE_HCKOFF_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_IPGOFF  (0x1 << 4)
#define BPORT1_AB_USDHC_PRES_STATE_IPGOFF_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_SDSTB  (0x1 << 3)
#define BPORT1_AB_USDHC_PRES_STATE_SDSTB_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_DLA  (0x1 << 2)
#define BPORT1_AB_USDHC_PRES_STATE_DLA_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_CDIHB  (0x1 << 1)
#define BPORT1_AB_USDHC_PRES_STATE_CDIHB_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_PRES_STATE_CIHB  0x1
#define BPORT1_AB_USDHC_PRES_STATE_CIHB_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_PROT_CTRL_POFFSET  0x28
#define BPORT1_AB_USDHC_PROT_CTRL       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_PROT_CTRL_POFFSET)
#define BPORT1_AB_USDHC_PROT_CTRL_NON_EXACT_BLK_RD  (0x1 << 30)
#define BPORT1_AB_USDHC_PROT_CTRL_NON_EXACT_BLK_RD_GET(_v)  ((_v >> 30) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_BURST_LEN_EN  (0x7 << 27)
#define BPORT1_AB_USDHC_PROT_CTRL_BURST_LEN_EN_GET(_v)  ((_v >> 27) & 0x7)
#define BPORT1_AB_USDHC_PROT_CTRL_WECRM  (0x1 << 26)
#define BPORT1_AB_USDHC_PROT_CTRL_WECRM_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_WECINS  (0x1 << 25)
#define BPORT1_AB_USDHC_PROT_CTRL_WECINS_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_WECINT  (0x1 << 24)
#define BPORT1_AB_USDHC_PROT_CTRL_WECINT_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_RD_DONE_NO_8CLK  (0x1 << 20)
#define BPORT1_AB_USDHC_PROT_CTRL_RD_DONE_NO_8CLK_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_IABG  (0x1 << 19)
#define BPORT1_AB_USDHC_PROT_CTRL_IABG_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_RWCTL  (0x1 << 18)
#define BPORT1_AB_USDHC_PROT_CTRL_RWCTL_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_CREQ  (0x1 << 17)
#define BPORT1_AB_USDHC_PROT_CTRL_CREQ_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_SABGREQ  (0x1 << 16)
#define BPORT1_AB_USDHC_PROT_CTRL_SABGREQ_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_DMASEL  (0x3 << 8)
#define BPORT1_AB_USDHC_PROT_CTRL_DMASEL_GET(_v)  ((_v >> 8) & 0x3)
#define BPORT1_AB_USDHC_PROT_CTRL_CDSS  (0x1 << 7)
#define BPORT1_AB_USDHC_PROT_CTRL_CDSS_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_CDTL  (0x1 << 6)
#define BPORT1_AB_USDHC_PROT_CTRL_CDTL_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_EMODE  (0x3 << 4)
#define BPORT1_AB_USDHC_PROT_CTRL_EMODE_GET(_v)  ((_v >> 4) & 0x3)
#define BPORT1_AB_USDHC_PROT_CTRL_D3CD  (0x1 << 3)
#define BPORT1_AB_USDHC_PROT_CTRL_D3CD_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_PROT_CTRL_DTW   (0x3 << 1)
#define BPORT1_AB_USDHC_PROT_CTRL_DTW_GET(_v)  ((_v >> 1) & 0x3)
#define BPORT1_AB_USDHC_PROT_CTRL_LCTL  0x1
#define BPORT1_AB_USDHC_PROT_CTRL_LCTL_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_SYS_CTRL_POFFSET  0x2c
#define BPORT1_AB_USDHC_SYS_CTRL        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_SYS_CTRL_POFFSET)
#define BPORT1_AB_USDHC_SYS_CTRL_INITA  (0x1 << 27)
#define BPORT1_AB_USDHC_SYS_CTRL_INITA_GET(_v)  ((_v >> 27) & 0x1)
#define BPORT1_AB_USDHC_SYS_CTRL_RSTD   (0x1 << 26)
#define BPORT1_AB_USDHC_SYS_CTRL_RSTD_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_USDHC_SYS_CTRL_RSTC   (0x1 << 25)
#define BPORT1_AB_USDHC_SYS_CTRL_RSTC_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_USDHC_SYS_CTRL_RSTA   (0x1 << 24)
#define BPORT1_AB_USDHC_SYS_CTRL_RSTA_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_SYS_CTRL_IPP_RST_N  (0x1 << 23)
#define BPORT1_AB_USDHC_SYS_CTRL_IPP_RST_N_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_USDHC_SYS_CTRL_DTOCV  (0xf << 16)
#define BPORT1_AB_USDHC_SYS_CTRL_DTOCV_GET(_v)  ((_v >> 16) & 0xf)
#define BPORT1_AB_USDHC_SYS_CTRL_SDCLKFS  (0x7f << 8)
#define BPORT1_AB_USDHC_SYS_CTRL_SDCLKFS_GET(_v)  ((_v >> 8) & 0x7f)
#define BPORT1_AB_USDHC_SYS_CTRL_DVS    (0x7 << 4)
#define BPORT1_AB_USDHC_SYS_CTRL_DVS_GET(_v)  ((_v >> 4) & 0x7)

#define BPORT1_AB_USDHC_INT_STATUS_POFFSET  0x30
#define BPORT1_AB_USDHC_INT_STATUS      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_INT_STATUS_POFFSET)
#define BPORT1_AB_USDHC_INT_STATUS_DMAE  (0x1 << 28)
#define BPORT1_AB_USDHC_INT_STATUS_DMAE_GET(_v)  ((_v >> 28) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_TNE  (0x1 << 26)
#define BPORT1_AB_USDHC_INT_STATUS_TNE_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_AC12E  (0x1 << 24)
#define BPORT1_AB_USDHC_INT_STATUS_AC12E_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_DEBE  (0x1 << 22)
#define BPORT1_AB_USDHC_INT_STATUS_DEBE_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_DCE  (0x1 << 21)
#define BPORT1_AB_USDHC_INT_STATUS_DCE_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_DTOE  (0x1 << 20)
#define BPORT1_AB_USDHC_INT_STATUS_DTOE_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CIE  (0x1 << 19)
#define BPORT1_AB_USDHC_INT_STATUS_CIE_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CEBE  (0x1 << 18)
#define BPORT1_AB_USDHC_INT_STATUS_CEBE_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CCE  (0x1 << 17)
#define BPORT1_AB_USDHC_INT_STATUS_CCE_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CTOE  (0x1 << 16)
#define BPORT1_AB_USDHC_INT_STATUS_CTOE_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_TP   (0x1 << 14)
#define BPORT1_AB_USDHC_INT_STATUS_TP_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_RTE  (0x1 << 12)
#define BPORT1_AB_USDHC_INT_STATUS_RTE_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CINT  (0x1 << 8)
#define BPORT1_AB_USDHC_INT_STATUS_CINT_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CRM  (0x1 << 7)
#define BPORT1_AB_USDHC_INT_STATUS_CRM_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CINS  (0x1 << 6)
#define BPORT1_AB_USDHC_INT_STATUS_CINS_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_BRR  (0x1 << 5)
#define BPORT1_AB_USDHC_INT_STATUS_BRR_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_BWR  (0x1 << 4)
#define BPORT1_AB_USDHC_INT_STATUS_BWR_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_DINT  (0x1 << 3)
#define BPORT1_AB_USDHC_INT_STATUS_DINT_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_BGE  (0x1 << 2)
#define BPORT1_AB_USDHC_INT_STATUS_BGE_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_TC   (0x1 << 1)
#define BPORT1_AB_USDHC_INT_STATUS_TC_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_CC   0x1
#define BPORT1_AB_USDHC_INT_STATUS_CC_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_INT_STATUS_EN_POFFSET  0x34
#define BPORT1_AB_USDHC_INT_STATUS_EN   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_INT_STATUS_EN_POFFSET)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DMAESEN  (0x1 << 28)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DMAESEN_GET(_v)  ((_v >> 28) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_TNESEN  (0x1 << 26)
#define BPORT1_AB_USDHC_INT_STATUS_EN_TNESEN_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_AC12ESEN  (0x1 << 24)
#define BPORT1_AB_USDHC_INT_STATUS_EN_AC12ESEN_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DEBESEN  (0x1 << 22)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DEBESEN_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DCESEN  (0x1 << 21)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DCESEN_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DTOESEN  (0x1 << 20)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DTOESEN_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CIESEN  (0x1 << 19)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CIESEN_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CEBESEN  (0x1 << 18)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CEBESEN_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CCESEN  (0x1 << 17)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CCESEN_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CTOESEN  (0x1 << 16)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CTOESEN_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_TPSEN  (0x1 << 14)
#define BPORT1_AB_USDHC_INT_STATUS_EN_TPSEN_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_RTESEN  (0x1 << 12)
#define BPORT1_AB_USDHC_INT_STATUS_EN_RTESEN_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CINTSEN  (0x1 << 8)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CINTSEN_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CRMSEN  (0x1 << 7)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CRMSEN_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CINSSEN  (0x1 << 6)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CINSSEN_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_BRRSEN  (0x1 << 5)
#define BPORT1_AB_USDHC_INT_STATUS_EN_BRRSEN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_BWRSEN  (0x1 << 4)
#define BPORT1_AB_USDHC_INT_STATUS_EN_BWRSEN_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DINTSEN  (0x1 << 3)
#define BPORT1_AB_USDHC_INT_STATUS_EN_DINTSEN_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_BGESEN  (0x1 << 2)
#define BPORT1_AB_USDHC_INT_STATUS_EN_BGESEN_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_TCSEN  (0x1 << 1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_TCSEN_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_INT_STATUS_EN_CCSEN  0x1
#define BPORT1_AB_USDHC_INT_STATUS_EN_CCSEN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_INT_SIGNAL_EN_POFFSET  0x38
#define BPORT1_AB_USDHC_INT_SIGNAL_EN   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_INT_SIGNAL_EN_POFFSET)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DMAEIEN  (0x1 << 28)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DMAEIEN_GET(_v)  ((_v >> 28) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_TNEIEN  (0x1 << 26)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_TNEIEN_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_AC12EIEN  (0x1 << 24)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_AC12EIEN_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DEBEIEN  (0x1 << 22)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DEBEIEN_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DCEIEN  (0x1 << 21)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DCEIEN_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DTOEIEN  (0x1 << 20)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DTOEIEN_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CIEIEN  (0x1 << 19)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CIEIEN_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CEBEIEN  (0x1 << 18)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CEBEIEN_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CCEIEN  (0x1 << 17)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CCEIEN_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CTOEIEN  (0x1 << 16)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CTOEIEN_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_TPIEN  (0x1 << 14)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_TPIEN_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_RTEIEN  (0x1 << 12)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_RTEIEN_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CINTIEN  (0x1 << 8)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CINTIEN_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CRMIEN  (0x1 << 7)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CRMIEN_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CINSIEN  (0x1 << 6)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CINSIEN_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_BRRIEN  (0x1 << 5)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_BRRIEN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_BWRIEN  (0x1 << 4)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_BWRIEN_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DINTIEN  (0x1 << 3)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_DINTIEN_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_BGEIEN  (0x1 << 2)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_BGEIEN_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_TCIEN  (0x1 << 1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_TCIEN_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CCIEN  0x1
#define BPORT1_AB_USDHC_INT_SIGNAL_EN_CCIEN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_POFFSET  0x3c
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_POFFSET)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_CNIBAC12E  (0x1 << 7)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_CNIBAC12E_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12IE  (0x1 << 4)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12IE_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12CE  (0x1 << 3)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12CE_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12EBE  (0x1 << 2)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12EBE_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12TOE  (0x1 << 1)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12TOE_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12NE  0x1
#define BPORT1_AB_USDHC_AUTOCMD12_ERR_STATUS_AC12NE_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_HOST_CTRL_CAP_POFFSET  0x40
#define BPORT1_AB_USDHC_HOST_CTRL_CAP   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_HOST_CTRL_CAP_POFFSET)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_VS18  (0x1 << 26)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_VS18_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_VS30  (0x1 << 25)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_VS30_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_VS33  (0x1 << 24)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_VS33_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_SRS  (0x1 << 23)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_SRS_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_DMAS  (0x1 << 22)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_DMAS_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_HSS  (0x1 << 21)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_HSS_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_ADMAS  (0x1 << 20)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_ADMAS_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_MBL  (0x7 << 16)
#define BPORT1_AB_USDHC_HOST_CTRL_CAP_MBL_GET(_v)  ((_v >> 16) & 0x7)

#define BPORT1_AB_USDHC_WTMK_LVL_POFFSET  0x44
#define BPORT1_AB_USDHC_WTMK_LVL        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_WTMK_LVL_POFFSET)
#define BPORT1_AB_USDHC_WTMK_LVL_WR_BRST_LEN  (0x1f << 24)
#define BPORT1_AB_USDHC_WTMK_LVL_WR_BRST_LEN_GET(_v)  ((_v >> 24) & 0x1f)
#define BPORT1_AB_USDHC_WTMK_LVL_WR_WML  (0xff << 16)
#define BPORT1_AB_USDHC_WTMK_LVL_WR_WML_GET(_v)  ((_v >> 16) & 0xff)
#define BPORT1_AB_USDHC_WTMK_LVL_RD_BRST_LEN  (0x1f << 8)
#define BPORT1_AB_USDHC_WTMK_LVL_RD_BRST_LEN_GET(_v)  ((_v >> 8) & 0x1f)
#define BPORT1_AB_USDHC_WTMK_LVL_RD_WML  0xff
#define BPORT1_AB_USDHC_WTMK_LVL_RD_WML_GET(_v)  (_v & 0xff)

#define BPORT1_AB_USDHC_MIX_CTRL_POFFSET  0x48
#define BPORT1_AB_USDHC_MIX_CTRL        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_MIX_CTRL_POFFSET)
#define BPORT1_AB_USDHC_MIX_CTRL_FBCLK_SEL  (0x1 << 25)
#define BPORT1_AB_USDHC_MIX_CTRL_FBCLK_SEL_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_AUTO_TUNE_EN  (0x1 << 24)
#define BPORT1_AB_USDHC_MIX_CTRL_AUTO_TUNE_EN_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_SMP_CLK_SEL  (0x1 << 23)
#define BPORT1_AB_USDHC_MIX_CTRL_SMP_CLK_SEL_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_EXE_TUNE  (0x1 << 22)
#define BPORT1_AB_USDHC_MIX_CTRL_EXE_TUNE_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_AC23EN  (0x1 << 7)
#define BPORT1_AB_USDHC_MIX_CTRL_AC23EN_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_NIBBLE_POS  (0x1 << 6)
#define BPORT1_AB_USDHC_MIX_CTRL_NIBBLE_POS_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_MSBSEL  (0x1 << 5)
#define BPORT1_AB_USDHC_MIX_CTRL_MSBSEL_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_DTDSEL  (0x1 << 4)
#define BPORT1_AB_USDHC_MIX_CTRL_DTDSEL_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_DDR_EN  (0x1 << 3)
#define BPORT1_AB_USDHC_MIX_CTRL_DDR_EN_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_AC12EN  (0x1 << 2)
#define BPORT1_AB_USDHC_MIX_CTRL_AC12EN_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_BCEN   (0x1 << 1)
#define BPORT1_AB_USDHC_MIX_CTRL_BCEN_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_MIX_CTRL_DMAEN  0x1
#define BPORT1_AB_USDHC_MIX_CTRL_DMAEN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_FORCE_EVENT_POFFSET  0x50
#define BPORT1_AB_USDHC_FORCE_EVENT     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_FORCE_EVENT_POFFSET)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCINT  (0x1 << 31)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCINT_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDMAE  (0x1 << 28)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDMAE_GET(_v)  ((_v >> 28) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTTNE  (0x1 << 26)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTTNE_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12E  (0x1 << 24)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12E_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDEBE  (0x1 << 22)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDEBE_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDCE  (0x1 << 21)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDCE_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDTOE  (0x1 << 20)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTDTOE_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCIE  (0x1 << 19)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCIE_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCEBE  (0x1 << 18)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCEBE_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCCE  (0x1 << 17)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCCE_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCTOE  (0x1 << 16)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCTOE_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCNIBAC12E  (0x1 << 7)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTCNIBAC12E_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12IE  (0x1 << 4)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12IE_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12EBE  (0x1 << 3)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12EBE_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12CE  (0x1 << 2)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12CE_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12TOE  (0x1 << 1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12TOE_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12NE  0x1
#define BPORT1_AB_USDHC_FORCE_EVENT_FEVTAC12NE_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_ADMA_ERR_STATUS_POFFSET  0x54
#define BPORT1_AB_USDHC_ADMA_ERR_STATUS  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_ADMA_ERR_STATUS_POFFSET)
#define BPORT1_AB_USDHC_ADMA_ERR_STATUS_ADMADCE  (0x1 << 3)
#define BPORT1_AB_USDHC_ADMA_ERR_STATUS_ADMADCE_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_ADMA_ERR_STATUS_ADMALME  (0x1 << 2)
#define BPORT1_AB_USDHC_ADMA_ERR_STATUS_ADMALME_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_ADMA_ERR_STATUS_ADMAES  0x3
#define BPORT1_AB_USDHC_ADMA_ERR_STATUS_ADMAES_GET(_v)  (_v & 0x3)

#define BPORT1_AB_USDHC_ADMA_SYS_ADDR_POFFSET  0x58
#define BPORT1_AB_USDHC_ADMA_SYS_ADDR   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_ADMA_SYS_ADDR_POFFSET)

#define BPORT1_AB_USDHC_DLL_CTRL_POFFSET  0x60
#define BPORT1_AB_USDHC_DLL_CTRL        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_DLL_CTRL_POFFSET)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_REF_UPDATE_INT  (0xf << 28)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_REF_UPDATE_INT_GET(_v)  ((_v >> 28) & 0xf)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_UPDATE_INT  (0xff << 20)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_UPDATE_INT_GET(_v)  ((_v >> 20) & 0xff)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_DLY_TARGET1  (0x7 << 16)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_DLY_TARGET1_GET(_v)  ((_v >> 16) & 0x7)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_OVERRIDE_VAL  (0x3f << 9)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_OVERRIDE_VAL_GET(_v)  ((_v >> 9) & 0x3f)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_OVERRIDE  (0x1 << 8)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_OVERRIDE_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_GATE_UPDATE  (0x1 << 7)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_GATE_UPDATE_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_DLY_TARGET0  (0xf << 3)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_DLY_TARGET0_GET(_v)  ((_v >> 3) & 0xf)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_FORCE_UPD  (0x1 << 2)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_SLV_FORCE_UPD_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_RESET  (0x1 << 1)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_RESET_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_ENABLE  0x1
#define BPORT1_AB_USDHC_DLL_CTRL_DLL_CTRL_ENABLE_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_DLL_STATUS_POFFSET  0x64
#define BPORT1_AB_USDHC_DLL_STATUS      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_DLL_STATUS_POFFSET)
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_REF_SEL  (0x7f << 9)
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_REF_SEL_GET(_v)  ((_v >> 9) & 0x7f)
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_SLV_SEL  (0x7f << 2)
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_SLV_SEL_GET(_v)  ((_v >> 2) & 0x7f)
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_REF_LOCK  (0x1 << 1)
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_REF_LOCK_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_SLV_LOCK  0x1
#define BPORT1_AB_USDHC_DLL_STATUS_DLL_STS_SLV_LOCK_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_POFFSET  0x68
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_POFFSET)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_PRE_ERR  (0x1 << 31)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_PRE_ERR_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_TAP_SEL_PRE  (0x7f << 24)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_TAP_SEL_PRE_GET(_v)  ((_v >> 24) & 0x7f)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_TAP_SEL_OUT  (0xf << 20)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_TAP_SEL_OUT_GET(_v)  ((_v >> 20) & 0xf)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_TAP_SEL_POST  (0xf << 16)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_TAP_SEL_POST_GET(_v)  ((_v >> 16) & 0xf)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_NXT_ERR  (0x1 << 15)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_NXT_ERR_GET(_v)  ((_v >> 15) & 0x1)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_DLY_CELL_SET_PRE  (0x7f << 8)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_DLY_CELL_SET_PRE_GET(_v)  ((_v >> 8) & 0x7f)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_DLY_CELL_SET_OUT  (0x7 << 4)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_DLY_CELL_SET_OUT_GET(_v)  ((_v >> 4) & 0x7)
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_DLY_CELL_SET_POST  0x7
#define BPORT1_AB_USDHC_CLK_TUNE_CTRL_STATUS_DLY_CELL_SET_POST_GET(_v)  (_v & 0x7)

#define BPORT1_AB_USDHC_VEND_SPEC_POFFSET  0xc0
#define BPORT1_AB_USDHC_VEND_SPEC       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_VEND_SPEC_POFFSET)
#define BPORT1_AB_USDHC_VEND_SPEC_CMD_BYTE_EN  (0x1 << 31)
#define BPORT1_AB_USDHC_VEND_SPEC_CMD_BYTE_EN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_INT_ST_VAL  (0xff << 16)
#define BPORT1_AB_USDHC_VEND_SPEC_INT_ST_VAL_GET(_v)  ((_v >> 16) & 0xff)
#define BPORT1_AB_USDHC_VEND_SPEC_CRC_CHK_DIS  (0x1 << 15)
#define BPORT1_AB_USDHC_VEND_SPEC_CRC_CHK_DIS_GET(_v)  ((_v >> 15) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_CARD_CLK_SOFT_EN  (0x1 << 14)
#define BPORT1_AB_USDHC_VEND_SPEC_CARD_CLK_SOFT_EN_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_IPG_PERCLK_SOFT_EN  (0x1 << 13)
#define BPORT1_AB_USDHC_VEND_SPEC_IPG_PERCLK_SOFT_EN_GET(_v)  ((_v >> 13) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_HCLK_SOFT_EN  (0x1 << 12)
#define BPORT1_AB_USDHC_VEND_SPEC_HCLK_SOFT_EN_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_IPG_CLK_SOFT_EN  (0x1 << 11)
#define BPORT1_AB_USDHC_VEND_SPEC_IPG_CLK_SOFT_EN_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_FRC_SDCLK_ON  (0x1 << 8)
#define BPORT1_AB_USDHC_VEND_SPEC_FRC_SDCLK_ON_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_CLKONJ_IN_ABORT  (0x1 << 7)
#define BPORT1_AB_USDHC_VEND_SPEC_CLKONJ_IN_ABORT_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_WP_POL  (0x1 << 6)
#define BPORT1_AB_USDHC_VEND_SPEC_WP_POL_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_CD_POL  (0x1 << 5)
#define BPORT1_AB_USDHC_VEND_SPEC_CD_POL_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_DAT3_CD_POL  (0x1 << 4)
#define BPORT1_AB_USDHC_VEND_SPEC_DAT3_CD_POL_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_AC12_WR_CHKBUSY_EN  (0x1 << 3)
#define BPORT1_AB_USDHC_VEND_SPEC_AC12_WR_CHKBUSY_EN_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_CONFLICT_CHK_EN  (0x1 << 2)
#define BPORT1_AB_USDHC_VEND_SPEC_CONFLICT_CHK_EN_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_VSELECT  (0x1 << 1)
#define BPORT1_AB_USDHC_VEND_SPEC_VSELECT_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC_EXT_DMA_EN  0x1
#define BPORT1_AB_USDHC_VEND_SPEC_EXT_DMA_EN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USDHC_MMC_BOOT_POFFSET  0xc4
#define BPORT1_AB_USDHC_MMC_BOOT        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_MMC_BOOT_POFFSET)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_BLK_CNT  (0xffff << 16)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_BLK_CNT_GET(_v)  ((_v >> 16) & 0xffff)
#define BPORT1_AB_USDHC_MMC_BOOT_DISABLE_TIME_OUT  (0x1 << 8)
#define BPORT1_AB_USDHC_MMC_BOOT_DISABLE_TIME_OUT_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_USDHC_MMC_BOOT_AUTO_SABG_EN  (0x1 << 7)
#define BPORT1_AB_USDHC_MMC_BOOT_AUTO_SABG_EN_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_EN  (0x1 << 6)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_EN_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_MODE  (0x1 << 5)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_MODE_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_ACK  (0x1 << 4)
#define BPORT1_AB_USDHC_MMC_BOOT_BOOT_ACK_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_MMC_BOOT_DTOCV_ACK  0xf
#define BPORT1_AB_USDHC_MMC_BOOT_DTOCV_ACK_GET(_v)  (_v & 0xf)

#define BPORT1_AB_USDHC_VEND_SPEC2_POFFSET  0xc8
#define BPORT1_AB_USDHC_VEND_SPEC2      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USDHC_VEND_SPEC2_POFFSET)
#define BPORT1_AB_USDHC_VEND_SPEC2_CARD_INT_AUTO_CLR_DIS  (0x1 << 7)
#define BPORT1_AB_USDHC_VEND_SPEC2_CARD_INT_AUTO_CLR_DIS_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC2_TUNING_CMD_EN  (0x1 << 6)
#define BPORT1_AB_USDHC_VEND_SPEC2_TUNING_CMD_EN_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC2_TUNING_1BIT_EN  (0x1 << 5)
#define BPORT1_AB_USDHC_VEND_SPEC2_TUNING_1BIT_EN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC2_TUNING_8BIT_EN  (0x1 << 4)
#define BPORT1_AB_USDHC_VEND_SPEC2_TUNING_8BIT_EN_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC2_CARD_INT_D3_TEST  (0x1 << 3)
#define BPORT1_AB_USDHC_VEND_SPEC2_CARD_INT_D3_TEST_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC2_SDR104_NSD_DIS  (0x1 << 2)
#define BPORT1_AB_USDHC_VEND_SPEC2_SDR104_NSD_DIS_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC2_SDR104_OE_DIS  (0x1 << 1)
#define BPORT1_AB_USDHC_VEND_SPEC2_SDR104_OE_DIS_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_USDHC_VEND_SPEC2_SDR104_TIMING_DIS  0x1
#define BPORT1_AB_USDHC_VEND_SPEC2_SDR104_TIMING_DIS_GET(_v)  (_v & 0x1)

#define BPORT1_AB_BUFFER76_POFFSET      0x4c
#define BPORT1_AB_BUFFER76              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER76_POFFSET)
#define BPORT1_AB_BUFFER76_BYTES        0x4

#define BPORT1_AB_BUFFER92_POFFSET      0x5c
#define BPORT1_AB_BUFFER92              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER92_POFFSET)
#define BPORT1_AB_BUFFER92_BYTES        0x4

#define BPORT1_AB_BUFFER108_POFFSET     0x6c
#define BPORT1_AB_BUFFER108             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER108_POFFSET)
#define BPORT1_AB_BUFFER108_BYTES       0x54


#endif
