IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")
CFLAGS+=-I$(IMPERAS_HOME)/ImperasLib/source/xilinx.ovpworld.org/modelSupport/httpConfig/1.0/module
include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.module
