/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORT1' to the base of port 'bport1'
#ifndef BPORT1
#error BPORT1 is undefined. It needs to be set to the port base address
#endif


#define BPORT1_AB_POFFSET               0x0
#define BPORT1_AB_MPRA_POFFSET          0x0
#define BPORT1_AB_MPRA                  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MPRA_POFFSET)
#define BPORT1_AB_MPRA_MPL7             0x1
#define BPORT1_AB_MPRA_MPL7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_MPRA_MTW7             (0x1 << 1)
#define BPORT1_AB_MPRA_MTW7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_MPRA_MTR7             (0x1 << 2)
#define BPORT1_AB_MPRA_MTR7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_MPRA_MPL6             (0x1 << 4)
#define BPORT1_AB_MPRA_MPL6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_MPRA_MTW6             (0x1 << 5)
#define BPORT1_AB_MPRA_MTW6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_MPRA_MTR6             (0x1 << 6)
#define BPORT1_AB_MPRA_MTR6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_MPRA_MPL5             (0x1 << 8)
#define BPORT1_AB_MPRA_MPL5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_MPRA_MTW5             (0x1 << 9)
#define BPORT1_AB_MPRA_MTW5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_MPRA_MTR5             (0x1 << 10)
#define BPORT1_AB_MPRA_MTR5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_MPRA_MPL4             (0x1 << 12)
#define BPORT1_AB_MPRA_MPL4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_MPRA_MTW4             (0x1 << 13)
#define BPORT1_AB_MPRA_MTW4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_MPRA_MTR4             (0x1 << 14)
#define BPORT1_AB_MPRA_MTR4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_MPRA_MPL3             (0x1 << 16)
#define BPORT1_AB_MPRA_MPL3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_MPRA_MTW3             (0x1 << 17)
#define BPORT1_AB_MPRA_MTW3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_MPRA_MTR3             (0x1 << 18)
#define BPORT1_AB_MPRA_MTR3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_MPRA_MPL2             (0x1 << 20)
#define BPORT1_AB_MPRA_MPL2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_MPRA_MTW2             (0x1 << 21)
#define BPORT1_AB_MPRA_MTW2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_MPRA_MTR2             (0x1 << 22)
#define BPORT1_AB_MPRA_MTR2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_MPRA_MPL1             (0x1 << 24)
#define BPORT1_AB_MPRA_MPL1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_MPRA_MTW1             (0x1 << 25)
#define BPORT1_AB_MPRA_MTW1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_MPRA_MTR1             (0x1 << 26)
#define BPORT1_AB_MPRA_MTR1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_MPRA_MPL0             (0x1 << 28)
#define BPORT1_AB_MPRA_MPL0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_MPRA_MTW0             (0x1 << 29)
#define BPORT1_AB_MPRA_MTW0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_MPRA_MTR0             (0x1 << 30)
#define BPORT1_AB_MPRA_MTR0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRA_POFFSET         0x20
#define BPORT1_AB_PACRA                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRA_POFFSET)
#define BPORT1_AB_PACRA_TP7             0x1
#define BPORT1_AB_PACRA_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRA_WP7             (0x1 << 1)
#define BPORT1_AB_PACRA_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRA_SP7             (0x1 << 2)
#define BPORT1_AB_PACRA_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRA_TP6             (0x1 << 4)
#define BPORT1_AB_PACRA_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRA_WP6             (0x1 << 5)
#define BPORT1_AB_PACRA_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRA_SP6             (0x1 << 6)
#define BPORT1_AB_PACRA_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRA_TP5             (0x1 << 8)
#define BPORT1_AB_PACRA_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRA_WP5             (0x1 << 9)
#define BPORT1_AB_PACRA_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRA_SP5             (0x1 << 10)
#define BPORT1_AB_PACRA_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRA_TP4             (0x1 << 12)
#define BPORT1_AB_PACRA_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRA_WP4             (0x1 << 13)
#define BPORT1_AB_PACRA_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRA_SP4             (0x1 << 14)
#define BPORT1_AB_PACRA_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRA_TP3             (0x1 << 16)
#define BPORT1_AB_PACRA_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRA_WP3             (0x1 << 17)
#define BPORT1_AB_PACRA_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRA_SP3             (0x1 << 18)
#define BPORT1_AB_PACRA_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRA_TP2             (0x1 << 20)
#define BPORT1_AB_PACRA_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRA_WP2             (0x1 << 21)
#define BPORT1_AB_PACRA_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRA_SP2             (0x1 << 22)
#define BPORT1_AB_PACRA_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRA_TP1             (0x1 << 24)
#define BPORT1_AB_PACRA_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRA_WP1             (0x1 << 25)
#define BPORT1_AB_PACRA_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRA_SP1             (0x1 << 26)
#define BPORT1_AB_PACRA_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRA_TP0             (0x1 << 28)
#define BPORT1_AB_PACRA_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRA_WP0             (0x1 << 29)
#define BPORT1_AB_PACRA_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRA_SP0             (0x1 << 30)
#define BPORT1_AB_PACRA_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRB_POFFSET         0x24
#define BPORT1_AB_PACRB                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRB_POFFSET)
#define BPORT1_AB_PACRB_TP7             0x1
#define BPORT1_AB_PACRB_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRB_WP7             (0x1 << 1)
#define BPORT1_AB_PACRB_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRB_SP7             (0x1 << 2)
#define BPORT1_AB_PACRB_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRB_TP6             (0x1 << 4)
#define BPORT1_AB_PACRB_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRB_WP6             (0x1 << 5)
#define BPORT1_AB_PACRB_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRB_SP6             (0x1 << 6)
#define BPORT1_AB_PACRB_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRB_TP5             (0x1 << 8)
#define BPORT1_AB_PACRB_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRB_WP5             (0x1 << 9)
#define BPORT1_AB_PACRB_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRB_SP5             (0x1 << 10)
#define BPORT1_AB_PACRB_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRB_TP4             (0x1 << 12)
#define BPORT1_AB_PACRB_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRB_WP4             (0x1 << 13)
#define BPORT1_AB_PACRB_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRB_SP4             (0x1 << 14)
#define BPORT1_AB_PACRB_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRB_TP3             (0x1 << 16)
#define BPORT1_AB_PACRB_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRB_WP3             (0x1 << 17)
#define BPORT1_AB_PACRB_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRB_SP3             (0x1 << 18)
#define BPORT1_AB_PACRB_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRB_TP2             (0x1 << 20)
#define BPORT1_AB_PACRB_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRB_WP2             (0x1 << 21)
#define BPORT1_AB_PACRB_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRB_SP2             (0x1 << 22)
#define BPORT1_AB_PACRB_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRB_TP1             (0x1 << 24)
#define BPORT1_AB_PACRB_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRB_WP1             (0x1 << 25)
#define BPORT1_AB_PACRB_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRB_SP1             (0x1 << 26)
#define BPORT1_AB_PACRB_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRB_TP0             (0x1 << 28)
#define BPORT1_AB_PACRB_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRB_WP0             (0x1 << 29)
#define BPORT1_AB_PACRB_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRB_SP0             (0x1 << 30)
#define BPORT1_AB_PACRB_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRC_POFFSET         0x28
#define BPORT1_AB_PACRC                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRC_POFFSET)
#define BPORT1_AB_PACRC_TP7             0x1
#define BPORT1_AB_PACRC_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRC_WP7             (0x1 << 1)
#define BPORT1_AB_PACRC_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRC_SP7             (0x1 << 2)
#define BPORT1_AB_PACRC_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRC_TP6             (0x1 << 4)
#define BPORT1_AB_PACRC_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRC_WP6             (0x1 << 5)
#define BPORT1_AB_PACRC_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRC_SP6             (0x1 << 6)
#define BPORT1_AB_PACRC_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRC_TP5             (0x1 << 8)
#define BPORT1_AB_PACRC_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRC_WP5             (0x1 << 9)
#define BPORT1_AB_PACRC_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRC_SP5             (0x1 << 10)
#define BPORT1_AB_PACRC_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRC_TP4             (0x1 << 12)
#define BPORT1_AB_PACRC_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRC_WP4             (0x1 << 13)
#define BPORT1_AB_PACRC_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRC_SP4             (0x1 << 14)
#define BPORT1_AB_PACRC_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRC_TP3             (0x1 << 16)
#define BPORT1_AB_PACRC_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRC_WP3             (0x1 << 17)
#define BPORT1_AB_PACRC_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRC_SP3             (0x1 << 18)
#define BPORT1_AB_PACRC_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRC_TP2             (0x1 << 20)
#define BPORT1_AB_PACRC_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRC_WP2             (0x1 << 21)
#define BPORT1_AB_PACRC_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRC_SP2             (0x1 << 22)
#define BPORT1_AB_PACRC_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRC_TP1             (0x1 << 24)
#define BPORT1_AB_PACRC_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRC_WP1             (0x1 << 25)
#define BPORT1_AB_PACRC_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRC_SP1             (0x1 << 26)
#define BPORT1_AB_PACRC_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRC_TP0             (0x1 << 28)
#define BPORT1_AB_PACRC_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRC_WP0             (0x1 << 29)
#define BPORT1_AB_PACRC_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRC_SP0             (0x1 << 30)
#define BPORT1_AB_PACRC_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRD_POFFSET         0x2c
#define BPORT1_AB_PACRD                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRD_POFFSET)
#define BPORT1_AB_PACRD_TP7             0x1
#define BPORT1_AB_PACRD_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRD_WP7             (0x1 << 1)
#define BPORT1_AB_PACRD_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRD_SP7             (0x1 << 2)
#define BPORT1_AB_PACRD_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRD_TP6             (0x1 << 4)
#define BPORT1_AB_PACRD_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRD_WP6             (0x1 << 5)
#define BPORT1_AB_PACRD_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRD_SP6             (0x1 << 6)
#define BPORT1_AB_PACRD_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRD_TP5             (0x1 << 8)
#define BPORT1_AB_PACRD_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRD_WP5             (0x1 << 9)
#define BPORT1_AB_PACRD_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRD_SP5             (0x1 << 10)
#define BPORT1_AB_PACRD_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRD_TP4             (0x1 << 12)
#define BPORT1_AB_PACRD_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRD_WP4             (0x1 << 13)
#define BPORT1_AB_PACRD_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRD_SP4             (0x1 << 14)
#define BPORT1_AB_PACRD_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRD_TP3             (0x1 << 16)
#define BPORT1_AB_PACRD_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRD_WP3             (0x1 << 17)
#define BPORT1_AB_PACRD_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRD_SP3             (0x1 << 18)
#define BPORT1_AB_PACRD_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRD_TP2             (0x1 << 20)
#define BPORT1_AB_PACRD_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRD_WP2             (0x1 << 21)
#define BPORT1_AB_PACRD_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRD_SP2             (0x1 << 22)
#define BPORT1_AB_PACRD_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRD_TP1             (0x1 << 24)
#define BPORT1_AB_PACRD_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRD_WP1             (0x1 << 25)
#define BPORT1_AB_PACRD_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRD_SP1             (0x1 << 26)
#define BPORT1_AB_PACRD_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRD_TP0             (0x1 << 28)
#define BPORT1_AB_PACRD_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRD_WP0             (0x1 << 29)
#define BPORT1_AB_PACRD_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRD_SP0             (0x1 << 30)
#define BPORT1_AB_PACRD_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRE_POFFSET         0x40
#define BPORT1_AB_PACRE                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRE_POFFSET)
#define BPORT1_AB_PACRE_TP7             0x1
#define BPORT1_AB_PACRE_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRE_WP7             (0x1 << 1)
#define BPORT1_AB_PACRE_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRE_SP7             (0x1 << 2)
#define BPORT1_AB_PACRE_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRE_TP6             (0x1 << 4)
#define BPORT1_AB_PACRE_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRE_WP6             (0x1 << 5)
#define BPORT1_AB_PACRE_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRE_SP6             (0x1 << 6)
#define BPORT1_AB_PACRE_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRE_TP5             (0x1 << 8)
#define BPORT1_AB_PACRE_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRE_WP5             (0x1 << 9)
#define BPORT1_AB_PACRE_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRE_SP5             (0x1 << 10)
#define BPORT1_AB_PACRE_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRE_TP4             (0x1 << 12)
#define BPORT1_AB_PACRE_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRE_WP4             (0x1 << 13)
#define BPORT1_AB_PACRE_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRE_SP4             (0x1 << 14)
#define BPORT1_AB_PACRE_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRE_TP3             (0x1 << 16)
#define BPORT1_AB_PACRE_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRE_WP3             (0x1 << 17)
#define BPORT1_AB_PACRE_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRE_SP3             (0x1 << 18)
#define BPORT1_AB_PACRE_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRE_TP2             (0x1 << 20)
#define BPORT1_AB_PACRE_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRE_WP2             (0x1 << 21)
#define BPORT1_AB_PACRE_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRE_SP2             (0x1 << 22)
#define BPORT1_AB_PACRE_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRE_TP1             (0x1 << 24)
#define BPORT1_AB_PACRE_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRE_WP1             (0x1 << 25)
#define BPORT1_AB_PACRE_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRE_SP1             (0x1 << 26)
#define BPORT1_AB_PACRE_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRE_TP0             (0x1 << 28)
#define BPORT1_AB_PACRE_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRE_WP0             (0x1 << 29)
#define BPORT1_AB_PACRE_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRE_SP0             (0x1 << 30)
#define BPORT1_AB_PACRE_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRF_POFFSET         0x44
#define BPORT1_AB_PACRF                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRF_POFFSET)
#define BPORT1_AB_PACRF_TP7             0x1
#define BPORT1_AB_PACRF_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRF_WP7             (0x1 << 1)
#define BPORT1_AB_PACRF_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRF_SP7             (0x1 << 2)
#define BPORT1_AB_PACRF_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRF_TP6             (0x1 << 4)
#define BPORT1_AB_PACRF_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRF_WP6             (0x1 << 5)
#define BPORT1_AB_PACRF_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRF_SP6             (0x1 << 6)
#define BPORT1_AB_PACRF_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRF_TP5             (0x1 << 8)
#define BPORT1_AB_PACRF_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRF_WP5             (0x1 << 9)
#define BPORT1_AB_PACRF_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRF_SP5             (0x1 << 10)
#define BPORT1_AB_PACRF_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRF_TP4             (0x1 << 12)
#define BPORT1_AB_PACRF_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRF_WP4             (0x1 << 13)
#define BPORT1_AB_PACRF_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRF_SP4             (0x1 << 14)
#define BPORT1_AB_PACRF_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRF_TP3             (0x1 << 16)
#define BPORT1_AB_PACRF_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRF_WP3             (0x1 << 17)
#define BPORT1_AB_PACRF_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRF_SP3             (0x1 << 18)
#define BPORT1_AB_PACRF_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRF_TP2             (0x1 << 20)
#define BPORT1_AB_PACRF_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRF_WP2             (0x1 << 21)
#define BPORT1_AB_PACRF_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRF_SP2             (0x1 << 22)
#define BPORT1_AB_PACRF_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRF_TP1             (0x1 << 24)
#define BPORT1_AB_PACRF_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRF_WP1             (0x1 << 25)
#define BPORT1_AB_PACRF_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRF_SP1             (0x1 << 26)
#define BPORT1_AB_PACRF_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRF_TP0             (0x1 << 28)
#define BPORT1_AB_PACRF_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRF_WP0             (0x1 << 29)
#define BPORT1_AB_PACRF_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRF_SP0             (0x1 << 30)
#define BPORT1_AB_PACRF_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRG_POFFSET         0x48
#define BPORT1_AB_PACRG                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRG_POFFSET)
#define BPORT1_AB_PACRG_TP7             0x1
#define BPORT1_AB_PACRG_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRG_WP7             (0x1 << 1)
#define BPORT1_AB_PACRG_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRG_SP7             (0x1 << 2)
#define BPORT1_AB_PACRG_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRG_TP6             (0x1 << 4)
#define BPORT1_AB_PACRG_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRG_WP6             (0x1 << 5)
#define BPORT1_AB_PACRG_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRG_SP6             (0x1 << 6)
#define BPORT1_AB_PACRG_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRG_TP5             (0x1 << 8)
#define BPORT1_AB_PACRG_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRG_WP5             (0x1 << 9)
#define BPORT1_AB_PACRG_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRG_SP5             (0x1 << 10)
#define BPORT1_AB_PACRG_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRG_TP4             (0x1 << 12)
#define BPORT1_AB_PACRG_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRG_WP4             (0x1 << 13)
#define BPORT1_AB_PACRG_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRG_SP4             (0x1 << 14)
#define BPORT1_AB_PACRG_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRG_TP3             (0x1 << 16)
#define BPORT1_AB_PACRG_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRG_WP3             (0x1 << 17)
#define BPORT1_AB_PACRG_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRG_SP3             (0x1 << 18)
#define BPORT1_AB_PACRG_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRG_TP2             (0x1 << 20)
#define BPORT1_AB_PACRG_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRG_WP2             (0x1 << 21)
#define BPORT1_AB_PACRG_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRG_SP2             (0x1 << 22)
#define BPORT1_AB_PACRG_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRG_TP1             (0x1 << 24)
#define BPORT1_AB_PACRG_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRG_WP1             (0x1 << 25)
#define BPORT1_AB_PACRG_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRG_SP1             (0x1 << 26)
#define BPORT1_AB_PACRG_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRG_TP0             (0x1 << 28)
#define BPORT1_AB_PACRG_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRG_WP0             (0x1 << 29)
#define BPORT1_AB_PACRG_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRG_SP0             (0x1 << 30)
#define BPORT1_AB_PACRG_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRH_POFFSET         0x4c
#define BPORT1_AB_PACRH                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRH_POFFSET)
#define BPORT1_AB_PACRH_TP7             0x1
#define BPORT1_AB_PACRH_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRH_WP7             (0x1 << 1)
#define BPORT1_AB_PACRH_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRH_SP7             (0x1 << 2)
#define BPORT1_AB_PACRH_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRH_TP6             (0x1 << 4)
#define BPORT1_AB_PACRH_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRH_WP6             (0x1 << 5)
#define BPORT1_AB_PACRH_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRH_SP6             (0x1 << 6)
#define BPORT1_AB_PACRH_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRH_TP5             (0x1 << 8)
#define BPORT1_AB_PACRH_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRH_WP5             (0x1 << 9)
#define BPORT1_AB_PACRH_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRH_SP5             (0x1 << 10)
#define BPORT1_AB_PACRH_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRH_TP4             (0x1 << 12)
#define BPORT1_AB_PACRH_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRH_WP4             (0x1 << 13)
#define BPORT1_AB_PACRH_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRH_SP4             (0x1 << 14)
#define BPORT1_AB_PACRH_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRH_TP3             (0x1 << 16)
#define BPORT1_AB_PACRH_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRH_WP3             (0x1 << 17)
#define BPORT1_AB_PACRH_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRH_SP3             (0x1 << 18)
#define BPORT1_AB_PACRH_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRH_TP2             (0x1 << 20)
#define BPORT1_AB_PACRH_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRH_WP2             (0x1 << 21)
#define BPORT1_AB_PACRH_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRH_SP2             (0x1 << 22)
#define BPORT1_AB_PACRH_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRH_TP1             (0x1 << 24)
#define BPORT1_AB_PACRH_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRH_WP1             (0x1 << 25)
#define BPORT1_AB_PACRH_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRH_SP1             (0x1 << 26)
#define BPORT1_AB_PACRH_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRH_TP0             (0x1 << 28)
#define BPORT1_AB_PACRH_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRH_WP0             (0x1 << 29)
#define BPORT1_AB_PACRH_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRH_SP0             (0x1 << 30)
#define BPORT1_AB_PACRH_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRI_POFFSET         0x50
#define BPORT1_AB_PACRI                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRI_POFFSET)
#define BPORT1_AB_PACRI_TP7             0x1
#define BPORT1_AB_PACRI_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRI_WP7             (0x1 << 1)
#define BPORT1_AB_PACRI_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRI_SP7             (0x1 << 2)
#define BPORT1_AB_PACRI_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRI_TP6             (0x1 << 4)
#define BPORT1_AB_PACRI_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRI_WP6             (0x1 << 5)
#define BPORT1_AB_PACRI_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRI_SP6             (0x1 << 6)
#define BPORT1_AB_PACRI_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRI_TP5             (0x1 << 8)
#define BPORT1_AB_PACRI_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRI_WP5             (0x1 << 9)
#define BPORT1_AB_PACRI_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRI_SP5             (0x1 << 10)
#define BPORT1_AB_PACRI_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRI_TP4             (0x1 << 12)
#define BPORT1_AB_PACRI_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRI_WP4             (0x1 << 13)
#define BPORT1_AB_PACRI_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRI_SP4             (0x1 << 14)
#define BPORT1_AB_PACRI_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRI_TP3             (0x1 << 16)
#define BPORT1_AB_PACRI_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRI_WP3             (0x1 << 17)
#define BPORT1_AB_PACRI_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRI_SP3             (0x1 << 18)
#define BPORT1_AB_PACRI_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRI_TP2             (0x1 << 20)
#define BPORT1_AB_PACRI_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRI_WP2             (0x1 << 21)
#define BPORT1_AB_PACRI_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRI_SP2             (0x1 << 22)
#define BPORT1_AB_PACRI_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRI_TP1             (0x1 << 24)
#define BPORT1_AB_PACRI_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRI_WP1             (0x1 << 25)
#define BPORT1_AB_PACRI_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRI_SP1             (0x1 << 26)
#define BPORT1_AB_PACRI_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRI_TP0             (0x1 << 28)
#define BPORT1_AB_PACRI_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRI_WP0             (0x1 << 29)
#define BPORT1_AB_PACRI_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRI_SP0             (0x1 << 30)
#define BPORT1_AB_PACRI_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRJ_POFFSET         0x54
#define BPORT1_AB_PACRJ                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRJ_POFFSET)
#define BPORT1_AB_PACRJ_TP7             0x1
#define BPORT1_AB_PACRJ_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRJ_WP7             (0x1 << 1)
#define BPORT1_AB_PACRJ_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRJ_SP7             (0x1 << 2)
#define BPORT1_AB_PACRJ_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRJ_TP6             (0x1 << 4)
#define BPORT1_AB_PACRJ_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRJ_WP6             (0x1 << 5)
#define BPORT1_AB_PACRJ_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRJ_SP6             (0x1 << 6)
#define BPORT1_AB_PACRJ_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRJ_TP5             (0x1 << 8)
#define BPORT1_AB_PACRJ_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRJ_WP5             (0x1 << 9)
#define BPORT1_AB_PACRJ_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRJ_SP5             (0x1 << 10)
#define BPORT1_AB_PACRJ_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRJ_TP4             (0x1 << 12)
#define BPORT1_AB_PACRJ_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRJ_WP4             (0x1 << 13)
#define BPORT1_AB_PACRJ_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRJ_SP4             (0x1 << 14)
#define BPORT1_AB_PACRJ_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRJ_TP3             (0x1 << 16)
#define BPORT1_AB_PACRJ_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRJ_WP3             (0x1 << 17)
#define BPORT1_AB_PACRJ_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRJ_SP3             (0x1 << 18)
#define BPORT1_AB_PACRJ_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRJ_TP2             (0x1 << 20)
#define BPORT1_AB_PACRJ_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRJ_WP2             (0x1 << 21)
#define BPORT1_AB_PACRJ_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRJ_SP2             (0x1 << 22)
#define BPORT1_AB_PACRJ_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRJ_TP1             (0x1 << 24)
#define BPORT1_AB_PACRJ_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRJ_WP1             (0x1 << 25)
#define BPORT1_AB_PACRJ_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRJ_SP1             (0x1 << 26)
#define BPORT1_AB_PACRJ_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRJ_TP0             (0x1 << 28)
#define BPORT1_AB_PACRJ_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRJ_WP0             (0x1 << 29)
#define BPORT1_AB_PACRJ_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRJ_SP0             (0x1 << 30)
#define BPORT1_AB_PACRJ_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRK_POFFSET         0x58
#define BPORT1_AB_PACRK                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRK_POFFSET)
#define BPORT1_AB_PACRK_TP7             0x1
#define BPORT1_AB_PACRK_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRK_WP7             (0x1 << 1)
#define BPORT1_AB_PACRK_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRK_SP7             (0x1 << 2)
#define BPORT1_AB_PACRK_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRK_TP6             (0x1 << 4)
#define BPORT1_AB_PACRK_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRK_WP6             (0x1 << 5)
#define BPORT1_AB_PACRK_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRK_SP6             (0x1 << 6)
#define BPORT1_AB_PACRK_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRK_TP5             (0x1 << 8)
#define BPORT1_AB_PACRK_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRK_WP5             (0x1 << 9)
#define BPORT1_AB_PACRK_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRK_SP5             (0x1 << 10)
#define BPORT1_AB_PACRK_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRK_TP4             (0x1 << 12)
#define BPORT1_AB_PACRK_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRK_WP4             (0x1 << 13)
#define BPORT1_AB_PACRK_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRK_SP4             (0x1 << 14)
#define BPORT1_AB_PACRK_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRK_TP3             (0x1 << 16)
#define BPORT1_AB_PACRK_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRK_WP3             (0x1 << 17)
#define BPORT1_AB_PACRK_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRK_SP3             (0x1 << 18)
#define BPORT1_AB_PACRK_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRK_TP2             (0x1 << 20)
#define BPORT1_AB_PACRK_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRK_WP2             (0x1 << 21)
#define BPORT1_AB_PACRK_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRK_SP2             (0x1 << 22)
#define BPORT1_AB_PACRK_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRK_TP1             (0x1 << 24)
#define BPORT1_AB_PACRK_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRK_WP1             (0x1 << 25)
#define BPORT1_AB_PACRK_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRK_SP1             (0x1 << 26)
#define BPORT1_AB_PACRK_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRK_TP0             (0x1 << 28)
#define BPORT1_AB_PACRK_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRK_WP0             (0x1 << 29)
#define BPORT1_AB_PACRK_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRK_SP0             (0x1 << 30)
#define BPORT1_AB_PACRK_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRL_POFFSET         0x5c
#define BPORT1_AB_PACRL                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRL_POFFSET)
#define BPORT1_AB_PACRL_TP7             0x1
#define BPORT1_AB_PACRL_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRL_WP7             (0x1 << 1)
#define BPORT1_AB_PACRL_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRL_SP7             (0x1 << 2)
#define BPORT1_AB_PACRL_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRL_TP6             (0x1 << 4)
#define BPORT1_AB_PACRL_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRL_WP6             (0x1 << 5)
#define BPORT1_AB_PACRL_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRL_SP6             (0x1 << 6)
#define BPORT1_AB_PACRL_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRL_TP5             (0x1 << 8)
#define BPORT1_AB_PACRL_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRL_WP5             (0x1 << 9)
#define BPORT1_AB_PACRL_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRL_SP5             (0x1 << 10)
#define BPORT1_AB_PACRL_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRL_TP4             (0x1 << 12)
#define BPORT1_AB_PACRL_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRL_WP4             (0x1 << 13)
#define BPORT1_AB_PACRL_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRL_SP4             (0x1 << 14)
#define BPORT1_AB_PACRL_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRL_TP3             (0x1 << 16)
#define BPORT1_AB_PACRL_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRL_WP3             (0x1 << 17)
#define BPORT1_AB_PACRL_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRL_SP3             (0x1 << 18)
#define BPORT1_AB_PACRL_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRL_TP2             (0x1 << 20)
#define BPORT1_AB_PACRL_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRL_WP2             (0x1 << 21)
#define BPORT1_AB_PACRL_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRL_SP2             (0x1 << 22)
#define BPORT1_AB_PACRL_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRL_TP1             (0x1 << 24)
#define BPORT1_AB_PACRL_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRL_WP1             (0x1 << 25)
#define BPORT1_AB_PACRL_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRL_SP1             (0x1 << 26)
#define BPORT1_AB_PACRL_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRL_TP0             (0x1 << 28)
#define BPORT1_AB_PACRL_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRL_WP0             (0x1 << 29)
#define BPORT1_AB_PACRL_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRL_SP0             (0x1 << 30)
#define BPORT1_AB_PACRL_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRM_POFFSET         0x60
#define BPORT1_AB_PACRM                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRM_POFFSET)
#define BPORT1_AB_PACRM_TP7             0x1
#define BPORT1_AB_PACRM_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRM_WP7             (0x1 << 1)
#define BPORT1_AB_PACRM_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRM_SP7             (0x1 << 2)
#define BPORT1_AB_PACRM_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRM_TP6             (0x1 << 4)
#define BPORT1_AB_PACRM_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRM_WP6             (0x1 << 5)
#define BPORT1_AB_PACRM_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRM_SP6             (0x1 << 6)
#define BPORT1_AB_PACRM_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRM_TP5             (0x1 << 8)
#define BPORT1_AB_PACRM_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRM_WP5             (0x1 << 9)
#define BPORT1_AB_PACRM_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRM_SP5             (0x1 << 10)
#define BPORT1_AB_PACRM_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRM_TP4             (0x1 << 12)
#define BPORT1_AB_PACRM_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRM_WP4             (0x1 << 13)
#define BPORT1_AB_PACRM_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRM_SP4             (0x1 << 14)
#define BPORT1_AB_PACRM_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRM_TP3             (0x1 << 16)
#define BPORT1_AB_PACRM_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRM_WP3             (0x1 << 17)
#define BPORT1_AB_PACRM_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRM_SP3             (0x1 << 18)
#define BPORT1_AB_PACRM_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRM_TP2             (0x1 << 20)
#define BPORT1_AB_PACRM_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRM_WP2             (0x1 << 21)
#define BPORT1_AB_PACRM_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRM_SP2             (0x1 << 22)
#define BPORT1_AB_PACRM_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRM_TP1             (0x1 << 24)
#define BPORT1_AB_PACRM_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRM_WP1             (0x1 << 25)
#define BPORT1_AB_PACRM_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRM_SP1             (0x1 << 26)
#define BPORT1_AB_PACRM_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRM_TP0             (0x1 << 28)
#define BPORT1_AB_PACRM_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRM_WP0             (0x1 << 29)
#define BPORT1_AB_PACRM_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRM_SP0             (0x1 << 30)
#define BPORT1_AB_PACRM_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRN_POFFSET         0x64
#define BPORT1_AB_PACRN                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRN_POFFSET)
#define BPORT1_AB_PACRN_TP7             0x1
#define BPORT1_AB_PACRN_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRN_WP7             (0x1 << 1)
#define BPORT1_AB_PACRN_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRN_SP7             (0x1 << 2)
#define BPORT1_AB_PACRN_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRN_TP6             (0x1 << 4)
#define BPORT1_AB_PACRN_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRN_WP6             (0x1 << 5)
#define BPORT1_AB_PACRN_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRN_SP6             (0x1 << 6)
#define BPORT1_AB_PACRN_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRN_TP5             (0x1 << 8)
#define BPORT1_AB_PACRN_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRN_WP5             (0x1 << 9)
#define BPORT1_AB_PACRN_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRN_SP5             (0x1 << 10)
#define BPORT1_AB_PACRN_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRN_TP4             (0x1 << 12)
#define BPORT1_AB_PACRN_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRN_WP4             (0x1 << 13)
#define BPORT1_AB_PACRN_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRN_SP4             (0x1 << 14)
#define BPORT1_AB_PACRN_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRN_TP3             (0x1 << 16)
#define BPORT1_AB_PACRN_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRN_WP3             (0x1 << 17)
#define BPORT1_AB_PACRN_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRN_SP3             (0x1 << 18)
#define BPORT1_AB_PACRN_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRN_TP2             (0x1 << 20)
#define BPORT1_AB_PACRN_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRN_WP2             (0x1 << 21)
#define BPORT1_AB_PACRN_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRN_SP2             (0x1 << 22)
#define BPORT1_AB_PACRN_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRN_TP1             (0x1 << 24)
#define BPORT1_AB_PACRN_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRN_WP1             (0x1 << 25)
#define BPORT1_AB_PACRN_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRN_SP1             (0x1 << 26)
#define BPORT1_AB_PACRN_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRN_TP0             (0x1 << 28)
#define BPORT1_AB_PACRN_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRN_WP0             (0x1 << 29)
#define BPORT1_AB_PACRN_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRN_SP0             (0x1 << 30)
#define BPORT1_AB_PACRN_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRO_POFFSET         0x68
#define BPORT1_AB_PACRO                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRO_POFFSET)
#define BPORT1_AB_PACRO_TP7             0x1
#define BPORT1_AB_PACRO_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRO_WP7             (0x1 << 1)
#define BPORT1_AB_PACRO_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRO_SP7             (0x1 << 2)
#define BPORT1_AB_PACRO_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRO_TP6             (0x1 << 4)
#define BPORT1_AB_PACRO_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRO_WP6             (0x1 << 5)
#define BPORT1_AB_PACRO_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRO_SP6             (0x1 << 6)
#define BPORT1_AB_PACRO_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRO_TP5             (0x1 << 8)
#define BPORT1_AB_PACRO_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRO_WP5             (0x1 << 9)
#define BPORT1_AB_PACRO_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRO_SP5             (0x1 << 10)
#define BPORT1_AB_PACRO_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRO_TP4             (0x1 << 12)
#define BPORT1_AB_PACRO_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRO_WP4             (0x1 << 13)
#define BPORT1_AB_PACRO_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRO_SP4             (0x1 << 14)
#define BPORT1_AB_PACRO_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRO_TP3             (0x1 << 16)
#define BPORT1_AB_PACRO_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRO_WP3             (0x1 << 17)
#define BPORT1_AB_PACRO_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRO_SP3             (0x1 << 18)
#define BPORT1_AB_PACRO_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRO_TP2             (0x1 << 20)
#define BPORT1_AB_PACRO_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRO_WP2             (0x1 << 21)
#define BPORT1_AB_PACRO_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRO_SP2             (0x1 << 22)
#define BPORT1_AB_PACRO_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRO_TP1             (0x1 << 24)
#define BPORT1_AB_PACRO_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRO_WP1             (0x1 << 25)
#define BPORT1_AB_PACRO_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRO_SP1             (0x1 << 26)
#define BPORT1_AB_PACRO_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRO_TP0             (0x1 << 28)
#define BPORT1_AB_PACRO_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRO_WP0             (0x1 << 29)
#define BPORT1_AB_PACRO_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRO_SP0             (0x1 << 30)
#define BPORT1_AB_PACRO_SP0_GET(_v)     ((_v >> 30) & 0x1)

#define BPORT1_AB_PACRP_POFFSET         0x6c
#define BPORT1_AB_PACRP                 (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PACRP_POFFSET)
#define BPORT1_AB_PACRP_TP7             0x1
#define BPORT1_AB_PACRP_TP7_GET(_v)     (_v & 0x1)
#define BPORT1_AB_PACRP_WP7             (0x1 << 1)
#define BPORT1_AB_PACRP_WP7_GET(_v)     ((_v >> 1) & 0x1)
#define BPORT1_AB_PACRP_SP7             (0x1 << 2)
#define BPORT1_AB_PACRP_SP7_GET(_v)     ((_v >> 2) & 0x1)
#define BPORT1_AB_PACRP_TP6             (0x1 << 4)
#define BPORT1_AB_PACRP_TP6_GET(_v)     ((_v >> 4) & 0x1)
#define BPORT1_AB_PACRP_WP6             (0x1 << 5)
#define BPORT1_AB_PACRP_WP6_GET(_v)     ((_v >> 5) & 0x1)
#define BPORT1_AB_PACRP_SP6             (0x1 << 6)
#define BPORT1_AB_PACRP_SP6_GET(_v)     ((_v >> 6) & 0x1)
#define BPORT1_AB_PACRP_TP5             (0x1 << 8)
#define BPORT1_AB_PACRP_TP5_GET(_v)     ((_v >> 8) & 0x1)
#define BPORT1_AB_PACRP_WP5             (0x1 << 9)
#define BPORT1_AB_PACRP_WP5_GET(_v)     ((_v >> 9) & 0x1)
#define BPORT1_AB_PACRP_SP5             (0x1 << 10)
#define BPORT1_AB_PACRP_SP5_GET(_v)     ((_v >> 10) & 0x1)
#define BPORT1_AB_PACRP_TP4             (0x1 << 12)
#define BPORT1_AB_PACRP_TP4_GET(_v)     ((_v >> 12) & 0x1)
#define BPORT1_AB_PACRP_WP4             (0x1 << 13)
#define BPORT1_AB_PACRP_WP4_GET(_v)     ((_v >> 13) & 0x1)
#define BPORT1_AB_PACRP_SP4             (0x1 << 14)
#define BPORT1_AB_PACRP_SP4_GET(_v)     ((_v >> 14) & 0x1)
#define BPORT1_AB_PACRP_TP3             (0x1 << 16)
#define BPORT1_AB_PACRP_TP3_GET(_v)     ((_v >> 16) & 0x1)
#define BPORT1_AB_PACRP_WP3             (0x1 << 17)
#define BPORT1_AB_PACRP_WP3_GET(_v)     ((_v >> 17) & 0x1)
#define BPORT1_AB_PACRP_SP3             (0x1 << 18)
#define BPORT1_AB_PACRP_SP3_GET(_v)     ((_v >> 18) & 0x1)
#define BPORT1_AB_PACRP_TP2             (0x1 << 20)
#define BPORT1_AB_PACRP_TP2_GET(_v)     ((_v >> 20) & 0x1)
#define BPORT1_AB_PACRP_WP2             (0x1 << 21)
#define BPORT1_AB_PACRP_WP2_GET(_v)     ((_v >> 21) & 0x1)
#define BPORT1_AB_PACRP_SP2             (0x1 << 22)
#define BPORT1_AB_PACRP_SP2_GET(_v)     ((_v >> 22) & 0x1)
#define BPORT1_AB_PACRP_TP1             (0x1 << 24)
#define BPORT1_AB_PACRP_TP1_GET(_v)     ((_v >> 24) & 0x1)
#define BPORT1_AB_PACRP_WP1             (0x1 << 25)
#define BPORT1_AB_PACRP_WP1_GET(_v)     ((_v >> 25) & 0x1)
#define BPORT1_AB_PACRP_SP1             (0x1 << 26)
#define BPORT1_AB_PACRP_SP1_GET(_v)     ((_v >> 26) & 0x1)
#define BPORT1_AB_PACRP_TP0             (0x1 << 28)
#define BPORT1_AB_PACRP_TP0_GET(_v)     ((_v >> 28) & 0x1)
#define BPORT1_AB_PACRP_WP0             (0x1 << 29)
#define BPORT1_AB_PACRP_WP0_GET(_v)     ((_v >> 29) & 0x1)
#define BPORT1_AB_PACRP_SP0             (0x1 << 30)
#define BPORT1_AB_PACRP_SP0_GET(_v)     ((_v >> 30) & 0x1)


#endif
