/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////


#ifdef _PSE_
#    include "peripheral/impTypes.h"
#    include "peripheral/bhm.h"
#    include "peripheral/bhmHttp.h"
#    include "peripheral/ppm.h"
#else
#    include "hostapi/impTypes.h"
#endif

#include "pse.igen.h"

static ppmBusPort busPorts[] = {
    {
        .name            = "INTCP0",
        .type            = PPM_SLAVE_PORT,
        .addrHi          = 0xfb,
        .mustBeConnected = 0,
        .remappable      = 0,
        .description     = 0,
    },
    { 0 }
};

static PPM_BUS_PORT_FN(nextBusPort) {
    if(!busPort) {
        busPort = busPorts;
    } else {
        busPort++;
    }
    return busPort->name ? busPort : 0;
}

static ppmNetPort netPorts[] = {
    {
        .name            = "RESET",
        .type            = PPM_OUTPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.RESET,
    },
    {
        .name            = "NMI0",
        .type            = PPM_OUTPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI0,
    },
    {
        .name            = "NMI1",
        .type            = PPM_OUTPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI1,
    },
    {
        .name            = "NMI2",
        .type            = PPM_OUTPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI2,
    },
    {
        .name            = "INTP",
        .type            = PPM_OUTPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INTP,
    },
    {
        .name            = "INTACK",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INTACK,
        .netCB           = P_INTACK,
    },
    {
        .name            = "MIRETI",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.MIRETI,
        .netCB           = P_MIRETI,
    },
    {
        .name            = "IRESET",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.IRESET,
        .netCB           = P_IRESET,
    },
    {
        .name            = "NMI_00",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_00,
        .netCB           = P_NMI,
        .userData        = (void*)0,
    },
    {
        .name            = "NMI_01",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_01,
        .netCB           = P_NMI,
        .userData        = (void*)1,
    },
    {
        .name            = "NMI_02",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_02,
        .netCB           = P_NMI,
        .userData        = (void*)2,
    },
    {
        .name            = "NMI_03",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_03,
        .netCB           = P_NMI,
        .userData        = (void*)3,
    },
    {
        .name            = "NMI_04",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_04,
        .netCB           = P_NMI,
        .userData        = (void*)4,
    },
    {
        .name            = "NMI_05",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_05,
        .netCB           = P_NMI,
        .userData        = (void*)5,
    },
    {
        .name            = "NMI_06",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_06,
        .netCB           = P_NMI,
        .userData        = (void*)6,
    },
    {
        .name            = "NMI_07",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_07,
        .netCB           = P_NMI,
        .userData        = (void*)7,
    },
    {
        .name            = "NMI_08",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_08,
        .netCB           = P_NMI,
        .userData        = (void*)8,
    },
    {
        .name            = "NMI_09",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_09,
        .netCB           = P_NMI,
        .userData        = (void*)9,
    },
    {
        .name            = "NMI_10",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_10,
        .netCB           = P_NMI,
        .userData        = (void*)10,
    },
    {
        .name            = "NMI_11",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_11,
        .netCB           = P_NMI,
        .userData        = (void*)11,
    },
    {
        .name            = "NMI_12",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_12,
        .netCB           = P_NMI,
        .userData        = (void*)12,
    },
    {
        .name            = "NMI_13",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_13,
        .netCB           = P_NMI,
        .userData        = (void*)13,
    },
    {
        .name            = "NMI_14",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_14,
        .netCB           = P_NMI,
        .userData        = (void*)14,
    },
    {
        .name            = "NMI_15",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_15,
        .netCB           = P_NMI,
        .userData        = (void*)15,
    },
    {
        .name            = "NMI_16",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_16,
        .netCB           = P_NMI,
        .userData        = (void*)16,
    },
    {
        .name            = "NMI_17",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_17,
        .netCB           = P_NMI,
        .userData        = (void*)17,
    },
    {
        .name            = "NMI_18",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_18,
        .netCB           = P_NMI,
        .userData        = (void*)18,
    },
    {
        .name            = "NMI_19",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_19,
        .netCB           = P_NMI,
        .userData        = (void*)19,
    },
    {
        .name            = "NMI_20",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_20,
        .netCB           = P_NMI,
        .userData        = (void*)20,
    },
    {
        .name            = "NMI_21",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_21,
        .netCB           = P_NMI,
        .userData        = (void*)21,
    },
    {
        .name            = "NMI_22",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_22,
        .netCB           = P_NMI,
        .userData        = (void*)22,
    },
    {
        .name            = "NMI_23",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_23,
        .netCB           = P_NMI,
        .userData        = (void*)23,
    },
    {
        .name            = "NMI_24",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_24,
        .netCB           = P_NMI,
        .userData        = (void*)24,
    },
    {
        .name            = "NMI_25",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_25,
        .netCB           = P_NMI,
        .userData        = (void*)25,
    },
    {
        .name            = "NMI_26",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_26,
        .netCB           = P_NMI,
        .userData        = (void*)26,
    },
    {
        .name            = "NMI_27",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_27,
        .netCB           = P_NMI,
        .userData        = (void*)27,
    },
    {
        .name            = "NMI_28",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_28,
        .netCB           = P_NMI,
        .userData        = (void*)28,
    },
    {
        .name            = "NMI_29",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_29,
        .netCB           = P_NMI,
        .userData        = (void*)29,
    },
    {
        .name            = "NMI_30",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_30,
        .netCB           = P_NMI,
        .userData        = (void*)30,
    },
    {
        .name            = "NMI_31",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_31,
        .netCB           = P_NMI,
        .userData        = (void*)31,
    },
    {
        .name            = "NMI_32",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_32,
        .netCB           = P_NMI,
        .userData        = (void*)32,
    },
    {
        .name            = "NMI_33",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_33,
        .netCB           = P_NMI,
        .userData        = (void*)33,
    },
    {
        .name            = "NMI_34",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_34,
        .netCB           = P_NMI,
        .userData        = (void*)34,
    },
    {
        .name            = "NMI_35",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_35,
        .netCB           = P_NMI,
        .userData        = (void*)35,
    },
    {
        .name            = "NMI_36",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_36,
        .netCB           = P_NMI,
        .userData        = (void*)36,
    },
    {
        .name            = "NMI_37",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_37,
        .netCB           = P_NMI,
        .userData        = (void*)37,
    },
    {
        .name            = "NMI_38",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_38,
        .netCB           = P_NMI,
        .userData        = (void*)38,
    },
    {
        .name            = "NMI_39",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_39,
        .netCB           = P_NMI,
        .userData        = (void*)39,
    },
    {
        .name            = "NMI_40",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_40,
        .netCB           = P_NMI,
        .userData        = (void*)40,
    },
    {
        .name            = "NMI_41",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_41,
        .netCB           = P_NMI,
        .userData        = (void*)41,
    },
    {
        .name            = "NMI_42",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_42,
        .netCB           = P_NMI,
        .userData        = (void*)42,
    },
    {
        .name            = "NMI_43",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_43,
        .netCB           = P_NMI,
        .userData        = (void*)43,
    },
    {
        .name            = "NMI_44",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_44,
        .netCB           = P_NMI,
        .userData        = (void*)44,
    },
    {
        .name            = "NMI_45",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_45,
        .netCB           = P_NMI,
        .userData        = (void*)45,
    },
    {
        .name            = "NMI_46",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_46,
        .netCB           = P_NMI,
        .userData        = (void*)46,
    },
    {
        .name            = "NMI_47",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_47,
        .netCB           = P_NMI,
        .userData        = (void*)47,
    },
    {
        .name            = "NMI_48",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_48,
        .netCB           = P_NMI,
        .userData        = (void*)48,
    },
    {
        .name            = "NMI_49",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_49,
        .netCB           = P_NMI,
        .userData        = (void*)49,
    },
    {
        .name            = "NMI_50",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_50,
        .netCB           = P_NMI,
        .userData        = (void*)50,
    },
    {
        .name            = "NMI_51",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_51,
        .netCB           = P_NMI,
        .userData        = (void*)51,
    },
    {
        .name            = "NMI_52",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_52,
        .netCB           = P_NMI,
        .userData        = (void*)52,
    },
    {
        .name            = "NMI_53",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_53,
        .netCB           = P_NMI,
        .userData        = (void*)53,
    },
    {
        .name            = "NMI_54",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_54,
        .netCB           = P_NMI,
        .userData        = (void*)54,
    },
    {
        .name            = "NMI_55",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_55,
        .netCB           = P_NMI,
        .userData        = (void*)55,
    },
    {
        .name            = "NMI_56",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_56,
        .netCB           = P_NMI,
        .userData        = (void*)56,
    },
    {
        .name            = "NMI_57",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_57,
        .netCB           = P_NMI,
        .userData        = (void*)57,
    },
    {
        .name            = "NMI_58",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_58,
        .netCB           = P_NMI,
        .userData        = (void*)58,
    },
    {
        .name            = "NMI_59",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_59,
        .netCB           = P_NMI,
        .userData        = (void*)59,
    },
    {
        .name            = "NMI_60",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_60,
        .netCB           = P_NMI,
        .userData        = (void*)60,
    },
    {
        .name            = "NMI_61",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_61,
        .netCB           = P_NMI,
        .userData        = (void*)61,
    },
    {
        .name            = "NMI_62",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_62,
        .netCB           = P_NMI,
        .userData        = (void*)62,
    },
    {
        .name            = "NMI_63",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.NMI_63,
        .netCB           = P_NMI,
        .userData        = (void*)63,
    },
    {
        .name            = "INT_00",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_00,
        .netCB           = P_INT,
        .userData        = (void*)0,
    },
    {
        .name            = "INT_01",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_01,
        .netCB           = P_INT,
        .userData        = (void*)1,
    },
    {
        .name            = "INT_02",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_02,
        .netCB           = P_INT,
        .userData        = (void*)2,
    },
    {
        .name            = "INT_03",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_03,
        .netCB           = P_INT,
        .userData        = (void*)3,
    },
    {
        .name            = "INT_04",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_04,
        .netCB           = P_INT,
        .userData        = (void*)4,
    },
    {
        .name            = "INT_05",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_05,
        .netCB           = P_INT,
        .userData        = (void*)5,
    },
    {
        .name            = "INT_06",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_06,
        .netCB           = P_INT,
        .userData        = (void*)6,
    },
    {
        .name            = "INT_07",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_07,
        .netCB           = P_INT,
        .userData        = (void*)7,
    },
    {
        .name            = "INT_08",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_08,
        .netCB           = P_INT,
        .userData        = (void*)8,
    },
    {
        .name            = "INT_09",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_09,
        .netCB           = P_INT,
        .userData        = (void*)9,
    },
    {
        .name            = "INT_10",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_10,
        .netCB           = P_INT,
        .userData        = (void*)10,
    },
    {
        .name            = "INT_11",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_11,
        .netCB           = P_INT,
        .userData        = (void*)11,
    },
    {
        .name            = "INT_12",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_12,
        .netCB           = P_INT,
        .userData        = (void*)12,
    },
    {
        .name            = "INT_13",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_13,
        .netCB           = P_INT,
        .userData        = (void*)13,
    },
    {
        .name            = "INT_14",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_14,
        .netCB           = P_INT,
        .userData        = (void*)14,
    },
    {
        .name            = "INT_15",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_15,
        .netCB           = P_INT,
        .userData        = (void*)15,
    },
    {
        .name            = "INT_16",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_16,
        .netCB           = P_INT,
        .userData        = (void*)16,
    },
    {
        .name            = "INT_17",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_17,
        .netCB           = P_INT,
        .userData        = (void*)17,
    },
    {
        .name            = "INT_18",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_18,
        .netCB           = P_INT,
        .userData        = (void*)18,
    },
    {
        .name            = "INT_19",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_19,
        .netCB           = P_INT,
        .userData        = (void*)19,
    },
    {
        .name            = "INT_20",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_20,
        .netCB           = P_INT,
        .userData        = (void*)20,
    },
    {
        .name            = "INT_21",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_21,
        .netCB           = P_INT,
        .userData        = (void*)21,
    },
    {
        .name            = "INT_22",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_22,
        .netCB           = P_INT,
        .userData        = (void*)22,
    },
    {
        .name            = "INT_23",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_23,
        .netCB           = P_INT,
        .userData        = (void*)23,
    },
    {
        .name            = "INT_24",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_24,
        .netCB           = P_INT,
        .userData        = (void*)24,
    },
    {
        .name            = "INT_25",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_25,
        .netCB           = P_INT,
        .userData        = (void*)25,
    },
    {
        .name            = "INT_26",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_26,
        .netCB           = P_INT,
        .userData        = (void*)26,
    },
    {
        .name            = "INT_27",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_27,
        .netCB           = P_INT,
        .userData        = (void*)27,
    },
    {
        .name            = "INT_28",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_28,
        .netCB           = P_INT,
        .userData        = (void*)28,
    },
    {
        .name            = "INT_29",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_29,
        .netCB           = P_INT,
        .userData        = (void*)29,
    },
    {
        .name            = "INT_30",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_30,
        .netCB           = P_INT,
        .userData        = (void*)30,
    },
    {
        .name            = "INT_31",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_31,
        .netCB           = P_INT,
        .userData        = (void*)31,
    },
    {
        .name            = "INT_32",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_32,
        .netCB           = P_INT,
        .userData        = (void*)32,
    },
    {
        .name            = "INT_33",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_33,
        .netCB           = P_INT,
        .userData        = (void*)33,
    },
    {
        .name            = "INT_34",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_34,
        .netCB           = P_INT,
        .userData        = (void*)34,
    },
    {
        .name            = "INT_35",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_35,
        .netCB           = P_INT,
        .userData        = (void*)35,
    },
    {
        .name            = "INT_36",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_36,
        .netCB           = P_INT,
        .userData        = (void*)36,
    },
    {
        .name            = "INT_37",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_37,
        .netCB           = P_INT,
        .userData        = (void*)37,
    },
    {
        .name            = "INT_38",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_38,
        .netCB           = P_INT,
        .userData        = (void*)38,
    },
    {
        .name            = "INT_39",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_39,
        .netCB           = P_INT,
        .userData        = (void*)39,
    },
    {
        .name            = "INT_40",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_40,
        .netCB           = P_INT,
        .userData        = (void*)40,
    },
    {
        .name            = "INT_41",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_41,
        .netCB           = P_INT,
        .userData        = (void*)41,
    },
    {
        .name            = "INT_42",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_42,
        .netCB           = P_INT,
        .userData        = (void*)42,
    },
    {
        .name            = "INT_43",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_43,
        .netCB           = P_INT,
        .userData        = (void*)43,
    },
    {
        .name            = "INT_44",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_44,
        .netCB           = P_INT,
        .userData        = (void*)44,
    },
    {
        .name            = "INT_45",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_45,
        .netCB           = P_INT,
        .userData        = (void*)45,
    },
    {
        .name            = "INT_46",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_46,
        .netCB           = P_INT,
        .userData        = (void*)46,
    },
    {
        .name            = "INT_47",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_47,
        .netCB           = P_INT,
        .userData        = (void*)47,
    },
    {
        .name            = "INT_48",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_48,
        .netCB           = P_INT,
        .userData        = (void*)48,
    },
    {
        .name            = "INT_49",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_49,
        .netCB           = P_INT,
        .userData        = (void*)49,
    },
    {
        .name            = "INT_50",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_50,
        .netCB           = P_INT,
        .userData        = (void*)50,
    },
    {
        .name            = "INT_51",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_51,
        .netCB           = P_INT,
        .userData        = (void*)51,
    },
    {
        .name            = "INT_52",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_52,
        .netCB           = P_INT,
        .userData        = (void*)52,
    },
    {
        .name            = "INT_53",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_53,
        .netCB           = P_INT,
        .userData        = (void*)53,
    },
    {
        .name            = "INT_54",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_54,
        .netCB           = P_INT,
        .userData        = (void*)54,
    },
    {
        .name            = "INT_55",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_55,
        .netCB           = P_INT,
        .userData        = (void*)55,
    },
    {
        .name            = "INT_56",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_56,
        .netCB           = P_INT,
        .userData        = (void*)56,
    },
    {
        .name            = "INT_57",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_57,
        .netCB           = P_INT,
        .userData        = (void*)57,
    },
    {
        .name            = "INT_58",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_58,
        .netCB           = P_INT,
        .userData        = (void*)58,
    },
    {
        .name            = "INT_59",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_59,
        .netCB           = P_INT,
        .userData        = (void*)59,
    },
    {
        .name            = "INT_60",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_60,
        .netCB           = P_INT,
        .userData        = (void*)60,
    },
    {
        .name            = "INT_61",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_61,
        .netCB           = P_INT,
        .userData        = (void*)61,
    },
    {
        .name            = "INT_62",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_62,
        .netCB           = P_INT,
        .userData        = (void*)62,
    },
    {
        .name            = "INT_63",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_63,
        .netCB           = P_INT,
        .userData        = (void*)63,
    },
    {
        .name            = "INT_64",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_64,
        .netCB           = P_INT,
        .userData        = (void*)64,
    },
    {
        .name            = "INT_65",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_65,
        .netCB           = P_INT,
        .userData        = (void*)65,
    },
    {
        .name            = "INT_66",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_66,
        .netCB           = P_INT,
        .userData        = (void*)66,
    },
    {
        .name            = "INT_67",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_67,
        .netCB           = P_INT,
        .userData        = (void*)67,
    },
    {
        .name            = "INT_68",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_68,
        .netCB           = P_INT,
        .userData        = (void*)68,
    },
    {
        .name            = "INT_69",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_69,
        .netCB           = P_INT,
        .userData        = (void*)69,
    },
    {
        .name            = "INT_70",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_70,
        .netCB           = P_INT,
        .userData        = (void*)70,
    },
    {
        .name            = "INT_71",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_71,
        .netCB           = P_INT,
        .userData        = (void*)71,
    },
    {
        .name            = "INT_72",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_72,
        .netCB           = P_INT,
        .userData        = (void*)72,
    },
    {
        .name            = "INT_73",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_73,
        .netCB           = P_INT,
        .userData        = (void*)73,
    },
    {
        .name            = "INT_74",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_74,
        .netCB           = P_INT,
        .userData        = (void*)74,
    },
    {
        .name            = "INT_75",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_75,
        .netCB           = P_INT,
        .userData        = (void*)75,
    },
    {
        .name            = "INT_76",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_76,
        .netCB           = P_INT,
        .userData        = (void*)76,
    },
    {
        .name            = "INT_77",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_77,
        .netCB           = P_INT,
        .userData        = (void*)77,
    },
    {
        .name            = "INT_78",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_78,
        .netCB           = P_INT,
        .userData        = (void*)78,
    },
    {
        .name            = "INT_79",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_79,
        .netCB           = P_INT,
        .userData        = (void*)79,
    },
    {
        .name            = "INT_80",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_80,
        .netCB           = P_INT,
        .userData        = (void*)80,
    },
    {
        .name            = "INT_81",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_81,
        .netCB           = P_INT,
        .userData        = (void*)81,
    },
    {
        .name            = "INT_82",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_82,
        .netCB           = P_INT,
        .userData        = (void*)82,
    },
    {
        .name            = "INT_83",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_83,
        .netCB           = P_INT,
        .userData        = (void*)83,
    },
    {
        .name            = "INT_84",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_84,
        .netCB           = P_INT,
        .userData        = (void*)84,
    },
    {
        .name            = "INT_85",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_85,
        .netCB           = P_INT,
        .userData        = (void*)85,
    },
    {
        .name            = "INT_86",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_86,
        .netCB           = P_INT,
        .userData        = (void*)86,
    },
    {
        .name            = "INT_87",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_87,
        .netCB           = P_INT,
        .userData        = (void*)87,
    },
    {
        .name            = "INT_88",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_88,
        .netCB           = P_INT,
        .userData        = (void*)88,
    },
    {
        .name            = "INT_89",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_89,
        .netCB           = P_INT,
        .userData        = (void*)89,
    },
    {
        .name            = "INT_90",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_90,
        .netCB           = P_INT,
        .userData        = (void*)90,
    },
    {
        .name            = "INT_91",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_91,
        .netCB           = P_INT,
        .userData        = (void*)91,
    },
    {
        .name            = "INT_92",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_92,
        .netCB           = P_INT,
        .userData        = (void*)92,
    },
    {
        .name            = "INT_93",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_93,
        .netCB           = P_INT,
        .userData        = (void*)93,
    },
    {
        .name            = "INT_94",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_94,
        .netCB           = P_INT,
        .userData        = (void*)94,
    },
    {
        .name            = "INT_95",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_95,
        .netCB           = P_INT,
        .userData        = (void*)95,
    },
    {
        .name            = "INT_96",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_96,
        .netCB           = P_INT,
        .userData        = (void*)96,
    },
    {
        .name            = "INT_97",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_97,
        .netCB           = P_INT,
        .userData        = (void*)97,
    },
    {
        .name            = "INT_98",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_98,
        .netCB           = P_INT,
        .userData        = (void*)98,
    },
    {
        .name            = "INT_99",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_99,
        .netCB           = P_INT,
        .userData        = (void*)99,
    },
    {
        .name            = "INT_100",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_100,
        .netCB           = P_INT,
        .userData        = (void*)100,
    },
    {
        .name            = "INT_101",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_101,
        .netCB           = P_INT,
        .userData        = (void*)101,
    },
    {
        .name            = "INT_102",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_102,
        .netCB           = P_INT,
        .userData        = (void*)102,
    },
    {
        .name            = "INT_103",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_103,
        .netCB           = P_INT,
        .userData        = (void*)103,
    },
    {
        .name            = "INT_104",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_104,
        .netCB           = P_INT,
        .userData        = (void*)104,
    },
    {
        .name            = "INT_105",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_105,
        .netCB           = P_INT,
        .userData        = (void*)105,
    },
    {
        .name            = "INT_106",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_106,
        .netCB           = P_INT,
        .userData        = (void*)106,
    },
    {
        .name            = "INT_107",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_107,
        .netCB           = P_INT,
        .userData        = (void*)107,
    },
    {
        .name            = "INT_108",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_108,
        .netCB           = P_INT,
        .userData        = (void*)108,
    },
    {
        .name            = "INT_109",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_109,
        .netCB           = P_INT,
        .userData        = (void*)109,
    },
    {
        .name            = "INT_110",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_110,
        .netCB           = P_INT,
        .userData        = (void*)110,
    },
    {
        .name            = "INT_111",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_111,
        .netCB           = P_INT,
        .userData        = (void*)111,
    },
    {
        .name            = "INT_112",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_112,
        .netCB           = P_INT,
        .userData        = (void*)112,
    },
    {
        .name            = "INT_113",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_113,
        .netCB           = P_INT,
        .userData        = (void*)113,
    },
    {
        .name            = "INT_114",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_114,
        .netCB           = P_INT,
        .userData        = (void*)114,
    },
    {
        .name            = "INT_115",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_115,
        .netCB           = P_INT,
        .userData        = (void*)115,
    },
    {
        .name            = "INT_116",
        .type            = PPM_INPUT_PORT,
        .mustBeConnected = 0,
        .description     = 0,
        .handlePtr       = &handles.INT_116,
        .netCB           = P_INT,
        .userData        = (void*)116,
    },
    { 0 }
};

static PPM_NET_PORT_FN(nextNetPort) {
    if(!netPort) {
         netPort = netPorts;
    } else {
        netPort++;
    }
    return (netPort && netPort->name) ? netPort : 0;
}

ppmModelAttr modelAttrs = {

    .versionString    = PPM_VERSION_STRING,
    .type             = PPM_MT_PERIPHERAL,

    .busPortsCB       = nextBusPort,  
    .netPortsCB       = nextNetPort,  

    .saveCB        = peripheralSaveState,
    .restoreCB     = peripheralRestoreState,

    .docCB         = installDocs,

    .vlnv          = {
        .vendor  = "renesas.ovpworld.org",
        .library = "peripheral",
        .name    = "intc",
        .version = "1.0"
    },

    .family               = "renesas.ovpworld.org",
    .noRecursiveCallbacks = 1,

    .releaseStatus = PPM_UNSET,
    .visibility     = PPM_VISIBLE,
    .saveRestore    = 0,

};
