/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'PLB' to the base of port 'plb'
#ifndef PLB
#error PLB is undefined. It needs to be set to the port base address
#endif


#define PLB_REG_POFFSET                 0x0
#define PLB_REG_ISR_POFFSET             0x0
#define PLB_REG_ISR                     (PLB + PLB_REG_POFFSET + PLB_REG_ISR_POFFSET)
#define PLB_REG_ISR_INT0                0x1
#define PLB_REG_ISR_INT0_GET(_v)        (_v & 0x1)
#define PLB_REG_ISR_INT1                (0x1 << 1)
#define PLB_REG_ISR_INT1_GET(_v)        ((_v >> 1) & 0x1)
#define PLB_REG_ISR_INT2                (0x1 << 2)
#define PLB_REG_ISR_INT2_GET(_v)        ((_v >> 2) & 0x1)
#define PLB_REG_ISR_INT3                (0x1 << 3)
#define PLB_REG_ISR_INT3_GET(_v)        ((_v >> 3) & 0x1)
#define PLB_REG_ISR_INT4                (0x1 << 4)
#define PLB_REG_ISR_INT4_GET(_v)        ((_v >> 4) & 0x1)
#define PLB_REG_ISR_INT5                (0x1 << 5)
#define PLB_REG_ISR_INT5_GET(_v)        ((_v >> 5) & 0x1)
#define PLB_REG_ISR_INT6                (0x1 << 6)
#define PLB_REG_ISR_INT6_GET(_v)        ((_v >> 6) & 0x1)
#define PLB_REG_ISR_INT7                (0x1 << 7)
#define PLB_REG_ISR_INT7_GET(_v)        ((_v >> 7) & 0x1)
#define PLB_REG_ISR_INT8                (0x1 << 8)
#define PLB_REG_ISR_INT8_GET(_v)        ((_v >> 8) & 0x1)
#define PLB_REG_ISR_INT9                (0x1 << 9)
#define PLB_REG_ISR_INT9_GET(_v)        ((_v >> 9) & 0x1)
#define PLB_REG_ISR_INT10               (0x1 << 10)
#define PLB_REG_ISR_INT10_GET(_v)       ((_v >> 10) & 0x1)
#define PLB_REG_ISR_INT11               (0x1 << 11)
#define PLB_REG_ISR_INT11_GET(_v)       ((_v >> 11) & 0x1)
#define PLB_REG_ISR_INT12               (0x1 << 12)
#define PLB_REG_ISR_INT12_GET(_v)       ((_v >> 12) & 0x1)
#define PLB_REG_ISR_INT13               (0x1 << 13)
#define PLB_REG_ISR_INT13_GET(_v)       ((_v >> 13) & 0x1)
#define PLB_REG_ISR_INT14               (0x1 << 14)
#define PLB_REG_ISR_INT14_GET(_v)       ((_v >> 14) & 0x1)
#define PLB_REG_ISR_INT15               (0x1 << 15)
#define PLB_REG_ISR_INT15_GET(_v)       ((_v >> 15) & 0x1)
#define PLB_REG_ISR_INT16               (0x1 << 16)
#define PLB_REG_ISR_INT16_GET(_v)       ((_v >> 16) & 0x1)
#define PLB_REG_ISR_INT17               (0x1 << 17)
#define PLB_REG_ISR_INT17_GET(_v)       ((_v >> 17) & 0x1)
#define PLB_REG_ISR_INT18               (0x1 << 18)
#define PLB_REG_ISR_INT18_GET(_v)       ((_v >> 18) & 0x1)
#define PLB_REG_ISR_INT19               (0x1 << 19)
#define PLB_REG_ISR_INT19_GET(_v)       ((_v >> 19) & 0x1)
#define PLB_REG_ISR_INT20               (0x1 << 20)
#define PLB_REG_ISR_INT20_GET(_v)       ((_v >> 20) & 0x1)
#define PLB_REG_ISR_INT21               (0x1 << 21)
#define PLB_REG_ISR_INT21_GET(_v)       ((_v >> 21) & 0x1)
#define PLB_REG_ISR_INT22               (0x1 << 22)
#define PLB_REG_ISR_INT22_GET(_v)       ((_v >> 22) & 0x1)
#define PLB_REG_ISR_INT23               (0x1 << 23)
#define PLB_REG_ISR_INT23_GET(_v)       ((_v >> 23) & 0x1)
#define PLB_REG_ISR_INT24               (0x1 << 24)
#define PLB_REG_ISR_INT24_GET(_v)       ((_v >> 24) & 0x1)
#define PLB_REG_ISR_INT25               (0x1 << 25)
#define PLB_REG_ISR_INT25_GET(_v)       ((_v >> 25) & 0x1)
#define PLB_REG_ISR_INT26               (0x1 << 26)
#define PLB_REG_ISR_INT26_GET(_v)       ((_v >> 26) & 0x1)
#define PLB_REG_ISR_INT27               (0x1 << 27)
#define PLB_REG_ISR_INT27_GET(_v)       ((_v >> 27) & 0x1)
#define PLB_REG_ISR_INT28               (0x1 << 28)
#define PLB_REG_ISR_INT28_GET(_v)       ((_v >> 28) & 0x1)
#define PLB_REG_ISR_INT29               (0x1 << 29)
#define PLB_REG_ISR_INT29_GET(_v)       ((_v >> 29) & 0x1)
#define PLB_REG_ISR_INT30               (0x1 << 30)
#define PLB_REG_ISR_INT30_GET(_v)       ((_v >> 30) & 0x1)
#define PLB_REG_ISR_INT31               (0x1 << 31)
#define PLB_REG_ISR_INT31_GET(_v)       ((_v >> 31) & 0x1)

#define PLB_REG_IPR_POFFSET             0x4
#define PLB_REG_IPR                     (PLB + PLB_REG_POFFSET + PLB_REG_IPR_POFFSET)
#define PLB_REG_IPR_INT0                0x1
#define PLB_REG_IPR_INT0_GET(_v)        (_v & 0x1)
#define PLB_REG_IPR_INT1                (0x1 << 1)
#define PLB_REG_IPR_INT1_GET(_v)        ((_v >> 1) & 0x1)
#define PLB_REG_IPR_INT2                (0x1 << 2)
#define PLB_REG_IPR_INT2_GET(_v)        ((_v >> 2) & 0x1)
#define PLB_REG_IPR_INT3                (0x1 << 3)
#define PLB_REG_IPR_INT3_GET(_v)        ((_v >> 3) & 0x1)
#define PLB_REG_IPR_INT4                (0x1 << 4)
#define PLB_REG_IPR_INT4_GET(_v)        ((_v >> 4) & 0x1)
#define PLB_REG_IPR_INT5                (0x1 << 5)
#define PLB_REG_IPR_INT5_GET(_v)        ((_v >> 5) & 0x1)
#define PLB_REG_IPR_INT6                (0x1 << 6)
#define PLB_REG_IPR_INT6_GET(_v)        ((_v >> 6) & 0x1)
#define PLB_REG_IPR_INT7                (0x1 << 7)
#define PLB_REG_IPR_INT7_GET(_v)        ((_v >> 7) & 0x1)
#define PLB_REG_IPR_INT8                (0x1 << 8)
#define PLB_REG_IPR_INT8_GET(_v)        ((_v >> 8) & 0x1)
#define PLB_REG_IPR_INT9                (0x1 << 9)
#define PLB_REG_IPR_INT9_GET(_v)        ((_v >> 9) & 0x1)
#define PLB_REG_IPR_INT10               (0x1 << 10)
#define PLB_REG_IPR_INT10_GET(_v)       ((_v >> 10) & 0x1)
#define PLB_REG_IPR_INT11               (0x1 << 11)
#define PLB_REG_IPR_INT11_GET(_v)       ((_v >> 11) & 0x1)
#define PLB_REG_IPR_INT12               (0x1 << 12)
#define PLB_REG_IPR_INT12_GET(_v)       ((_v >> 12) & 0x1)
#define PLB_REG_IPR_INT13               (0x1 << 13)
#define PLB_REG_IPR_INT13_GET(_v)       ((_v >> 13) & 0x1)
#define PLB_REG_IPR_INT14               (0x1 << 14)
#define PLB_REG_IPR_INT14_GET(_v)       ((_v >> 14) & 0x1)
#define PLB_REG_IPR_INT15               (0x1 << 15)
#define PLB_REG_IPR_INT15_GET(_v)       ((_v >> 15) & 0x1)
#define PLB_REG_IPR_INT16               (0x1 << 16)
#define PLB_REG_IPR_INT16_GET(_v)       ((_v >> 16) & 0x1)
#define PLB_REG_IPR_INT17               (0x1 << 17)
#define PLB_REG_IPR_INT17_GET(_v)       ((_v >> 17) & 0x1)
#define PLB_REG_IPR_INT18               (0x1 << 18)
#define PLB_REG_IPR_INT18_GET(_v)       ((_v >> 18) & 0x1)
#define PLB_REG_IPR_INT19               (0x1 << 19)
#define PLB_REG_IPR_INT19_GET(_v)       ((_v >> 19) & 0x1)
#define PLB_REG_IPR_INT20               (0x1 << 20)
#define PLB_REG_IPR_INT20_GET(_v)       ((_v >> 20) & 0x1)
#define PLB_REG_IPR_INT21               (0x1 << 21)
#define PLB_REG_IPR_INT21_GET(_v)       ((_v >> 21) & 0x1)
#define PLB_REG_IPR_INT22               (0x1 << 22)
#define PLB_REG_IPR_INT22_GET(_v)       ((_v >> 22) & 0x1)
#define PLB_REG_IPR_INT23               (0x1 << 23)
#define PLB_REG_IPR_INT23_GET(_v)       ((_v >> 23) & 0x1)
#define PLB_REG_IPR_INT24               (0x1 << 24)
#define PLB_REG_IPR_INT24_GET(_v)       ((_v >> 24) & 0x1)
#define PLB_REG_IPR_INT25               (0x1 << 25)
#define PLB_REG_IPR_INT25_GET(_v)       ((_v >> 25) & 0x1)
#define PLB_REG_IPR_INT26               (0x1 << 26)
#define PLB_REG_IPR_INT26_GET(_v)       ((_v >> 26) & 0x1)
#define PLB_REG_IPR_INT27               (0x1 << 27)
#define PLB_REG_IPR_INT27_GET(_v)       ((_v >> 27) & 0x1)
#define PLB_REG_IPR_INT28               (0x1 << 28)
#define PLB_REG_IPR_INT28_GET(_v)       ((_v >> 28) & 0x1)
#define PLB_REG_IPR_INT29               (0x1 << 29)
#define PLB_REG_IPR_INT29_GET(_v)       ((_v >> 29) & 0x1)
#define PLB_REG_IPR_INT30               (0x1 << 30)
#define PLB_REG_IPR_INT30_GET(_v)       ((_v >> 30) & 0x1)
#define PLB_REG_IPR_INT31               (0x1 << 31)
#define PLB_REG_IPR_INT31_GET(_v)       ((_v >> 31) & 0x1)

#define PLB_REG_IER_POFFSET             0x8
#define PLB_REG_IER                     (PLB + PLB_REG_POFFSET + PLB_REG_IER_POFFSET)
#define PLB_REG_IER_INT0                0x1
#define PLB_REG_IER_INT0_GET(_v)        (_v & 0x1)
#define PLB_REG_IER_INT1                (0x1 << 1)
#define PLB_REG_IER_INT1_GET(_v)        ((_v >> 1) & 0x1)
#define PLB_REG_IER_INT2                (0x1 << 2)
#define PLB_REG_IER_INT2_GET(_v)        ((_v >> 2) & 0x1)
#define PLB_REG_IER_INT3                (0x1 << 3)
#define PLB_REG_IER_INT3_GET(_v)        ((_v >> 3) & 0x1)
#define PLB_REG_IER_INT4                (0x1 << 4)
#define PLB_REG_IER_INT4_GET(_v)        ((_v >> 4) & 0x1)
#define PLB_REG_IER_INT5                (0x1 << 5)
#define PLB_REG_IER_INT5_GET(_v)        ((_v >> 5) & 0x1)
#define PLB_REG_IER_INT6                (0x1 << 6)
#define PLB_REG_IER_INT6_GET(_v)        ((_v >> 6) & 0x1)
#define PLB_REG_IER_INT7                (0x1 << 7)
#define PLB_REG_IER_INT7_GET(_v)        ((_v >> 7) & 0x1)
#define PLB_REG_IER_INT8                (0x1 << 8)
#define PLB_REG_IER_INT8_GET(_v)        ((_v >> 8) & 0x1)
#define PLB_REG_IER_INT9                (0x1 << 9)
#define PLB_REG_IER_INT9_GET(_v)        ((_v >> 9) & 0x1)
#define PLB_REG_IER_INT10               (0x1 << 10)
#define PLB_REG_IER_INT10_GET(_v)       ((_v >> 10) & 0x1)
#define PLB_REG_IER_INT11               (0x1 << 11)
#define PLB_REG_IER_INT11_GET(_v)       ((_v >> 11) & 0x1)
#define PLB_REG_IER_INT12               (0x1 << 12)
#define PLB_REG_IER_INT12_GET(_v)       ((_v >> 12) & 0x1)
#define PLB_REG_IER_INT13               (0x1 << 13)
#define PLB_REG_IER_INT13_GET(_v)       ((_v >> 13) & 0x1)
#define PLB_REG_IER_INT14               (0x1 << 14)
#define PLB_REG_IER_INT14_GET(_v)       ((_v >> 14) & 0x1)
#define PLB_REG_IER_INT15               (0x1 << 15)
#define PLB_REG_IER_INT15_GET(_v)       ((_v >> 15) & 0x1)
#define PLB_REG_IER_INT16               (0x1 << 16)
#define PLB_REG_IER_INT16_GET(_v)       ((_v >> 16) & 0x1)
#define PLB_REG_IER_INT17               (0x1 << 17)
#define PLB_REG_IER_INT17_GET(_v)       ((_v >> 17) & 0x1)
#define PLB_REG_IER_INT18               (0x1 << 18)
#define PLB_REG_IER_INT18_GET(_v)       ((_v >> 18) & 0x1)
#define PLB_REG_IER_INT19               (0x1 << 19)
#define PLB_REG_IER_INT19_GET(_v)       ((_v >> 19) & 0x1)
#define PLB_REG_IER_INT20               (0x1 << 20)
#define PLB_REG_IER_INT20_GET(_v)       ((_v >> 20) & 0x1)
#define PLB_REG_IER_INT21               (0x1 << 21)
#define PLB_REG_IER_INT21_GET(_v)       ((_v >> 21) & 0x1)
#define PLB_REG_IER_INT22               (0x1 << 22)
#define PLB_REG_IER_INT22_GET(_v)       ((_v >> 22) & 0x1)
#define PLB_REG_IER_INT23               (0x1 << 23)
#define PLB_REG_IER_INT23_GET(_v)       ((_v >> 23) & 0x1)
#define PLB_REG_IER_INT24               (0x1 << 24)
#define PLB_REG_IER_INT24_GET(_v)       ((_v >> 24) & 0x1)
#define PLB_REG_IER_INT25               (0x1 << 25)
#define PLB_REG_IER_INT25_GET(_v)       ((_v >> 25) & 0x1)
#define PLB_REG_IER_INT26               (0x1 << 26)
#define PLB_REG_IER_INT26_GET(_v)       ((_v >> 26) & 0x1)
#define PLB_REG_IER_INT27               (0x1 << 27)
#define PLB_REG_IER_INT27_GET(_v)       ((_v >> 27) & 0x1)
#define PLB_REG_IER_INT28               (0x1 << 28)
#define PLB_REG_IER_INT28_GET(_v)       ((_v >> 28) & 0x1)
#define PLB_REG_IER_INT29               (0x1 << 29)
#define PLB_REG_IER_INT29_GET(_v)       ((_v >> 29) & 0x1)
#define PLB_REG_IER_INT30               (0x1 << 30)
#define PLB_REG_IER_INT30_GET(_v)       ((_v >> 30) & 0x1)
#define PLB_REG_IER_INT31               (0x1 << 31)
#define PLB_REG_IER_INT31_GET(_v)       ((_v >> 31) & 0x1)

#define PLB_REG_IAR_POFFSET             0xc
#define PLB_REG_IAR                     (PLB + PLB_REG_POFFSET + PLB_REG_IAR_POFFSET)
#define PLB_REG_IAR_INT0                0x1
#define PLB_REG_IAR_INT0_GET(_v)        (_v & 0x1)
#define PLB_REG_IAR_INT1                (0x1 << 1)
#define PLB_REG_IAR_INT1_GET(_v)        ((_v >> 1) & 0x1)
#define PLB_REG_IAR_INT2                (0x1 << 2)
#define PLB_REG_IAR_INT2_GET(_v)        ((_v >> 2) & 0x1)
#define PLB_REG_IAR_INT3                (0x1 << 3)
#define PLB_REG_IAR_INT3_GET(_v)        ((_v >> 3) & 0x1)
#define PLB_REG_IAR_INT4                (0x1 << 4)
#define PLB_REG_IAR_INT4_GET(_v)        ((_v >> 4) & 0x1)
#define PLB_REG_IAR_INT5                (0x1 << 5)
#define PLB_REG_IAR_INT5_GET(_v)        ((_v >> 5) & 0x1)
#define PLB_REG_IAR_INT6                (0x1 << 6)
#define PLB_REG_IAR_INT6_GET(_v)        ((_v >> 6) & 0x1)
#define PLB_REG_IAR_INT7                (0x1 << 7)
#define PLB_REG_IAR_INT7_GET(_v)        ((_v >> 7) & 0x1)
#define PLB_REG_IAR_INT8                (0x1 << 8)
#define PLB_REG_IAR_INT8_GET(_v)        ((_v >> 8) & 0x1)
#define PLB_REG_IAR_INT9                (0x1 << 9)
#define PLB_REG_IAR_INT9_GET(_v)        ((_v >> 9) & 0x1)
#define PLB_REG_IAR_INT10               (0x1 << 10)
#define PLB_REG_IAR_INT10_GET(_v)       ((_v >> 10) & 0x1)
#define PLB_REG_IAR_INT11               (0x1 << 11)
#define PLB_REG_IAR_INT11_GET(_v)       ((_v >> 11) & 0x1)
#define PLB_REG_IAR_INT12               (0x1 << 12)
#define PLB_REG_IAR_INT12_GET(_v)       ((_v >> 12) & 0x1)
#define PLB_REG_IAR_INT13               (0x1 << 13)
#define PLB_REG_IAR_INT13_GET(_v)       ((_v >> 13) & 0x1)
#define PLB_REG_IAR_INT14               (0x1 << 14)
#define PLB_REG_IAR_INT14_GET(_v)       ((_v >> 14) & 0x1)
#define PLB_REG_IAR_INT15               (0x1 << 15)
#define PLB_REG_IAR_INT15_GET(_v)       ((_v >> 15) & 0x1)
#define PLB_REG_IAR_INT16               (0x1 << 16)
#define PLB_REG_IAR_INT16_GET(_v)       ((_v >> 16) & 0x1)
#define PLB_REG_IAR_INT17               (0x1 << 17)
#define PLB_REG_IAR_INT17_GET(_v)       ((_v >> 17) & 0x1)
#define PLB_REG_IAR_INT18               (0x1 << 18)
#define PLB_REG_IAR_INT18_GET(_v)       ((_v >> 18) & 0x1)
#define PLB_REG_IAR_INT19               (0x1 << 19)
#define PLB_REG_IAR_INT19_GET(_v)       ((_v >> 19) & 0x1)
#define PLB_REG_IAR_INT20               (0x1 << 20)
#define PLB_REG_IAR_INT20_GET(_v)       ((_v >> 20) & 0x1)
#define PLB_REG_IAR_INT21               (0x1 << 21)
#define PLB_REG_IAR_INT21_GET(_v)       ((_v >> 21) & 0x1)
#define PLB_REG_IAR_INT22               (0x1 << 22)
#define PLB_REG_IAR_INT22_GET(_v)       ((_v >> 22) & 0x1)
#define PLB_REG_IAR_INT23               (0x1 << 23)
#define PLB_REG_IAR_INT23_GET(_v)       ((_v >> 23) & 0x1)
#define PLB_REG_IAR_INT24               (0x1 << 24)
#define PLB_REG_IAR_INT24_GET(_v)       ((_v >> 24) & 0x1)
#define PLB_REG_IAR_INT25               (0x1 << 25)
#define PLB_REG_IAR_INT25_GET(_v)       ((_v >> 25) & 0x1)
#define PLB_REG_IAR_INT26               (0x1 << 26)
#define PLB_REG_IAR_INT26_GET(_v)       ((_v >> 26) & 0x1)
#define PLB_REG_IAR_INT27               (0x1 << 27)
#define PLB_REG_IAR_INT27_GET(_v)       ((_v >> 27) & 0x1)
#define PLB_REG_IAR_INT28               (0x1 << 28)
#define PLB_REG_IAR_INT28_GET(_v)       ((_v >> 28) & 0x1)
#define PLB_REG_IAR_INT29               (0x1 << 29)
#define PLB_REG_IAR_INT29_GET(_v)       ((_v >> 29) & 0x1)
#define PLB_REG_IAR_INT30               (0x1 << 30)
#define PLB_REG_IAR_INT30_GET(_v)       ((_v >> 30) & 0x1)
#define PLB_REG_IAR_INT31               (0x1 << 31)
#define PLB_REG_IAR_INT31_GET(_v)       ((_v >> 31) & 0x1)

#define PLB_REG_SIE_POFFSET             0x10
#define PLB_REG_SIE                     (PLB + PLB_REG_POFFSET + PLB_REG_SIE_POFFSET)
#define PLB_REG_SIE_INT0                0x1
#define PLB_REG_SIE_INT0_GET(_v)        (_v & 0x1)
#define PLB_REG_SIE_INT1                (0x1 << 1)
#define PLB_REG_SIE_INT1_GET(_v)        ((_v >> 1) & 0x1)
#define PLB_REG_SIE_INT2                (0x1 << 2)
#define PLB_REG_SIE_INT2_GET(_v)        ((_v >> 2) & 0x1)
#define PLB_REG_SIE_INT3                (0x1 << 3)
#define PLB_REG_SIE_INT3_GET(_v)        ((_v >> 3) & 0x1)
#define PLB_REG_SIE_INT4                (0x1 << 4)
#define PLB_REG_SIE_INT4_GET(_v)        ((_v >> 4) & 0x1)
#define PLB_REG_SIE_INT5                (0x1 << 5)
#define PLB_REG_SIE_INT5_GET(_v)        ((_v >> 5) & 0x1)
#define PLB_REG_SIE_INT6                (0x1 << 6)
#define PLB_REG_SIE_INT6_GET(_v)        ((_v >> 6) & 0x1)
#define PLB_REG_SIE_INT7                (0x1 << 7)
#define PLB_REG_SIE_INT7_GET(_v)        ((_v >> 7) & 0x1)
#define PLB_REG_SIE_INT8                (0x1 << 8)
#define PLB_REG_SIE_INT8_GET(_v)        ((_v >> 8) & 0x1)
#define PLB_REG_SIE_INT9                (0x1 << 9)
#define PLB_REG_SIE_INT9_GET(_v)        ((_v >> 9) & 0x1)
#define PLB_REG_SIE_INT10               (0x1 << 10)
#define PLB_REG_SIE_INT10_GET(_v)       ((_v >> 10) & 0x1)
#define PLB_REG_SIE_INT11               (0x1 << 11)
#define PLB_REG_SIE_INT11_GET(_v)       ((_v >> 11) & 0x1)
#define PLB_REG_SIE_INT12               (0x1 << 12)
#define PLB_REG_SIE_INT12_GET(_v)       ((_v >> 12) & 0x1)
#define PLB_REG_SIE_INT13               (0x1 << 13)
#define PLB_REG_SIE_INT13_GET(_v)       ((_v >> 13) & 0x1)
#define PLB_REG_SIE_INT14               (0x1 << 14)
#define PLB_REG_SIE_INT14_GET(_v)       ((_v >> 14) & 0x1)
#define PLB_REG_SIE_INT15               (0x1 << 15)
#define PLB_REG_SIE_INT15_GET(_v)       ((_v >> 15) & 0x1)
#define PLB_REG_SIE_INT16               (0x1 << 16)
#define PLB_REG_SIE_INT16_GET(_v)       ((_v >> 16) & 0x1)
#define PLB_REG_SIE_INT17               (0x1 << 17)
#define PLB_REG_SIE_INT17_GET(_v)       ((_v >> 17) & 0x1)
#define PLB_REG_SIE_INT18               (0x1 << 18)
#define PLB_REG_SIE_INT18_GET(_v)       ((_v >> 18) & 0x1)
#define PLB_REG_SIE_INT19               (0x1 << 19)
#define PLB_REG_SIE_INT19_GET(_v)       ((_v >> 19) & 0x1)
#define PLB_REG_SIE_INT20               (0x1 << 20)
#define PLB_REG_SIE_INT20_GET(_v)       ((_v >> 20) & 0x1)
#define PLB_REG_SIE_INT21               (0x1 << 21)
#define PLB_REG_SIE_INT21_GET(_v)       ((_v >> 21) & 0x1)
#define PLB_REG_SIE_INT22               (0x1 << 22)
#define PLB_REG_SIE_INT22_GET(_v)       ((_v >> 22) & 0x1)
#define PLB_REG_SIE_INT23               (0x1 << 23)
#define PLB_REG_SIE_INT23_GET(_v)       ((_v >> 23) & 0x1)
#define PLB_REG_SIE_INT24               (0x1 << 24)
#define PLB_REG_SIE_INT24_GET(_v)       ((_v >> 24) & 0x1)
#define PLB_REG_SIE_INT25               (0x1 << 25)
#define PLB_REG_SIE_INT25_GET(_v)       ((_v >> 25) & 0x1)
#define PLB_REG_SIE_INT26               (0x1 << 26)
#define PLB_REG_SIE_INT26_GET(_v)       ((_v >> 26) & 0x1)
#define PLB_REG_SIE_INT27               (0x1 << 27)
#define PLB_REG_SIE_INT27_GET(_v)       ((_v >> 27) & 0x1)
#define PLB_REG_SIE_INT28               (0x1 << 28)
#define PLB_REG_SIE_INT28_GET(_v)       ((_v >> 28) & 0x1)
#define PLB_REG_SIE_INT29               (0x1 << 29)
#define PLB_REG_SIE_INT29_GET(_v)       ((_v >> 29) & 0x1)
#define PLB_REG_SIE_INT30               (0x1 << 30)
#define PLB_REG_SIE_INT30_GET(_v)       ((_v >> 30) & 0x1)
#define PLB_REG_SIE_INT31               (0x1 << 31)
#define PLB_REG_SIE_INT31_GET(_v)       ((_v >> 31) & 0x1)

#define PLB_REG_CIE_POFFSET             0x14
#define PLB_REG_CIE                     (PLB + PLB_REG_POFFSET + PLB_REG_CIE_POFFSET)
#define PLB_REG_CIE_INT0                0x1
#define PLB_REG_CIE_INT0_GET(_v)        (_v & 0x1)
#define PLB_REG_CIE_INT1                (0x1 << 1)
#define PLB_REG_CIE_INT1_GET(_v)        ((_v >> 1) & 0x1)
#define PLB_REG_CIE_INT2                (0x1 << 2)
#define PLB_REG_CIE_INT2_GET(_v)        ((_v >> 2) & 0x1)
#define PLB_REG_CIE_INT3                (0x1 << 3)
#define PLB_REG_CIE_INT3_GET(_v)        ((_v >> 3) & 0x1)
#define PLB_REG_CIE_INT4                (0x1 << 4)
#define PLB_REG_CIE_INT4_GET(_v)        ((_v >> 4) & 0x1)
#define PLB_REG_CIE_INT5                (0x1 << 5)
#define PLB_REG_CIE_INT5_GET(_v)        ((_v >> 5) & 0x1)
#define PLB_REG_CIE_INT6                (0x1 << 6)
#define PLB_REG_CIE_INT6_GET(_v)        ((_v >> 6) & 0x1)
#define PLB_REG_CIE_INT7                (0x1 << 7)
#define PLB_REG_CIE_INT7_GET(_v)        ((_v >> 7) & 0x1)
#define PLB_REG_CIE_INT8                (0x1 << 8)
#define PLB_REG_CIE_INT8_GET(_v)        ((_v >> 8) & 0x1)
#define PLB_REG_CIE_INT9                (0x1 << 9)
#define PLB_REG_CIE_INT9_GET(_v)        ((_v >> 9) & 0x1)
#define PLB_REG_CIE_INT10               (0x1 << 10)
#define PLB_REG_CIE_INT10_GET(_v)       ((_v >> 10) & 0x1)
#define PLB_REG_CIE_INT11               (0x1 << 11)
#define PLB_REG_CIE_INT11_GET(_v)       ((_v >> 11) & 0x1)
#define PLB_REG_CIE_INT12               (0x1 << 12)
#define PLB_REG_CIE_INT12_GET(_v)       ((_v >> 12) & 0x1)
#define PLB_REG_CIE_INT13               (0x1 << 13)
#define PLB_REG_CIE_INT13_GET(_v)       ((_v >> 13) & 0x1)
#define PLB_REG_CIE_INT14               (0x1 << 14)
#define PLB_REG_CIE_INT14_GET(_v)       ((_v >> 14) & 0x1)
#define PLB_REG_CIE_INT15               (0x1 << 15)
#define PLB_REG_CIE_INT15_GET(_v)       ((_v >> 15) & 0x1)
#define PLB_REG_CIE_INT16               (0x1 << 16)
#define PLB_REG_CIE_INT16_GET(_v)       ((_v >> 16) & 0x1)
#define PLB_REG_CIE_INT17               (0x1 << 17)
#define PLB_REG_CIE_INT17_GET(_v)       ((_v >> 17) & 0x1)
#define PLB_REG_CIE_INT18               (0x1 << 18)
#define PLB_REG_CIE_INT18_GET(_v)       ((_v >> 18) & 0x1)
#define PLB_REG_CIE_INT19               (0x1 << 19)
#define PLB_REG_CIE_INT19_GET(_v)       ((_v >> 19) & 0x1)
#define PLB_REG_CIE_INT20               (0x1 << 20)
#define PLB_REG_CIE_INT20_GET(_v)       ((_v >> 20) & 0x1)
#define PLB_REG_CIE_INT21               (0x1 << 21)
#define PLB_REG_CIE_INT21_GET(_v)       ((_v >> 21) & 0x1)
#define PLB_REG_CIE_INT22               (0x1 << 22)
#define PLB_REG_CIE_INT22_GET(_v)       ((_v >> 22) & 0x1)
#define PLB_REG_CIE_INT23               (0x1 << 23)
#define PLB_REG_CIE_INT23_GET(_v)       ((_v >> 23) & 0x1)
#define PLB_REG_CIE_INT24               (0x1 << 24)
#define PLB_REG_CIE_INT24_GET(_v)       ((_v >> 24) & 0x1)
#define PLB_REG_CIE_INT25               (0x1 << 25)
#define PLB_REG_CIE_INT25_GET(_v)       ((_v >> 25) & 0x1)
#define PLB_REG_CIE_INT26               (0x1 << 26)
#define PLB_REG_CIE_INT26_GET(_v)       ((_v >> 26) & 0x1)
#define PLB_REG_CIE_INT27               (0x1 << 27)
#define PLB_REG_CIE_INT27_GET(_v)       ((_v >> 27) & 0x1)
#define PLB_REG_CIE_INT28               (0x1 << 28)
#define PLB_REG_CIE_INT28_GET(_v)       ((_v >> 28) & 0x1)
#define PLB_REG_CIE_INT29               (0x1 << 29)
#define PLB_REG_CIE_INT29_GET(_v)       ((_v >> 29) & 0x1)
#define PLB_REG_CIE_INT30               (0x1 << 30)
#define PLB_REG_CIE_INT30_GET(_v)       ((_v >> 30) & 0x1)
#define PLB_REG_CIE_INT31               (0x1 << 31)
#define PLB_REG_CIE_INT31_GET(_v)       ((_v >> 31) & 0x1)

#define PLB_REG_IVR_POFFSET             0x18
#define PLB_REG_IVR                     (PLB + PLB_REG_POFFSET + PLB_REG_IVR_POFFSET)

#define PLB_REG_MER_POFFSET             0x1c
#define PLB_REG_MER                     (PLB + PLB_REG_POFFSET + PLB_REG_MER_POFFSET)
#define PLB_REG_MER_ME                  0x1
#define PLB_REG_MER_ME_GET(_v)          (_v & 0x1)
#define PLB_REG_MER_HIE                 (0x1 << 1)
#define PLB_REG_MER_HIE_GET(_v)         ((_v >> 1) & 0x1)


#endif
