/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORT1' to the base of port 'bport1'
#ifndef BPORT1
#error BPORT1 is undefined. It needs to be set to the port base address
#endif


#define BPORT1_REG_POFFSET              0x0
#define BPORT1_REG_MASK_DATA_0_LSW_POFFSET  0x0
#define BPORT1_REG_MASK_DATA_0_LSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_0_LSW_POFFSET)
#define BPORT1_REG_MASK_DATA_0_LSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_0_LSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_0_LSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_0_LSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_MASK_DATA_0_MSW_POFFSET  0x4
#define BPORT1_REG_MASK_DATA_0_MSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_0_MSW_POFFSET)
#define BPORT1_REG_MASK_DATA_0_MSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_0_MSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_0_MSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_0_MSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_MASK_DATA_1_LSW_POFFSET  0x8
#define BPORT1_REG_MASK_DATA_1_LSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_1_LSW_POFFSET)
#define BPORT1_REG_MASK_DATA_1_LSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_1_LSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_1_LSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_1_LSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_MASK_DATA_1_MSW_POFFSET  0xc
#define BPORT1_REG_MASK_DATA_1_MSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_1_MSW_POFFSET)
#define BPORT1_REG_MASK_DATA_1_MSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_1_MSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_1_MSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_1_MSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_MASK_DATA_2_LSW_POFFSET  0x10
#define BPORT1_REG_MASK_DATA_2_LSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_2_LSW_POFFSET)
#define BPORT1_REG_MASK_DATA_2_LSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_2_LSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_2_LSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_2_LSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_MASK_DATA_2_MSW_POFFSET  0x14
#define BPORT1_REG_MASK_DATA_2_MSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_2_MSW_POFFSET)
#define BPORT1_REG_MASK_DATA_2_MSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_2_MSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_2_MSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_2_MSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_MASK_DATA_3_LSW_POFFSET  0x18
#define BPORT1_REG_MASK_DATA_3_LSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_3_LSW_POFFSET)
#define BPORT1_REG_MASK_DATA_3_LSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_3_LSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_3_LSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_3_LSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_MASK_DATA_3_MSW_POFFSET  0x1c
#define BPORT1_REG_MASK_DATA_3_MSW      (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_MASK_DATA_3_MSW_POFFSET)
#define BPORT1_REG_MASK_DATA_3_MSW_DATA  0xffff
#define BPORT1_REG_MASK_DATA_3_MSW_DATA_GET(_v)  (_v & 0xffff)
#define BPORT1_REG_MASK_DATA_3_MSW_MASK  (0xffff << 16)
#define BPORT1_REG_MASK_DATA_3_MSW_MASK_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_DATA_0_POFFSET       0x40
#define BPORT1_REG_DATA_0               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_0_POFFSET)
#define BPORT1_REG_DATA_0_LOW           0xffff
#define BPORT1_REG_DATA_0_LOW_GET(_v)   (_v & 0xffff)
#define BPORT1_REG_DATA_0_HIGH          (0xffff << 16)
#define BPORT1_REG_DATA_0_HIGH_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_DATA_1_POFFSET       0x44
#define BPORT1_REG_DATA_1               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_1_POFFSET)
#define BPORT1_REG_DATA_1_LOW           0xffff
#define BPORT1_REG_DATA_1_LOW_GET(_v)   (_v & 0xffff)
#define BPORT1_REG_DATA_1_HIGH          (0xffff << 16)
#define BPORT1_REG_DATA_1_HIGH_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_DATA_2_POFFSET       0x48
#define BPORT1_REG_DATA_2               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_2_POFFSET)
#define BPORT1_REG_DATA_2_LOW           0xffff
#define BPORT1_REG_DATA_2_LOW_GET(_v)   (_v & 0xffff)
#define BPORT1_REG_DATA_2_HIGH          (0xffff << 16)
#define BPORT1_REG_DATA_2_HIGH_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_DATA_3_POFFSET       0x4c
#define BPORT1_REG_DATA_3               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_3_POFFSET)
#define BPORT1_REG_DATA_3_LOW           0xffff
#define BPORT1_REG_DATA_3_LOW_GET(_v)   (_v & 0xffff)
#define BPORT1_REG_DATA_3_HIGH          (0xffff << 16)
#define BPORT1_REG_DATA_3_HIGH_GET(_v)  ((_v >> 16) & 0xffff)

#define BPORT1_REG_DIRM_0_POFFSET       0x204
#define BPORT1_REG_DIRM_0               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DIRM_0_POFFSET)

#define BPORT1_REG_OEN_0_POFFSET        0x208
#define BPORT1_REG_OEN_0                (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_OEN_0_POFFSET)

#define BPORT1_REG_INT_MASK_0_POFFSET   0x20c
#define BPORT1_REG_INT_MASK_0           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_MASK_0_POFFSET)

#define BPORT1_REG_INT_EN_0_POFFSET     0x210
#define BPORT1_REG_INT_EN_0             (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_EN_0_POFFSET)

#define BPORT1_REG_INT_DIS_0_POFFSET    0x214
#define BPORT1_REG_INT_DIS_0            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_DIS_0_POFFSET)

#define BPORT1_REG_INT_STAT_0_POFFSET   0x218
#define BPORT1_REG_INT_STAT_0           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_STAT_0_POFFSET)

#define BPORT1_REG_INT_TYPE_0_POFFSET   0x21c
#define BPORT1_REG_INT_TYPE_0           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_TYPE_0_POFFSET)

#define BPORT1_REG_INT_POLARITY_0_POFFSET  0x220
#define BPORT1_REG_INT_POLARITY_0       (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_POLARITY_0_POFFSET)

#define BPORT1_REG_INT_ANY_0_POFFSET    0x224
#define BPORT1_REG_INT_ANY_0            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_ANY_0_POFFSET)

#define BPORT1_REG_DIRM_1_POFFSET       0x244
#define BPORT1_REG_DIRM_1               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DIRM_1_POFFSET)

#define BPORT1_REG_OEN_1_POFFSET        0x248
#define BPORT1_REG_OEN_1                (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_OEN_1_POFFSET)

#define BPORT1_REG_INT_MASK_1_POFFSET   0x24c
#define BPORT1_REG_INT_MASK_1           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_MASK_1_POFFSET)

#define BPORT1_REG_INT_EN_1_POFFSET     0x250
#define BPORT1_REG_INT_EN_1             (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_EN_1_POFFSET)

#define BPORT1_REG_INT_DIS_1_POFFSET    0x254
#define BPORT1_REG_INT_DIS_1            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_DIS_1_POFFSET)

#define BPORT1_REG_INT_STAT_1_POFFSET   0x258
#define BPORT1_REG_INT_STAT_1           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_STAT_1_POFFSET)

#define BPORT1_REG_INT_TYPE_1_POFFSET   0x25c
#define BPORT1_REG_INT_TYPE_1           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_TYPE_1_POFFSET)

#define BPORT1_REG_INT_POLARITY_1_POFFSET  0x260
#define BPORT1_REG_INT_POLARITY_1       (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_POLARITY_1_POFFSET)

#define BPORT1_REG_INT_ANY_1_POFFSET    0x264
#define BPORT1_REG_INT_ANY_1            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_ANY_1_POFFSET)

#define BPORT1_REG_DIRM_2_POFFSET       0x284
#define BPORT1_REG_DIRM_2               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DIRM_2_POFFSET)

#define BPORT1_REG_OEN_2_POFFSET        0x288
#define BPORT1_REG_OEN_2                (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_OEN_2_POFFSET)

#define BPORT1_REG_INT_MASK_2_POFFSET   0x28c
#define BPORT1_REG_INT_MASK_2           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_MASK_2_POFFSET)

#define BPORT1_REG_INT_EN_2_POFFSET     0x290
#define BPORT1_REG_INT_EN_2             (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_EN_2_POFFSET)

#define BPORT1_REG_INT_DIS_2_POFFSET    0x294
#define BPORT1_REG_INT_DIS_2            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_DIS_2_POFFSET)

#define BPORT1_REG_INT_STAT_2_POFFSET   0x298
#define BPORT1_REG_INT_STAT_2           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_STAT_2_POFFSET)

#define BPORT1_REG_INT_TYPE_2_POFFSET   0x29c
#define BPORT1_REG_INT_TYPE_2           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_TYPE_2_POFFSET)

#define BPORT1_REG_INT_POLARITY_2_POFFSET  0x2a0
#define BPORT1_REG_INT_POLARITY_2       (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_POLARITY_2_POFFSET)

#define BPORT1_REG_INT_ANY_2_POFFSET    0x2a4
#define BPORT1_REG_INT_ANY_2            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_ANY_2_POFFSET)

#define BPORT1_REG_DIRM_3_POFFSET       0x2c4
#define BPORT1_REG_DIRM_3               (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DIRM_3_POFFSET)

#define BPORT1_REG_OEN_3_POFFSET        0x2c8
#define BPORT1_REG_OEN_3                (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_OEN_3_POFFSET)

#define BPORT1_REG_INT_MASK_3_POFFSET   0x2cc
#define BPORT1_REG_INT_MASK_3           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_MASK_3_POFFSET)

#define BPORT1_REG_INT_EN_3_POFFSET     0x2d0
#define BPORT1_REG_INT_EN_3             (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_EN_3_POFFSET)

#define BPORT1_REG_INT_DIS_3_POFFSET    0x2d4
#define BPORT1_REG_INT_DIS_3            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_DIS_3_POFFSET)

#define BPORT1_REG_INT_STAT_3_POFFSET   0x2d8
#define BPORT1_REG_INT_STAT_3           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_STAT_3_POFFSET)

#define BPORT1_REG_INT_TYPE_3_POFFSET   0x2dc
#define BPORT1_REG_INT_TYPE_3           (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_TYPE_3_POFFSET)

#define BPORT1_REG_INT_POLARITY_3_POFFSET  0x2e0
#define BPORT1_REG_INT_POLARITY_3       (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_POLARITY_3_POFFSET)

#define BPORT1_REG_INT_ANY_3_POFFSET    0x2e4
#define BPORT1_REG_INT_ANY_3            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_INT_ANY_3_POFFSET)

#define BPORT1_REG_BUFFER0_POFFSET      0x0
#define BPORT1_REG_BUFFER0              (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_BUFFER0_POFFSET)
#define BPORT1_REG_BUFFER0_BYTES        0x3c

#define BPORT1_REG_BUFFER1_POFFSET      0x70
#define BPORT1_REG_BUFFER1              (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_BUFFER1_POFFSET)
#define BPORT1_REG_BUFFER1_BYTES        0xf90

#define BPORT1_REG_DATA_0_RO_POFFSET    0x60
#define BPORT1_REG_DATA_0_RO            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_0_RO_POFFSET)
#define BPORT1_REG_DATA_0_RO_BYTES      0x4

#define BPORT1_REG_DATA_1_RO_POFFSET    0x64
#define BPORT1_REG_DATA_1_RO            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_1_RO_POFFSET)
#define BPORT1_REG_DATA_1_RO_BYTES      0x4

#define BPORT1_REG_DATA_2_RO_POFFSET    0x68
#define BPORT1_REG_DATA_2_RO            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_2_RO_POFFSET)
#define BPORT1_REG_DATA_2_RO_BYTES      0x4

#define BPORT1_REG_DATA_3_RO_POFFSET    0x6c
#define BPORT1_REG_DATA_3_RO            (BPORT1 + BPORT1_REG_POFFSET + BPORT1_REG_DATA_3_RO_POFFSET)
#define BPORT1_REG_DATA_3_RO_BYTES      0x4


#endif
