/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////


#include "pse.igen.h"
/////////////////////////////// Port Declarations //////////////////////////////

bport1_ab_dataT bport1_ab_data;

handlesT handles;

/////////////////////////////// Diagnostic level ///////////////////////////////

// Test this variable to determine what diagnostics to output.
// eg. if (diagnosticLevel >= 1) bhmMessage("I", "iMX6_Analog", "Example");
//     Predefined macros PSE_DIAG_LOW, PSE_DIAG_MEDIUM and PSE_DIAG_HIGH may be used
Uns32 diagnosticLevel;

/////////////////////////// Diagnostic level callback //////////////////////////

static void setDiagLevel(Uns32 new) {
    diagnosticLevel = new;
}

///////////////////////////// MMR Generic callbacks ////////////////////////////

static PPM_VIEW_CB(view32) {  *(Uns32*)data = *(Uns32*)user; }

static PPM_READ_CB(read_32) {  return *(Uns32*)user; }

static PPM_WRITE_CB(write_32) { *(Uns32*)user = data; }

//////////////////////////////// Bus Slave Ports ///////////////////////////////

static void installSlavePorts(void) {
    handles.bport1 = ppmCreateSlaveBusPort("bport1", 4096);
    if (!handles.bport1) {
        bhmMessage("E", "PPM_SPNC", "Could not connect port 'bport1'");
    }

    ppmInstallReadCallback(regNoDefinitionRead, (void*)0 , handles.bport1 + 0x0, 0x1000);
    ppmInstallWriteCallback(regNoDefinitionWrite, (void*)0 , handles.bport1 + 0x0, 0x1000);
}

//////////////////////////// Memory mapped registers ///////////////////////////

static void installRegisters(void) {

    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ARM",
            "Analog ARM PLL control Register",
            handles.bport1,
            0x0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ARM.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ARM_SET",
            0,
            handles.bport1,
            0x4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ARM_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ARM_CLR",
            0,
            handles.bport1,
            0x8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ARM_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ARM_TOG",
            0,
            handles.bport1,
            0xc,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ARM_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB1",
            "Analog USB1 480MHz PLL Control Register",
            handles.bport1,
            0x10,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB1.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB1_SET",
            0,
            handles.bport1,
            0x14,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB1_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB1_CLR",
            0,
            handles.bport1,
            0x18,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB1_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB1_TOG",
            0,
            handles.bport1,
            0x1c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB1_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB2",
            "Analog USB2 480MHz PLL Control Register",
            handles.bport1,
            0x20,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB2.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB2_SET",
            0,
            handles.bport1,
            0x24,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB2_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB2_CLR",
            0,
            handles.bport1,
            0x28,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB2_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_USB2_TOG",
            0,
            handles.bport1,
            0x2c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_USB2_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_SYS",
            "Analog System PLL Control Register (modified reset value)",
            handles.bport1,
            0x30,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_SYS.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_SYS_SET",
            0,
            handles.bport1,
            0x34,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_SYS_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_SYS_CLR",
            0,
            handles.bport1,
            0x38,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_SYS_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_SYS_TOG",
            0,
            handles.bport1,
            0x3c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_SYS_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_SYS_SS",
            "528MHz System PLL Spread Spectrum Register",
            handles.bport1,
            0x40,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_SYS_SS.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_SYS_SYS_NUM",
            "Numerator of 528MHz System PLL Fractional Loop Divider Register",
            handles.bport1,
            0x50,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_SYS_SYS_NUM.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_SYS_SYS_DENOM",
            "Denominator of 528MHz System PLL Fractional Loop Divider Register",
            handles.bport1,
            0x60,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_SYS_SYS_DENOM.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO",
            "Analog Audio PLL control Register",
            handles.bport1,
            0x70,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_SET",
            0,
            handles.bport1,
            0x74,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_CLR",
            0,
            handles.bport1,
            0x78,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_TOG",
            0,
            handles.bport1,
            0x7c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_NUM",
            "Numerator of Audio PLL Fractional Loop Divider Register",
            handles.bport1,
            0x80,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_NUM.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_NUM_SET",
            0,
            handles.bport1,
            0x84,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_NUM_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_NUM_CLR",
            0,
            handles.bport1,
            0x88,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_NUM_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_NUM_TOG",
            0,
            handles.bport1,
            0x8c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_NUM_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_DENOM",
            "Denominator of Audio PLL Fractional Loop Divider Register",
            handles.bport1,
            0x90,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_DENOM.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_DENOM_SET",
            0,
            handles.bport1,
            0x94,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_DENOM_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_DENOM_CLR",
            0,
            handles.bport1,
            0x98,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_DENOM_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_AUDIO_DENOM_TOG",
            0,
            handles.bport1,
            0x9c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_DENOM_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO",
            "Analog Video PLL control Register",
            handles.bport1,
            0xa0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_SET",
            0,
            handles.bport1,
            0xa4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_CLR",
            0,
            handles.bport1,
            0xa8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_TOG",
            0,
            handles.bport1,
            0xac,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_NUM",
            "Numerator of Video PLL Fractional Loop Divider Register",
            handles.bport1,
            0xb0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_NUM.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_NUM_SET",
            0,
            handles.bport1,
            0xb4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_NUM_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_NUM_CLR",
            0,
            handles.bport1,
            0xb8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_NUM_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_NUM_TOG",
            0,
            handles.bport1,
            0xbc,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_NUM_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_DENOM",
            "Denominator of Video PLL Fractional Loop Divider Register",
            handles.bport1,
            0xc0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_DENOM.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_DENOM_SET",
            0,
            handles.bport1,
            0xc4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_DENOM_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_DENOM_CLR",
            0,
            handles.bport1,
            0xc8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_DENOM_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_VIDEO_DENOM_TOG",
            0,
            handles.bport1,
            0xcc,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_DENOM_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_MLB",
            "Analog MLB PLL Control Register",
            handles.bport1,
            0xd0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_MLB.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_MLB_SET",
            0,
            handles.bport1,
            0xd4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_MLB_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_MLB_CLR",
            0,
            handles.bport1,
            0xd8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_MLB_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_MLB_TOG",
            0,
            handles.bport1,
            0xdc,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_MLB_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ENET",
            "Analog ENET PLL Control Register",
            handles.bport1,
            0xe0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ENET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ENET_SET",
            0,
            handles.bport1,
            0xe4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ENET_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ENET_CLR",
            0,
            handles.bport1,
            0xe8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ENET_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PLL_ENET_TOG",
            0,
            handles.bport1,
            0xec,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PLL_ENET_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_480",
            "480MHz Clock (PLL3) Phase Fractional Divider Control Register",
            handles.bport1,
            0xf0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_480.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_480_SET",
            0,
            handles.bport1,
            0xf4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_480_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_480_CLR",
            0,
            handles.bport1,
            0xf8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_480_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_480_TOG",
            0,
            handles.bport1,
            0xfc,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_480_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_528",
            "528MHz Clock (PLL2) Phase Fractional Divider Control Register",
            handles.bport1,
            0x100,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_528.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_528_SET",
            0,
            handles.bport1,
            0x104,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_528_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_528_CLR",
            0,
            handles.bport1,
            0x108,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_528_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_CCM_ANALOG_PFD_528_TOG",
            0,
            handles.bport1,
            0x10c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.CCM_ANALOG_PFD_528_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_1P1",
            "Regulator 1P1 Register",
            handles.bport1,
            0x110,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.PMU_REG_1P1.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_1P1_SET",
            0,
            handles.bport1,
            0x114,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.PMU_REG_1P1_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_1P1_CLR",
            0,
            handles.bport1,
            0x118,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.PMU_REG_1P1_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_1P1_TOG",
            0,
            handles.bport1,
            0x11c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.PMU_REG_1P1_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_3P0",
            "Regulator 3P0 Register",
            handles.bport1,
            0x120,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.PMU_REG_3P0.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_3P0_SET",
            0,
            handles.bport1,
            0x124,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.PMU_REG_3P0_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_3P0_CLR",
            0,
            handles.bport1,
            0x128,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.PMU_REG_3P0_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_3P0_TOG",
            0,
            handles.bport1,
            0x12c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.PMU_REG_3P0_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_2P5",
            "Regulator 2P5 Register",
            handles.bport1,
            0x130,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.PMU_REG_2P5.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_2P5_SET",
            0,
            handles.bport1,
            0x134,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.PMU_REG_2P5_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_2P5_CLR",
            0,
            handles.bport1,
            0x138,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.PMU_REG_2P5_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_2P5_TOG",
            0,
            handles.bport1,
            0x13c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.PMU_REG_2P5_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_CORE",
            "Digital Regulator Core Registerr",
            handles.bport1,
            0x140,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.PMU_REG_CORE.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_CORE_SET",
            0,
            handles.bport1,
            0x144,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.PMU_REG_CORE_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_CORE_CLR",
            0,
            handles.bport1,
            0x148,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.PMU_REG_CORE_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_PMU_REG_CORE_TOG",
            0,
            handles.bport1,
            0x14c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.PMU_REG_CORE_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC0",
            "Miscellaneous Register 0",
            handles.bport1,
            0x150,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.MISC0.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC0_SET",
            0,
            handles.bport1,
            0x154,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.MISC0_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC0_CLR",
            0,
            handles.bport1,
            0x158,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.MISC0_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC0_TOG",
            0,
            handles.bport1,
            0x15c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.MISC0_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC1",
            "Miscellaneous Register 1",
            handles.bport1,
            0x160,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.MISC1.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC1_SET",
            0,
            handles.bport1,
            0x164,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.MISC1_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC1_CLR",
            0,
            handles.bport1,
            0x168,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.MISC1_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC1_TOG",
            0,
            handles.bport1,
            0x16c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.MISC1_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC2",
            "Miscellaneous Register 2",
            handles.bport1,
            0x170,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.MISC2.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC2_SET",
            0,
            handles.bport1,
            0x174,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.MISC2_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC2_CLR",
            0,
            handles.bport1,
            0x178,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.MISC2_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_MISC2_TOG",
            0,
            handles.bport1,
            0x17c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.MISC2_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_VBUS_DETECT",
            "USB VBUS Detect Register",
            handles.bport1,
            0x1a0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_VBUS_DETECT_SET",
            0,
            handles.bport1,
            0x1a4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_VBUS_DETECT_CLR",
            0,
            handles.bport1,
            0x1a8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_VBUS_DETECT_TOG",
            0,
            handles.bport1,
            0x1ac,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_CHRG_DETECT",
            "USB Charger Detect Register",
            handles.bport1,
            0x1b0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_CHRG_DETECT_SET",
            0,
            handles.bport1,
            0x1b4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_CHRG_DETECT_CLR",
            0,
            handles.bport1,
            0x1b8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_CHRG_DETECT_TOG",
            0,
            handles.bport1,
            0x1bc,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_VBUS_DETECT_STAT",
            "USB VBUS Detect Status Register",
            handles.bport1,
            0x1c0,
            4,
            read_32,
            0,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT_STAT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_CHRG_DETECT_STAT",
            "USB Charger Detect Status Register",
            handles.bport1,
            0x1d0,
            4,
            read_32,
            0,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT_STAT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_MISC",
            "USB Misc Register",
            handles.bport1,
            0x1f0,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_MISC.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_MISC_SET",
            0,
            handles.bport1,
            0x1f4,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_MISC_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_MISC_CLR",
            0,
            handles.bport1,
            0x1f8,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_MISC_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB1_MISC_TOG",
            0,
            handles.bport1,
            0x1fc,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB1_MISC_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_VBUS_DETECT",
            "USB VBUS Detect Register",
            handles.bport1,
            0x200,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_VBUS_DETECT_SET",
            0,
            handles.bport1,
            0x204,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_VBUS_DETECT_CLR",
            0,
            handles.bport1,
            0x208,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_VBUS_DETECT_TOG",
            0,
            handles.bport1,
            0x20c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_CHRG_DETECT",
            "USB Charger Detect Register",
            handles.bport1,
            0x210,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_CHRG_DETECT_SET",
            0,
            handles.bport1,
            0x214,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_CHRG_DETECT_CLR",
            0,
            handles.bport1,
            0x218,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_CHRG_DETECT_TOG",
            0,
            handles.bport1,
            0x21c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_VBUS_DETECT_STAT",
            "USB VBUS Detect Status Register",
            handles.bport1,
            0x220,
            4,
            read_32,
            0,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT_STAT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_CHRG_DETECT_STAT",
            "USB Charger Detect Status Register",
            handles.bport1,
            0x230,
            4,
            read_32,
            0,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT_STAT.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_MISC",
            "USB Misc Register",
            handles.bport1,
            0x250,
            4,
            read_32,
            write_32,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_MISC.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_MISC_SET",
            0,
            handles.bport1,
            0x254,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_MISC_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_MISC_CLR",
            0,
            handles.bport1,
            0x258,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_MISC_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_USB2_MISC_TOG",
            0,
            handles.bport1,
            0x25c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_USB2_MISC_TOG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_DIGPROG",
            "Chip Silicon Version (modified reset value)",
            handles.bport1,
            0x260,
            4,
            read_32,
            0,
            view32,
            &(bport1_ab_data.USB_ANALOG_DIGPROG.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_DIGPROG_SET",
            0,
            handles.bport1,
            0x264,
            4,
            ReadZero,
            SetBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_DIGPROG_SET.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_DIGPROG_CLR",
            0,
            handles.bport1,
            0x268,
            4,
            ReadZero,
            ClrBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_DIGPROG_CLR.value),
            True
        );
    }
    {
        ppmCreateRegister(
            "ab_USB_ANALOG_DIGPROG_TOG",
            0,
            handles.bport1,
            0x26c,
            4,
            ReadZero,
            TogBits,
            view32,
            &(bport1_ab_data.USB_ANALOG_DIGPROG_TOG.value),
            True
        );
    }

}

PPM_NET_CB(reset_resetNet) {
    if(value != 0 ) {
        bport1_ab_data.USB_ANALOG_DIGPROG.value = (Uns32)(bport1_ab_data.USB_ANALOG_DIGPROG.value & ~(0xffffffff)) | ((0xffffffff) & (0x00610000));
        bport1_ab_data.USB_ANALOG_USB2_MISC.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB2_MISC.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000002));
        bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT_STAT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT_STAT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT_STAT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT_STAT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB2_CHRG_DETECT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB2_VBUS_DETECT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00100004));
        bport1_ab_data.USB_ANALOG_USB1_MISC.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB1_MISC.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000002));
        bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT_STAT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT_STAT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT_STAT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT_STAT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB1_CHRG_DETECT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT.value = (Uns32)(bport1_ab_data.USB_ANALOG_USB1_VBUS_DETECT.value & ~(0xffffffff)) | ((0xffffffff) & (0x00100004));
        bport1_ab_data.MISC2.value = (Uns32)(bport1_ab_data.MISC2.value & ~(0xffffffff)) | ((0xffffffff) & (0x00272727));
        bport1_ab_data.MISC1.value = (Uns32)(bport1_ab_data.MISC1.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.MISC0.value = (Uns32)(bport1_ab_data.MISC0.value & ~(0xffffffff)) | ((0xffffffff) & (0x04000000));
        bport1_ab_data.PMU_REG_CORE.value = (Uns32)(bport1_ab_data.PMU_REG_CORE.value & ~(0xffffffff)) | ((0xffffffff) & (0x00402010));
        bport1_ab_data.PMU_REG_2P5.value = (Uns32)(bport1_ab_data.PMU_REG_2P5.value & ~(0xffffffff)) | ((0xffffffff) & (0x00005071));
        bport1_ab_data.PMU_REG_3P0.value = (Uns32)(bport1_ab_data.PMU_REG_3P0.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000f74));
        bport1_ab_data.PMU_REG_1P1.value = (Uns32)(bport1_ab_data.PMU_REG_1P1.value & ~(0xffffffff)) | ((0xffffffff) & (0x00001073));
        bport1_ab_data.CCM_ANALOG_PFD_528.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PFD_528.value & ~(0xffffffff)) | ((0xffffffff) & (0x1018101B));
        bport1_ab_data.CCM_ANALOG_PFD_480.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PFD_480.value & ~(0xffffffff)) | ((0xffffffff) & (0x1311100C));
        bport1_ab_data.CCM_ANALOG_PLL_ENET.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_ENET.value & ~(0xffffffff)) | ((0xffffffff) & (0x80011001));
        bport1_ab_data.CCM_ANALOG_PLL_MLB.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_MLB.value & ~(0xffffffff)) | ((0xffffffff) & (0x80010000));
        bport1_ab_data.CCM_ANALOG_PLL_VIDEO_DENOM.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_DENOM.value & ~(0xffffffff)) | ((0xffffffff) & (0x10A24447));
        bport1_ab_data.CCM_ANALOG_PLL_VIDEO_NUM.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_VIDEO_NUM.value & ~(0xffffffff)) | ((0xffffffff) & (0x05F5E100));
        bport1_ab_data.CCM_ANALOG_PLL_VIDEO.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_VIDEO.value & ~(0xffffffff)) | ((0xffffffff) & (0x8001100C));
        bport1_ab_data.CCM_ANALOG_PLL_AUDIO_DENOM.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_DENOM.value & ~(0xffffffff)) | ((0xffffffff) & (0x2964619C));
        bport1_ab_data.CCM_ANALOG_PLL_AUDIO_NUM.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_AUDIO_NUM.value & ~(0xffffffff)) | ((0xffffffff) & (0x05F5E100));
        bport1_ab_data.CCM_ANALOG_PLL_AUDIO.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_AUDIO.value & ~(0xffffffff)) | ((0xffffffff) & (0x80011006));
        bport1_ab_data.CCM_ANALOG_PLL_SYS_SYS_DENOM.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_SYS_SYS_DENOM.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000012));
        bport1_ab_data.CCM_ANALOG_PLL_SYS_SYS_NUM.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_SYS_SYS_NUM.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.CCM_ANALOG_PLL_SYS_SS.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_SYS_SS.value & ~(0xffffffff)) | ((0xffffffff) & (0x00000000));
        bport1_ab_data.CCM_ANALOG_PLL_SYS.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_SYS.value & ~(0xffffffff)) | ((0xffffffff) & (0x80013001));
        bport1_ab_data.CCM_ANALOG_PLL_USB2.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_USB2.value & ~(0xffffffff)) | ((0xffffffff) & (0x80012000));
        bport1_ab_data.CCM_ANALOG_PLL_USB1.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_USB1.value & ~(0xffffffff)) | ((0xffffffff) & (0x80012000));
        bport1_ab_data.CCM_ANALOG_PLL_ARM.value = (Uns32)(bport1_ab_data.CCM_ANALOG_PLL_ARM.value & ~(0xffffffff)) | ((0xffffffff) & (0x80013042));
    }
}

PPM_DOC_FN(installDocs){

    ppmDocNodeP Root1_node = ppmDocAddSection(0, "Root");
    {
        ppmDocNodeP doc2_node = ppmDocAddSection(Root1_node, "Description");
        ppmDocAddText(doc2_node, "NXP i.MX6 ANALOG: (PLLs, PFDs, Regulators, LDOs, Temp Sensor) Registers");
        ppmDocNodeP doc_12_node = ppmDocAddSection(Root1_node, "Licensing");
        ppmDocAddText(doc_12_node, "Open Source Apache 2.0");
        ppmDocNodeP doc_22_node = ppmDocAddSection(Root1_node, "Limitations");
        ppmDocAddText(doc_22_node, "\nThis is a register only interface model. No functionality is implemented.\nThe reset values for registers have been modified from those specified in the documentation to set the lock bit (bit 31) on PLL registers.\n");
        ppmDocNodeP doc_32_node = ppmDocAddSection(Root1_node, "Reference");
        ppmDocAddText(doc_32_node, "i.MX 6Solo/6DualLite Applications Processor Reference Manual (IMX6SDLRM_Ref_Manual.pdf");
    }
}
////////////////////////////////// Constructor /////////////////////////////////

PPM_CONSTRUCTOR_CB(periphConstructor) {
    installSlavePorts();
    installRegisters();
    reset_resetNet(1,0);
}

///////////////////////////////////// Main /////////////////////////////////////

int main(int argc, char *argv[]) {

    diagnosticLevel = 0;
    bhmInstallDiagCB(setDiagLevel);
    constructor();

    bhmWaitEvent(bhmGetSystemEvent(BHM_SE_END_OF_SIMULATION));
    destructor();
    return 0;
}

