/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORT1' to the base of port 'bport1'
#ifndef BPORT1
#error BPORT1 is undefined. It needs to be set to the port base address
#endif


#define BPORT1_AB_POFFSET               0x0
#define BPORT1_AB_CLOCK_CONTROL_1_POFFSET  0x0
#define BPORT1_AB_CLOCK_CONTROL_1       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_CLOCK_CONTROL_1_POFFSET)
#define BPORT1_AB_CLOCK_CONTROL_1_E     (0x1 << 6)
#define BPORT1_AB_CLOCK_CONTROL_1_E_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_CLOCK_CONTROL_1_SRC   (0x1 << 5)
#define BPORT1_AB_CLOCK_CONTROL_1_SRC_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_CLOCK_CONTROL_1_PS_V  (0xf << 1)
#define BPORT1_AB_CLOCK_CONTROL_1_PS_V_GET(_v)  ((_v >> 1) & 0xf)
#define BPORT1_AB_CLOCK_CONTROL_1_PS_EN  0x1
#define BPORT1_AB_CLOCK_CONTROL_1_PS_EN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_CLOCK_CONTROL_2_POFFSET  0x4
#define BPORT1_AB_CLOCK_CONTROL_2       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_CLOCK_CONTROL_2_POFFSET)
#define BPORT1_AB_CLOCK_CONTROL_2_E     (0x1 << 6)
#define BPORT1_AB_CLOCK_CONTROL_2_E_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_CLOCK_CONTROL_2_SRC   (0x1 << 5)
#define BPORT1_AB_CLOCK_CONTROL_2_SRC_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_CLOCK_CONTROL_2_PS_V  (0xf << 1)
#define BPORT1_AB_CLOCK_CONTROL_2_PS_V_GET(_v)  ((_v >> 1) & 0xf)
#define BPORT1_AB_CLOCK_CONTROL_2_PS_EN  0x1
#define BPORT1_AB_CLOCK_CONTROL_2_PS_EN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_CLOCK_CONTROL_3_POFFSET  0x8
#define BPORT1_AB_CLOCK_CONTROL_3       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_CLOCK_CONTROL_3_POFFSET)
#define BPORT1_AB_CLOCK_CONTROL_3_E     (0x1 << 6)
#define BPORT1_AB_CLOCK_CONTROL_3_E_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_CLOCK_CONTROL_3_SRC   (0x1 << 5)
#define BPORT1_AB_CLOCK_CONTROL_3_SRC_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_CLOCK_CONTROL_3_PS_V  (0xf << 1)
#define BPORT1_AB_CLOCK_CONTROL_3_PS_V_GET(_v)  ((_v >> 1) & 0xf)
#define BPORT1_AB_CLOCK_CONTROL_3_PS_EN  0x1
#define BPORT1_AB_CLOCK_CONTROL_3_PS_EN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_COUNTER_CONTROL_1_POFFSET  0xc
#define BPORT1_AB_COUNTER_CONTROL_1     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_COUNTER_CONTROL_1_POFFSET)
#define BPORT1_AB_COUNTER_CONTROL_1_WAVPOL  (0x1 << 6)
#define BPORT1_AB_COUNTER_CONTROL_1_WAVPOL_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_1_WAVEN  (0x1 << 5)
#define BPORT1_AB_COUNTER_CONTROL_1_WAVEN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_1_RST  (0x1 << 4)
#define BPORT1_AB_COUNTER_CONTROL_1_RST_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_1_MATCH  (0x1 << 3)
#define BPORT1_AB_COUNTER_CONTROL_1_MATCH_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_1_DEC  (0x1 << 2)
#define BPORT1_AB_COUNTER_CONTROL_1_DEC_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_1_INT  (0x1 << 1)
#define BPORT1_AB_COUNTER_CONTROL_1_INT_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_1_DIS  0x1
#define BPORT1_AB_COUNTER_CONTROL_1_DIS_GET(_v)  (_v & 0x1)

#define BPORT1_AB_COUNTER_CONTROL_2_POFFSET  0x10
#define BPORT1_AB_COUNTER_CONTROL_2     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_COUNTER_CONTROL_2_POFFSET)
#define BPORT1_AB_COUNTER_CONTROL_2_WAVPOL  (0x1 << 6)
#define BPORT1_AB_COUNTER_CONTROL_2_WAVPOL_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_2_WAVEN  (0x1 << 5)
#define BPORT1_AB_COUNTER_CONTROL_2_WAVEN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_2_RST  (0x1 << 4)
#define BPORT1_AB_COUNTER_CONTROL_2_RST_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_2_MATCH  (0x1 << 3)
#define BPORT1_AB_COUNTER_CONTROL_2_MATCH_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_2_DEC  (0x1 << 2)
#define BPORT1_AB_COUNTER_CONTROL_2_DEC_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_2_INT  (0x1 << 1)
#define BPORT1_AB_COUNTER_CONTROL_2_INT_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_2_DIS  0x1
#define BPORT1_AB_COUNTER_CONTROL_2_DIS_GET(_v)  (_v & 0x1)

#define BPORT1_AB_COUNTER_CONTROL_3_POFFSET  0x14
#define BPORT1_AB_COUNTER_CONTROL_3     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_COUNTER_CONTROL_3_POFFSET)
#define BPORT1_AB_COUNTER_CONTROL_3_WAVPOL  (0x1 << 6)
#define BPORT1_AB_COUNTER_CONTROL_3_WAVPOL_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_3_WAVEN  (0x1 << 5)
#define BPORT1_AB_COUNTER_CONTROL_3_WAVEN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_3_RST  (0x1 << 4)
#define BPORT1_AB_COUNTER_CONTROL_3_RST_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_3_MATCH  (0x1 << 3)
#define BPORT1_AB_COUNTER_CONTROL_3_MATCH_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_3_DEC  (0x1 << 2)
#define BPORT1_AB_COUNTER_CONTROL_3_DEC_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_3_INT  (0x1 << 1)
#define BPORT1_AB_COUNTER_CONTROL_3_INT_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_COUNTER_CONTROL_3_DIS  0x1
#define BPORT1_AB_COUNTER_CONTROL_3_DIS_GET(_v)  (_v & 0x1)

#define BPORT1_AB_COUNTER_VALUE_1_POFFSET  0x18
#define BPORT1_AB_COUNTER_VALUE_1       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_COUNTER_VALUE_1_POFFSET)

#define BPORT1_AB_COUNTER_VALUE_2_POFFSET  0x1c
#define BPORT1_AB_COUNTER_VALUE_2       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_COUNTER_VALUE_2_POFFSET)

#define BPORT1_AB_COUNTER_VALUE_3_POFFSET  0x20
#define BPORT1_AB_COUNTER_VALUE_3       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_COUNTER_VALUE_3_POFFSET)

#define BPORT1_AB_INTERVAL_COUNTER_1_POFFSET  0x24
#define BPORT1_AB_INTERVAL_COUNTER_1    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERVAL_COUNTER_1_POFFSET)

#define BPORT1_AB_INTERVAL_COUNTER_2_POFFSET  0x28
#define BPORT1_AB_INTERVAL_COUNTER_2    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERVAL_COUNTER_2_POFFSET)

#define BPORT1_AB_INTERVAL_COUNTER_3_POFFSET  0x2c
#define BPORT1_AB_INTERVAL_COUNTER_3    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERVAL_COUNTER_3_POFFSET)

#define BPORT1_AB_MATCH_1_COUNTER_1_POFFSET  0x30
#define BPORT1_AB_MATCH_1_COUNTER_1     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_1_COUNTER_1_POFFSET)

#define BPORT1_AB_MATCH_1_COUNTER_2_POFFSET  0x34
#define BPORT1_AB_MATCH_1_COUNTER_2     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_1_COUNTER_2_POFFSET)

#define BPORT1_AB_MATCH_1_COUNTER_3_POFFSET  0x38
#define BPORT1_AB_MATCH_1_COUNTER_3     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_1_COUNTER_3_POFFSET)

#define BPORT1_AB_MATCH_2_COUNTER_1_POFFSET  0x3c
#define BPORT1_AB_MATCH_2_COUNTER_1     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_2_COUNTER_1_POFFSET)

#define BPORT1_AB_MATCH_2_COUNTER_2_POFFSET  0x40
#define BPORT1_AB_MATCH_2_COUNTER_2     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_2_COUNTER_2_POFFSET)

#define BPORT1_AB_MATCH_2_COUNTER_3_POFFSET  0x44
#define BPORT1_AB_MATCH_2_COUNTER_3     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_2_COUNTER_3_POFFSET)

#define BPORT1_AB_MATCH_3_COUNTER_1_POFFSET  0x48
#define BPORT1_AB_MATCH_3_COUNTER_1     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_3_COUNTER_1_POFFSET)

#define BPORT1_AB_MATCH_3_COUNTER_2_POFFSET  0x4c
#define BPORT1_AB_MATCH_3_COUNTER_2     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_3_COUNTER_2_POFFSET)

#define BPORT1_AB_MATCH_3_COUNTER_3_POFFSET  0x50
#define BPORT1_AB_MATCH_3_COUNTER_3     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MATCH_3_COUNTER_3_POFFSET)

#define BPORT1_AB_INTERRUPT_REGISTER_1_POFFSET  0x54
#define BPORT1_AB_INTERRUPT_REGISTER_1  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_REGISTER_1_POFFSET)
#define BPORT1_AB_INTERRUPT_REGISTER_1_EV  (0x1 << 5)
#define BPORT1_AB_INTERRUPT_REGISTER_1_EV_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_1_OV  (0x1 << 4)
#define BPORT1_AB_INTERRUPT_REGISTER_1_OV_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_1_M3  (0x1 << 3)
#define BPORT1_AB_INTERRUPT_REGISTER_1_M3_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_1_M2  (0x1 << 2)
#define BPORT1_AB_INTERRUPT_REGISTER_1_M2_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_1_M1  (0x1 << 1)
#define BPORT1_AB_INTERRUPT_REGISTER_1_M1_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_1_IV  0x1
#define BPORT1_AB_INTERRUPT_REGISTER_1_IV_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTERRUPT_REGISTER_2_POFFSET  0x58
#define BPORT1_AB_INTERRUPT_REGISTER_2  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_REGISTER_2_POFFSET)
#define BPORT1_AB_INTERRUPT_REGISTER_2_EV  (0x1 << 5)
#define BPORT1_AB_INTERRUPT_REGISTER_2_EV_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_2_OV  (0x1 << 4)
#define BPORT1_AB_INTERRUPT_REGISTER_2_OV_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_2_M3  (0x1 << 3)
#define BPORT1_AB_INTERRUPT_REGISTER_2_M3_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_2_M2  (0x1 << 2)
#define BPORT1_AB_INTERRUPT_REGISTER_2_M2_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_2_M1  (0x1 << 1)
#define BPORT1_AB_INTERRUPT_REGISTER_2_M1_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_2_IV  0x1
#define BPORT1_AB_INTERRUPT_REGISTER_2_IV_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTERRUPT_REGISTER_3_POFFSET  0x5c
#define BPORT1_AB_INTERRUPT_REGISTER_3  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_REGISTER_3_POFFSET)
#define BPORT1_AB_INTERRUPT_REGISTER_3_EV  (0x1 << 5)
#define BPORT1_AB_INTERRUPT_REGISTER_3_EV_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_3_OV  (0x1 << 4)
#define BPORT1_AB_INTERRUPT_REGISTER_3_OV_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_3_M3  (0x1 << 3)
#define BPORT1_AB_INTERRUPT_REGISTER_3_M3_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_3_M2  (0x1 << 2)
#define BPORT1_AB_INTERRUPT_REGISTER_3_M2_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_3_M1  (0x1 << 1)
#define BPORT1_AB_INTERRUPT_REGISTER_3_M1_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_INTERRUPT_REGISTER_3_IV  0x1
#define BPORT1_AB_INTERRUPT_REGISTER_3_IV_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTERRUPT_ENABLE_1_POFFSET  0x60
#define BPORT1_AB_INTERRUPT_ENABLE_1    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_ENABLE_1_POFFSET)

#define BPORT1_AB_INTERRUPT_ENABLE_2_POFFSET  0x64
#define BPORT1_AB_INTERRUPT_ENABLE_2    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_ENABLE_2_POFFSET)

#define BPORT1_AB_INTERRUPT_ENABLE_3_POFFSET  0x68
#define BPORT1_AB_INTERRUPT_ENABLE_3    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_ENABLE_3_POFFSET)

#define BPORT1_AB_EVENT_CONTROL_TIMER_1_POFFSET  0x6c
#define BPORT1_AB_EVENT_CONTROL_TIMER_1  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_EVENT_CONTROL_TIMER_1_POFFSET)
#define BPORT1_AB_EVENT_CONTROL_TIMER_1_OV  (0x1 << 2)
#define BPORT1_AB_EVENT_CONTROL_TIMER_1_OV_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_1_LO  (0x1 << 1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_1_LO_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_1_EN  0x1
#define BPORT1_AB_EVENT_CONTROL_TIMER_1_EN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_EVENT_CONTROL_TIMER_2_POFFSET  0x70
#define BPORT1_AB_EVENT_CONTROL_TIMER_2  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_EVENT_CONTROL_TIMER_2_POFFSET)
#define BPORT1_AB_EVENT_CONTROL_TIMER_2_OV  (0x1 << 2)
#define BPORT1_AB_EVENT_CONTROL_TIMER_2_OV_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_2_LO  (0x1 << 1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_2_LO_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_2_EN  0x1
#define BPORT1_AB_EVENT_CONTROL_TIMER_2_EN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_EVENT_CONTROL_TIMER_3_POFFSET  0x74
#define BPORT1_AB_EVENT_CONTROL_TIMER_3  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_EVENT_CONTROL_TIMER_3_POFFSET)
#define BPORT1_AB_EVENT_CONTROL_TIMER_3_OV  (0x1 << 2)
#define BPORT1_AB_EVENT_CONTROL_TIMER_3_OV_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_3_LO  (0x1 << 1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_3_LO_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_EVENT_CONTROL_TIMER_3_EN  0x1
#define BPORT1_AB_EVENT_CONTROL_TIMER_3_EN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_EVENT_REGISTER_1_POFFSET  0x78
#define BPORT1_AB_EVENT_REGISTER_1      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_EVENT_REGISTER_1_POFFSET)

#define BPORT1_AB_EVENT_REGISTER_2_POFFSET  0x7c
#define BPORT1_AB_EVENT_REGISTER_2      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_EVENT_REGISTER_2_POFFSET)

#define BPORT1_AB_EVENT_REGISTER_3_POFFSET  0x80
#define BPORT1_AB_EVENT_REGISTER_3      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_EVENT_REGISTER_3_POFFSET)

#define BPORT1_AB_BUFFER_POFFSET        0x0
#define BPORT1_AB_BUFFER                (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER_POFFSET)
#define BPORT1_AB_BUFFER_BYTES          0x1000


#endif
