IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")
CFLAGS += -I$(IMPERAS_HOME)/SimCommon/include
CFLAGS += -I$(IMPERAS_HOME)/Examples/Models/Processor/25.or1kExtended
VERBOSE=1
include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.host
