/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                           Imperas/OVP Generated
//
////////////////////////////////////////////////////////////////////////////////


#include <string.h>
#include <stdlib.h>

#include "op/op.h"


#define MODULE_NAME "Zynq_PS"

// information to pass to callback
typedef struct netCBInfoS {
    optNetP         netDerate;          // Nets generated by SLCR with derate value
    optProcessorP   pARM;               // ARM core processor handle
    Uns32           diagnosticlevel;    // enable diagnostics
} netCBInfo;

typedef struct optModuleObjectS {
    // insert module persistent data here
    netCBInfo infoARM0;
    netCBInfo infoARM1;
} optModuleObject;




// forward declaration of component constructor
static OP_CONSTRUCT_FN(instantiateComponents);

//
// When the deration nets from the SLCR are written intercept the write and
// use this to derate the ARM processor
// Note: applied to individual cores to allow clock gating i.e. derate 100%
//
static OP_NET_WRITE_FN(derateARMCB) {
    netCBInfo *info = (netCBInfo *) userData;

    if(info->diagnosticlevel) {
        opMessage("I", MODULE_NAME, "Derate %s at %d%%\n", opObjectName(info->pARM), (Uns32)value);
    }
    opProcessorDerate (info->pARM, (double) value);
}

static OP_CONSTRUCT_FN(moduleConstructor) {

    // instantiate module components
    instantiateComponents(mi, object);

    //
    // The SLCR clock control registers calculate the deration to be applied to the
    // ARM processor cores based upon the defined nominla MIPS rate and register values
    //

    // Get deration net and ARM processor objects
    object->infoARM0.netDerate = opObjectByName(mi,  "ARM0Deration", OP_NET_EN).Net;
    object->infoARM0.pARM      = opObjectByName(mi,  "cpu_CPU0", OP_PROCESSOR_EN).Processor;
    object->infoARM1.netDerate = opObjectByName(mi,  "ARM1Deration", OP_NET_EN).Net;
    object->infoARM1.pARM      = opObjectByName(mi,  "cpu_CPU1", OP_PROCESSOR_EN).Processor;

    opNetWriteMonitorAdd   ( object->infoARM0.netDerate, derateARMCB, (void *) &object->infoARM0);
    opNetWriteMonitorAdd   ( object->infoARM1.netDerate, derateARMCB, (void *) &object->infoARM1);
}

static OP_PRE_SIMULATE_FN(modulePreSimulate) {
    // insert pre simulation code here
}

static OP_SIMULATE_STARTING_FN(moduleSimulateStart) {
    // insert simulation starting code here
}

static OP_POST_SIMULATE_FN(modulePostSimulate) {
    // insert post simulation code here
}

static OP_DESTRUCT_FN(moduleDestruct) {
    // insert destructor code here
}

static OP_DIAG_SET_FN(moduleDiagSet) {
    // change the diagnostics level here
    object->infoARM0.diagnosticlevel = level;
    object->infoARM1.diagnosticlevel = level;
}

#include "module.igen.h"
