/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORT1' to the base of port 'bport1'
#ifndef BPORT1
#error BPORT1 is undefined. It needs to be set to the port base address
#endif
// Set the macro 'PHYPORT' to the base of port 'phyport'
#ifndef PHYPORT
#error PHYPORT is undefined. It needs to be set to the port base address
#endif


#define BPORT1_AB_POFFSET               0x0
#define BPORT1_AB_NET_CTRL_POFFSET      0x0
#define BPORT1_AB_NET_CTRL              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_NET_CTRL_POFFSET)
#define BPORT1_AB_NET_CTRL_FLUSH_NEXT_RX_DPRAM_  (0x1 << 18)
#define BPORT1_AB_NET_CTRL_FLUSH_NEXT_RX_DPRAM__GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_NET_CTRL_TX_PFC_PRI_PRI_PAUSE_F  (0x1 << 17)
#define BPORT1_AB_NET_CTRL_TX_PFC_PRI_PRI_PAUSE_F_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_NET_CTRL_EN_PFC_PRI_PAUSE_RX  (0x1 << 16)
#define BPORT1_AB_NET_CTRL_EN_PFC_PRI_PAUSE_RX_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_NET_CTRL_STR_RX_TIMESTAMP  (0x1 << 15)
#define BPORT1_AB_NET_CTRL_STR_RX_TIMESTAMP_GET(_v)  ((_v >> 15) & 0x1)
#define BPORT1_AB_NET_CTRL_TX_ZEROQ_PAUSE_FRAME  (0x1 << 12)
#define BPORT1_AB_NET_CTRL_TX_ZEROQ_PAUSE_FRAME_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_NET_CTRL_TX_PAUSE_FRAME  (0x1 << 11)
#define BPORT1_AB_NET_CTRL_TX_PAUSE_FRAME_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_NET_CTRL_TX_HALT      (0x1 << 10)
#define BPORT1_AB_NET_CTRL_TX_HALT_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_NET_CTRL_START_TX     (0x1 << 9)
#define BPORT1_AB_NET_CTRL_START_TX_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_NET_CTRL_BACK_PRESSURE  (0x1 << 8)
#define BPORT1_AB_NET_CTRL_BACK_PRESSURE_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_NET_CTRL_WREN_STAT_REGS  (0x1 << 7)
#define BPORT1_AB_NET_CTRL_WREN_STAT_REGS_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_NET_CTRL_INCR_STAT_REGS  (0x1 << 6)
#define BPORT1_AB_NET_CTRL_INCR_STAT_REGS_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_NET_CTRL_CLEAR_STAT_REGS  (0x1 << 5)
#define BPORT1_AB_NET_CTRL_CLEAR_STAT_REGS_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_NET_CTRL_MGMT_PORT_EN  (0x1 << 4)
#define BPORT1_AB_NET_CTRL_MGMT_PORT_EN_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_NET_CTRL_TX_EN        (0x1 << 3)
#define BPORT1_AB_NET_CTRL_TX_EN_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_NET_CTRL_RX_EN        (0x1 << 2)
#define BPORT1_AB_NET_CTRL_RX_EN_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_NET_CTRL_LOOPBACK_LOCAL  (0x1 << 1)
#define BPORT1_AB_NET_CTRL_LOOPBACK_LOCAL_GET(_v)  ((_v >> 1) & 0x1)

#define BPORT1_AB_NET_CFG_POFFSET       0x4
#define BPORT1_AB_NET_CFG               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_NET_CFG_POFFSET)
#define BPORT1_AB_NET_CFG_UNIDIR_EN     (0x1 << 31)
#define BPORT1_AB_NET_CFG_UNIDIR_EN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_NET_CFG_IGNORE_IPG_RX_ER  (0x1 << 30)
#define BPORT1_AB_NET_CFG_IGNORE_IPG_RX_ER_GET(_v)  ((_v >> 30) & 0x1)
#define BPORT1_AB_NET_CFG_RX_BAD_PREAMBLE  (0x1 << 29)
#define BPORT1_AB_NET_CFG_RX_BAD_PREAMBLE_GET(_v)  ((_v >> 29) & 0x1)
#define BPORT1_AB_NET_CFG_IPG_STRETCH_EN  (0x1 << 28)
#define BPORT1_AB_NET_CFG_IPG_STRETCH_EN_GET(_v)  ((_v >> 28) & 0x1)
#define BPORT1_AB_NET_CFG_SGMII_EN      (0x1 << 27)
#define BPORT1_AB_NET_CFG_SGMII_EN_GET(_v)  ((_v >> 27) & 0x1)
#define BPORT1_AB_NET_CFG_IGNORE_RX_FCS  (0x1 << 26)
#define BPORT1_AB_NET_CFG_IGNORE_RX_FCS_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_NET_CFG_RX_HD_WHILE_TX  (0x1 << 25)
#define BPORT1_AB_NET_CFG_RX_HD_WHILE_TX_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_NET_CFG_RX_CHKSUM_OFFLD_EN  (0x1 << 24)
#define BPORT1_AB_NET_CFG_RX_CHKSUM_OFFLD_EN_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_NET_CFG_DIS_CP_PAUSE_FRAME  (0x1 << 23)
#define BPORT1_AB_NET_CFG_DIS_CP_PAUSE_FRAME_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_NET_CFG_DBUS_WIDTH    (0x3 << 21)
#define BPORT1_AB_NET_CFG_DBUS_WIDTH_GET(_v)  ((_v >> 21) & 0x3)
#define BPORT1_AB_NET_CFG_MDC_CLK_DIV   (0x7 << 18)
#define BPORT1_AB_NET_CFG_MDC_CLK_DIV_GET(_v)  ((_v >> 18) & 0x7)
#define BPORT1_AB_NET_CFG_FCS_REMOVE    (0x1 << 17)
#define BPORT1_AB_NET_CFG_FCS_REMOVE_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_NET_CFG_LEN_ERR_FRAME_DISC  (0x1 << 16)
#define BPORT1_AB_NET_CFG_LEN_ERR_FRAME_DISC_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_NET_CFG_RX_BUF_OFFSET  (0x3 << 14)
#define BPORT1_AB_NET_CFG_RX_BUF_OFFSET_GET(_v)  ((_v >> 14) & 0x3)
#define BPORT1_AB_NET_CFG_PAUSE_EN      (0x1 << 13)
#define BPORT1_AB_NET_CFG_PAUSE_EN_GET(_v)  ((_v >> 13) & 0x1)
#define BPORT1_AB_NET_CFG_RETRY_TEST    (0x1 << 12)
#define BPORT1_AB_NET_CFG_RETRY_TEST_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_NET_CFG_PCS_SEL       (0x1 << 11)
#define BPORT1_AB_NET_CFG_PCS_SEL_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_NET_CFG_GIGE_EN       (0x1 << 10)
#define BPORT1_AB_NET_CFG_GIGE_EN_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_NET_CFG_EXT_ADDR_MATCH_EN  (0x1 << 9)
#define BPORT1_AB_NET_CFG_EXT_ADDR_MATCH_EN_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_NET_CFG_RX_1536_BYTE_FRAMES  (0x1 << 8)
#define BPORT1_AB_NET_CFG_RX_1536_BYTE_FRAMES_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_NET_CFG_UNI_HASH_EN   (0x1 << 7)
#define BPORT1_AB_NET_CFG_UNI_HASH_EN_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_NET_CFG_MULTI_HASH_EN  (0x1 << 6)
#define BPORT1_AB_NET_CFG_MULTI_HASH_EN_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_NET_CFG_NO_BROADCAST  (0x1 << 5)
#define BPORT1_AB_NET_CFG_NO_BROADCAST_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_NET_CFG_COPY_ALL      (0x1 << 4)
#define BPORT1_AB_NET_CFG_COPY_ALL_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_NET_CFG_DISC_NON_VLAN  (0x1 << 2)
#define BPORT1_AB_NET_CFG_DISC_NON_VLAN_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_NET_CFG_FULL_DUPLEX   (0x1 << 1)
#define BPORT1_AB_NET_CFG_FULL_DUPLEX_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_NET_CFG_SPEED         0x1
#define BPORT1_AB_NET_CFG_SPEED_GET(_v)  (_v & 0x1)

#define BPORT1_AB_NET_STATUS_POFFSET    0x8
#define BPORT1_AB_NET_STATUS            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_NET_STATUS_POFFSET)
#define BPORT1_AB_NET_STATUS_PFC_PRI_PAUSE_NEG  (0x1 << 6)
#define BPORT1_AB_NET_STATUS_PFC_PRI_PAUSE_NEG_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_NET_STATUS_PCS_AUTONEG_PAUSE_TX  (0x1 << 5)
#define BPORT1_AB_NET_STATUS_PCS_AUTONEG_PAUSE_TX_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_NET_STATUS_PCS_AUTONEG_PAUSE_RX  (0x1 << 4)
#define BPORT1_AB_NET_STATUS_PCS_AUTONEG_PAUSE_RX_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_NET_STATUS_PCS_AUTONEG_DUP_RES  (0x1 << 3)
#define BPORT1_AB_NET_STATUS_PCS_AUTONEG_DUP_RES_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_NET_STATUS_PHY_MGMT_IDLE  (0x1 << 2)
#define BPORT1_AB_NET_STATUS_PHY_MGMT_IDLE_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_NET_STATUS_MDIO_IN_PIN_STATUS  (0x1 << 1)
#define BPORT1_AB_NET_STATUS_MDIO_IN_PIN_STATUS_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_NET_STATUS_PCS_LINK_STATE  0x1
#define BPORT1_AB_NET_STATUS_PCS_LINK_STATE_GET(_v)  (_v & 0x1)

#define BPORT1_AB_USER_IO_POFFSET       0xc
#define BPORT1_AB_USER_IO               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_USER_IO_POFFSET)

#define BPORT1_AB_DMA_CFG_POFFSET       0x10
#define BPORT1_AB_DMA_CFG               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DMA_CFG_POFFSET)
#define BPORT1_AB_DMA_CFG_DISC_WHEN_NO_AHB  (0x1 << 24)
#define BPORT1_AB_DMA_CFG_DISC_WHEN_NO_AHB_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_DMA_CFG_AHB_MEM_RX_BUF_SIZE  (0xff << 16)
#define BPORT1_AB_DMA_CFG_AHB_MEM_RX_BUF_SIZE_GET(_v)  ((_v >> 16) & 0xff)
#define BPORT1_AB_DMA_CFG_CSUM_GEN_OFFLOAD_EN  (0x1 << 11)
#define BPORT1_AB_DMA_CFG_CSUM_GEN_OFFLOAD_EN_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_DMA_CFG_TX_PKTBUF_MEMSZ_SEL  (0x1 << 10)
#define BPORT1_AB_DMA_CFG_TX_PKTBUF_MEMSZ_SEL_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_DMA_CFG_RX_PKTBUF_MEMSZ_SEL  (0x3 << 8)
#define BPORT1_AB_DMA_CFG_RX_PKTBUF_MEMSZ_SEL_GET(_v)  ((_v >> 8) & 0x3)
#define BPORT1_AB_DMA_CFG_AHB_ENDIAN_SWP_PKT_  (0x1 << 7)
#define BPORT1_AB_DMA_CFG_AHB_ENDIAN_SWP_PKT__GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_DMA_CFG_AHB_ENDIAN_SWP_MGM  (0x1 << 6)
#define BPORT1_AB_DMA_CFG_AHB_ENDIAN_SWP_MGM_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_DMA_CFG_AHB_FIXED_BURST_LEN  0x1f
#define BPORT1_AB_DMA_CFG_AHB_FIXED_BURST_LEN_GET(_v)  (_v & 0x1f)

#define BPORT1_AB_TX_STATUS_POFFSET     0x14
#define BPORT1_AB_TX_STATUS             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TX_STATUS_POFFSET)
#define BPORT1_AB_TX_STATUS_HRESP_NOT_OK  (0x1 << 8)
#define BPORT1_AB_TX_STATUS_HRESP_NOT_OK_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_TX_STATUS_LATE_COLLISION  (0x1 << 7)
#define BPORT1_AB_TX_STATUS_LATE_COLLISION_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_TX_STATUS_TX_UNDER_RUN  (0x1 << 6)
#define BPORT1_AB_TX_STATUS_TX_UNDER_RUN_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_TX_STATUS_TX_COMPLETE  (0x1 << 5)
#define BPORT1_AB_TX_STATUS_TX_COMPLETE_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_TX_STATUS_TX_CORR_AHB_ERR  (0x1 << 4)
#define BPORT1_AB_TX_STATUS_TX_CORR_AHB_ERR_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_TX_STATUS_TX_GO       (0x1 << 3)
#define BPORT1_AB_TX_STATUS_TX_GO_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_TX_STATUS_RETRY_LIMIT_EXCEEDED  (0x1 << 2)
#define BPORT1_AB_TX_STATUS_RETRY_LIMIT_EXCEEDED_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_TX_STATUS_COLLISION   (0x1 << 1)
#define BPORT1_AB_TX_STATUS_COLLISION_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_TX_STATUS_USED_BIT_READ  0x1
#define BPORT1_AB_TX_STATUS_USED_BIT_READ_GET(_v)  (_v & 0x1)

#define BPORT1_AB_RX_QBAR_POFFSET       0x18
#define BPORT1_AB_RX_QBAR               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_QBAR_POFFSET)
#define BPORT1_AB_RX_QBAR_RX_Q_BASEADDR  (0x3fffffff << 2)
#define BPORT1_AB_RX_QBAR_RX_Q_BASEADDR_GET(_v)  ((_v >> 2) & 0x3fffffff)

#define BPORT1_AB_TX_QBAR_POFFSET       0x1c
#define BPORT1_AB_TX_QBAR               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TX_QBAR_POFFSET)
#define BPORT1_AB_TX_QBAR_TX_Q_BASE_ADDR  (0x3fffffff << 2)
#define BPORT1_AB_TX_QBAR_TX_Q_BASE_ADDR_GET(_v)  ((_v >> 2) & 0x3fffffff)

#define BPORT1_AB_RX_STATUS_POFFSET     0x20
#define BPORT1_AB_RX_STATUS             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_STATUS_POFFSET)
#define BPORT1_AB_RX_STATUS_HRESP_NOT_OK  (0x1 << 3)
#define BPORT1_AB_RX_STATUS_HRESP_NOT_OK_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_RX_STATUS_RX_OVERRUN  (0x1 << 2)
#define BPORT1_AB_RX_STATUS_RX_OVERRUN_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_RX_STATUS_FRAME_RECD  (0x1 << 1)
#define BPORT1_AB_RX_STATUS_FRAME_RECD_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_RX_STATUS_BUFFER_NOT_AVAIL  0x1
#define BPORT1_AB_RX_STATUS_BUFFER_NOT_AVAIL_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTR_STATUS_POFFSET   0x24
#define BPORT1_AB_INTR_STATUS           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTR_STATUS_POFFSET)
#define BPORT1_AB_INTR_STATUS_TSU_SEC_INCR  (0x1 << 26)
#define BPORT1_AB_INTR_STATUS_TSU_SEC_INCR_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_INTR_STATUS_PDELAY_RESP_TX  (0x1 << 25)
#define BPORT1_AB_INTR_STATUS_PDELAY_RESP_TX_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_INTR_STATUS_PDELAY_REQ_TX  (0x1 << 24)
#define BPORT1_AB_INTR_STATUS_PDELAY_REQ_TX_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_INTR_STATUS_PDELAY_RESP_RX  (0x1 << 23)
#define BPORT1_AB_INTR_STATUS_PDELAY_RESP_RX_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_INTR_STATUS_PDELAY_REQ_RX  (0x1 << 22)
#define BPORT1_AB_INTR_STATUS_PDELAY_REQ_RX_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_INTR_STATUS_SYNC_TX   (0x1 << 21)
#define BPORT1_AB_INTR_STATUS_SYNC_TX_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_INTR_STATUS_DELAY_REQ_TX  (0x1 << 20)
#define BPORT1_AB_INTR_STATUS_DELAY_REQ_TX_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_INTR_STATUS_SYNC_RX   (0x1 << 19)
#define BPORT1_AB_INTR_STATUS_SYNC_RX_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_INTR_STATUS_DELAY_REQ_RX  (0x1 << 18)
#define BPORT1_AB_INTR_STATUS_DELAY_REQ_RX_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_INTR_STATUS_PARTNER_PG_RX  (0x1 << 17)
#define BPORT1_AB_INTR_STATUS_PARTNER_PG_RX_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_INTR_STATUS_AUTONEG_COMPLETE  (0x1 << 16)
#define BPORT1_AB_INTR_STATUS_AUTONEG_COMPLETE_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_INTR_STATUS_EXT_INTR  (0x1 << 15)
#define BPORT1_AB_INTR_STATUS_EXT_INTR_GET(_v)  ((_v >> 15) & 0x1)
#define BPORT1_AB_INTR_STATUS_PAUSE_TX  (0x1 << 14)
#define BPORT1_AB_INTR_STATUS_PAUSE_TX_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_INTR_STATUS_PAUSE_ZERO  (0x1 << 13)
#define BPORT1_AB_INTR_STATUS_PAUSE_ZERO_GET(_v)  ((_v >> 13) & 0x1)
#define BPORT1_AB_INTR_STATUS_PAUSE_NONZEROQ_RX  (0x1 << 12)
#define BPORT1_AB_INTR_STATUS_PAUSE_NONZEROQ_RX_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_INTR_STATUS_HRESP_NOT_OK  (0x1 << 11)
#define BPORT1_AB_INTR_STATUS_HRESP_NOT_OK_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_INTR_STATUS_RX_OVERRUN  (0x1 << 10)
#define BPORT1_AB_INTR_STATUS_RX_OVERRUN_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_INTR_STATUS_LINK_CHNG  (0x1 << 9)
#define BPORT1_AB_INTR_STATUS_LINK_CHNG_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_INTR_STATUS_TX_COMPLETE  (0x1 << 7)
#define BPORT1_AB_INTR_STATUS_TX_COMPLETE_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_INTR_STATUS_TX_CORRUPT_AHB_ERR  (0x1 << 6)
#define BPORT1_AB_INTR_STATUS_TX_CORRUPT_AHB_ERR_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_INTR_STATUS_RETRY_EX_LATE_COLLISN  (0x1 << 5)
#define BPORT1_AB_INTR_STATUS_RETRY_EX_LATE_COLLISN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_INTR_STATUS_TX_USED_READ  (0x1 << 3)
#define BPORT1_AB_INTR_STATUS_TX_USED_READ_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_INTR_STATUS_RX_USED_READ  (0x1 << 2)
#define BPORT1_AB_INTR_STATUS_RX_USED_READ_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_INTR_STATUS_RX_COMPLETE  (0x1 << 1)
#define BPORT1_AB_INTR_STATUS_RX_COMPLETE_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_INTR_STATUS_MGMT_SENT  0x1
#define BPORT1_AB_INTR_STATUS_MGMT_SENT_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTR_EN_POFFSET       0x28
#define BPORT1_AB_INTR_EN               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTR_EN_POFFSET)
#define BPORT1_AB_INTR_EN_TSU_SEC_INCR  (0x1 << 26)
#define BPORT1_AB_INTR_EN_TSU_SEC_INCR_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_INTR_EN_PDELAY_RESP_TX  (0x1 << 25)
#define BPORT1_AB_INTR_EN_PDELAY_RESP_TX_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_INTR_EN_PDELAY_REQ_TX  (0x1 << 24)
#define BPORT1_AB_INTR_EN_PDELAY_REQ_TX_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_INTR_EN_PDELAY_RESP_RX  (0x1 << 23)
#define BPORT1_AB_INTR_EN_PDELAY_RESP_RX_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_INTR_EN_PDELAY_REQ_RX  (0x1 << 22)
#define BPORT1_AB_INTR_EN_PDELAY_REQ_RX_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_INTR_EN_SYNC_TX       (0x1 << 21)
#define BPORT1_AB_INTR_EN_SYNC_TX_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_INTR_EN_DELAY_REQ_TX  (0x1 << 20)
#define BPORT1_AB_INTR_EN_DELAY_REQ_TX_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_INTR_EN_SYNC_RX       (0x1 << 19)
#define BPORT1_AB_INTR_EN_SYNC_RX_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_INTR_EN_DELAY_REQ_RX  (0x1 << 18)
#define BPORT1_AB_INTR_EN_DELAY_REQ_RX_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_INTR_EN_PARTNER_PG_RX  (0x1 << 17)
#define BPORT1_AB_INTR_EN_PARTNER_PG_RX_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_INTR_EN_AUTONEG_COMPLETE  (0x1 << 16)
#define BPORT1_AB_INTR_EN_AUTONEG_COMPLETE_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_INTR_EN_EXT_INTR      (0x1 << 15)
#define BPORT1_AB_INTR_EN_EXT_INTR_GET(_v)  ((_v >> 15) & 0x1)
#define BPORT1_AB_INTR_EN_PAUSE_TX      (0x1 << 14)
#define BPORT1_AB_INTR_EN_PAUSE_TX_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_INTR_EN_PAUSE_ZERO    (0x1 << 13)
#define BPORT1_AB_INTR_EN_PAUSE_ZERO_GET(_v)  ((_v >> 13) & 0x1)
#define BPORT1_AB_INTR_EN_PAUSE_NONZEROQ  (0x1 << 12)
#define BPORT1_AB_INTR_EN_PAUSE_NONZEROQ_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_INTR_EN_HRESP_NOT_OK  (0x1 << 11)
#define BPORT1_AB_INTR_EN_HRESP_NOT_OK_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_INTR_EN_RX_OVERRUN    (0x1 << 10)
#define BPORT1_AB_INTR_EN_RX_OVERRUN_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_INTR_EN_LINK_CHNG     (0x1 << 9)
#define BPORT1_AB_INTR_EN_LINK_CHNG_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_INTR_EN_TX_COMPLETE   (0x1 << 7)
#define BPORT1_AB_INTR_EN_TX_COMPLETE_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_INTR_EN_TX_CORRUPT_AHB_ERR  (0x1 << 6)
#define BPORT1_AB_INTR_EN_TX_CORRUPT_AHB_ERR_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_INTR_EN_RETRY_EX_LATE_COLLISN  (0x1 << 5)
#define BPORT1_AB_INTR_EN_RETRY_EX_LATE_COLLISN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_INTR_EN_TX_UNDERRUN   (0x1 << 4)
#define BPORT1_AB_INTR_EN_TX_UNDERRUN_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_INTR_EN_TX_USED_READ  (0x1 << 3)
#define BPORT1_AB_INTR_EN_TX_USED_READ_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_INTR_EN_RX_USED_READ  (0x1 << 2)
#define BPORT1_AB_INTR_EN_RX_USED_READ_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_INTR_EN_RX_COMPLETE   (0x1 << 1)
#define BPORT1_AB_INTR_EN_RX_COMPLETE_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_INTR_EN_MGMT_DONE     0x1
#define BPORT1_AB_INTR_EN_MGMT_DONE_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTR_DIS_POFFSET      0x2c
#define BPORT1_AB_INTR_DIS              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTR_DIS_POFFSET)
#define BPORT1_AB_INTR_DIS_TSU_SEC_INCR  (0x1 << 26)
#define BPORT1_AB_INTR_DIS_TSU_SEC_INCR_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_INTR_DIS_PDELAY_RESP_TX  (0x1 << 25)
#define BPORT1_AB_INTR_DIS_PDELAY_RESP_TX_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_INTR_DIS_PDELAY_REQ_TX  (0x1 << 24)
#define BPORT1_AB_INTR_DIS_PDELAY_REQ_TX_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_INTR_DIS_PDELAY_RESP_RX  (0x1 << 23)
#define BPORT1_AB_INTR_DIS_PDELAY_RESP_RX_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_INTR_DIS_PDELAY_REQ_RX  (0x1 << 22)
#define BPORT1_AB_INTR_DIS_PDELAY_REQ_RX_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_INTR_DIS_SYNC_TX      (0x1 << 21)
#define BPORT1_AB_INTR_DIS_SYNC_TX_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_INTR_DIS_DELAY_REQ_TX  (0x1 << 20)
#define BPORT1_AB_INTR_DIS_DELAY_REQ_TX_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_INTR_DIS_SYNC_RX      (0x1 << 19)
#define BPORT1_AB_INTR_DIS_SYNC_RX_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_INTR_DIS_DELAY_REQ_RX  (0x1 << 18)
#define BPORT1_AB_INTR_DIS_DELAY_REQ_RX_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_INTR_DIS_PARTNER_PG_RX  (0x1 << 17)
#define BPORT1_AB_INTR_DIS_PARTNER_PG_RX_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_INTR_DIS_AUTONEG_COMPLETE  (0x1 << 16)
#define BPORT1_AB_INTR_DIS_AUTONEG_COMPLETE_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_INTR_DIS_EXT_INTR     (0x1 << 15)
#define BPORT1_AB_INTR_DIS_EXT_INTR_GET(_v)  ((_v >> 15) & 0x1)
#define BPORT1_AB_INTR_DIS_PAUSE_TX     (0x1 << 14)
#define BPORT1_AB_INTR_DIS_PAUSE_TX_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_INTR_DIS_PAUSE_ZERO   (0x1 << 13)
#define BPORT1_AB_INTR_DIS_PAUSE_ZERO_GET(_v)  ((_v >> 13) & 0x1)
#define BPORT1_AB_INTR_DIS_PAUSE_NONZEROQ  (0x1 << 12)
#define BPORT1_AB_INTR_DIS_PAUSE_NONZEROQ_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_INTR_DIS_HRESP_NOT_OK  (0x1 << 11)
#define BPORT1_AB_INTR_DIS_HRESP_NOT_OK_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_INTR_DIS_RX_OVERRUN   (0x1 << 10)
#define BPORT1_AB_INTR_DIS_RX_OVERRUN_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_INTR_DIS_LINK_CHNG    (0x1 << 9)
#define BPORT1_AB_INTR_DIS_LINK_CHNG_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_INTR_DIS_TX_COMPLETE  (0x1 << 7)
#define BPORT1_AB_INTR_DIS_TX_COMPLETE_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_INTR_DIS_TX_CORRUPT_AHB_ERR  (0x1 << 6)
#define BPORT1_AB_INTR_DIS_TX_CORRUPT_AHB_ERR_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_INTR_DIS_RETRY_EX_LATE_COLLISN  (0x1 << 5)
#define BPORT1_AB_INTR_DIS_RETRY_EX_LATE_COLLISN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_INTR_DIS_TX_UNDERRUN  (0x1 << 4)
#define BPORT1_AB_INTR_DIS_TX_UNDERRUN_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_INTR_DIS_TX_USED_READ  (0x1 << 3)
#define BPORT1_AB_INTR_DIS_TX_USED_READ_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_INTR_DIS_RX_USED_READ  (0x1 << 2)
#define BPORT1_AB_INTR_DIS_RX_USED_READ_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_INTR_DIS_RX_COMPLETE  (0x1 << 1)
#define BPORT1_AB_INTR_DIS_RX_COMPLETE_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_INTR_DIS_MGMT_DONE    0x1
#define BPORT1_AB_INTR_DIS_MGMT_DONE_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTR_MASK_POFFSET     0x30
#define BPORT1_AB_INTR_MASK             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTR_MASK_POFFSET)
#define BPORT1_AB_INTR_MASK_PDELAY_RESP_TX  (0x1 << 25)
#define BPORT1_AB_INTR_MASK_PDELAY_RESP_TX_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_INTR_MASK_PDELAY_REQ_TX  (0x1 << 24)
#define BPORT1_AB_INTR_MASK_PDELAY_REQ_TX_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_INTR_MASK_PDELAY_RESP_RX  (0x1 << 23)
#define BPORT1_AB_INTR_MASK_PDELAY_RESP_RX_GET(_v)  ((_v >> 23) & 0x1)
#define BPORT1_AB_INTR_MASK_PDELAY_REQ_RX  (0x1 << 22)
#define BPORT1_AB_INTR_MASK_PDELAY_REQ_RX_GET(_v)  ((_v >> 22) & 0x1)
#define BPORT1_AB_INTR_MASK_SYNC_TX     (0x1 << 21)
#define BPORT1_AB_INTR_MASK_SYNC_TX_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_INTR_MASK_DELAY_REQ_TX  (0x1 << 20)
#define BPORT1_AB_INTR_MASK_DELAY_REQ_TX_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_INTR_MASK_SYNC_RX     (0x1 << 19)
#define BPORT1_AB_INTR_MASK_SYNC_RX_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_INTR_MASK_DELAY_REQ_RX  (0x1 << 18)
#define BPORT1_AB_INTR_MASK_DELAY_REQ_RX_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_INTR_MASK_PARTNER_PG_RX  (0x1 << 17)
#define BPORT1_AB_INTR_MASK_PARTNER_PG_RX_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_INTR_MASK_AUTONEG_COMPLETE  (0x1 << 16)
#define BPORT1_AB_INTR_MASK_AUTONEG_COMPLETE_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_INTR_MASK_EXT_INTR    (0x1 << 15)
#define BPORT1_AB_INTR_MASK_EXT_INTR_GET(_v)  ((_v >> 15) & 0x1)
#define BPORT1_AB_INTR_MASK_PAUSE_TX    (0x1 << 14)
#define BPORT1_AB_INTR_MASK_PAUSE_TX_GET(_v)  ((_v >> 14) & 0x1)
#define BPORT1_AB_INTR_MASK_PAUSE_ZERO  (0x1 << 13)
#define BPORT1_AB_INTR_MASK_PAUSE_ZERO_GET(_v)  ((_v >> 13) & 0x1)
#define BPORT1_AB_INTR_MASK_PAUSE_NONZEROQ  (0x1 << 12)
#define BPORT1_AB_INTR_MASK_PAUSE_NONZEROQ_GET(_v)  ((_v >> 12) & 0x1)
#define BPORT1_AB_INTR_MASK_HRESP_NOT_OK  (0x1 << 11)
#define BPORT1_AB_INTR_MASK_HRESP_NOT_OK_GET(_v)  ((_v >> 11) & 0x1)
#define BPORT1_AB_INTR_MASK_RX_OVERRUN  (0x1 << 10)
#define BPORT1_AB_INTR_MASK_RX_OVERRUN_GET(_v)  ((_v >> 10) & 0x1)
#define BPORT1_AB_INTR_MASK_LINK_CHNG   (0x1 << 9)
#define BPORT1_AB_INTR_MASK_LINK_CHNG_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_INTR_MASK_TX_COMPLETE  (0x1 << 7)
#define BPORT1_AB_INTR_MASK_TX_COMPLETE_GET(_v)  ((_v >> 7) & 0x1)
#define BPORT1_AB_INTR_MASK_TX_CORRUPT_AHB_ERR  (0x1 << 6)
#define BPORT1_AB_INTR_MASK_TX_CORRUPT_AHB_ERR_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_INTR_MASK_RETRY_EX_LATE_COLLISN  (0x1 << 5)
#define BPORT1_AB_INTR_MASK_RETRY_EX_LATE_COLLISN_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_INTR_MASK_TX_UNDERRUN  (0x1 << 4)
#define BPORT1_AB_INTR_MASK_TX_UNDERRUN_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_INTR_MASK_TX_USED_READ  (0x1 << 3)
#define BPORT1_AB_INTR_MASK_TX_USED_READ_GET(_v)  ((_v >> 3) & 0x1)
#define BPORT1_AB_INTR_MASK_RX_USED_READ  (0x1 << 2)
#define BPORT1_AB_INTR_MASK_RX_USED_READ_GET(_v)  ((_v >> 2) & 0x1)
#define BPORT1_AB_INTR_MASK_RX_COMPLETE  (0x1 << 1)
#define BPORT1_AB_INTR_MASK_RX_COMPLETE_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_INTR_MASK_MGMT_DONE   0x1
#define BPORT1_AB_INTR_MASK_MGMT_DONE_GET(_v)  (_v & 0x1)

#define BPORT1_AB_PHY_MAINT_POFFSET     0x34
#define BPORT1_AB_PHY_MAINT             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PHY_MAINT_POFFSET)
#define BPORT1_AB_PHY_MAINT_CLAUSE_22   (0x1 << 30)
#define BPORT1_AB_PHY_MAINT_CLAUSE_22_GET(_v)  ((_v >> 30) & 0x1)
#define BPORT1_AB_PHY_MAINT_OPERATION   (0x3 << 28)
#define BPORT1_AB_PHY_MAINT_OPERATION_GET(_v)  ((_v >> 28) & 0x3)
#define BPORT1_AB_PHY_MAINT_PHY_ADDR    (0x1f << 23)
#define BPORT1_AB_PHY_MAINT_PHY_ADDR_GET(_v)  ((_v >> 23) & 0x1f)
#define BPORT1_AB_PHY_MAINT_REG_ADDR    (0x1f << 18)
#define BPORT1_AB_PHY_MAINT_REG_ADDR_GET(_v)  ((_v >> 18) & 0x1f)
#define BPORT1_AB_PHY_MAINT_MUST_10     (0x3 << 16)
#define BPORT1_AB_PHY_MAINT_MUST_10_GET(_v)  ((_v >> 16) & 0x3)
#define BPORT1_AB_PHY_MAINT_DATA        0xffff
#define BPORT1_AB_PHY_MAINT_DATA_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_RX_PAUSEQ_POFFSET     0x38
#define BPORT1_AB_RX_PAUSEQ             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_PAUSEQ_POFFSET)
#define BPORT1_AB_RX_PAUSEQ_RX_PAUSEQ   0xffff
#define BPORT1_AB_RX_PAUSEQ_RX_PAUSEQ_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_TX_PAUSEQ_POFFSET     0x3c
#define BPORT1_AB_TX_PAUSEQ             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TX_PAUSEQ_POFFSET)
#define BPORT1_AB_TX_PAUSEQ_TX_PAUSEQ   0xffff
#define BPORT1_AB_TX_PAUSEQ_TX_PAUSEQ_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_GEM_JML_POFFSET       0x48
#define BPORT1_AB_GEM_JML               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_GEM_JML_POFFSET)

#define BPORT1_AB_HASH_BOT_POFFSET      0x80
#define BPORT1_AB_HASH_BOT              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_HASH_BOT_POFFSET)

#define BPORT1_AB_HASH_TOP_POFFSET      0x84
#define BPORT1_AB_HASH_TOP              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_HASH_TOP_POFFSET)

#define BPORT1_AB_SPEC_ADDR1_BOT_POFFSET  0x88
#define BPORT1_AB_SPEC_ADDR1_BOT        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR1_BOT_POFFSET)

#define BPORT1_AB_SPEC_ADDR1_TOP_POFFSET  0x8c
#define BPORT1_AB_SPEC_ADDR1_TOP        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR1_TOP_POFFSET)
#define BPORT1_AB_SPEC_ADDR1_TOP_ADDR_MSBS  0xffff
#define BPORT1_AB_SPEC_ADDR1_TOP_ADDR_MSBS_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_SPEC_ADDR2_BOT_POFFSET  0x90
#define BPORT1_AB_SPEC_ADDR2_BOT        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR2_BOT_POFFSET)

#define BPORT1_AB_SPEC_ADDR2_TOP_POFFSET  0x94
#define BPORT1_AB_SPEC_ADDR2_TOP        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR2_TOP_POFFSET)
#define BPORT1_AB_SPEC_ADDR2_TOP_ADDR_MSBS  0xffff
#define BPORT1_AB_SPEC_ADDR2_TOP_ADDR_MSBS_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_SPEC_ADDR3_BOT_POFFSET  0x98
#define BPORT1_AB_SPEC_ADDR3_BOT        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR3_BOT_POFFSET)

#define BPORT1_AB_SPEC_ADDR3_TOP_POFFSET  0x9c
#define BPORT1_AB_SPEC_ADDR3_TOP        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR3_TOP_POFFSET)
#define BPORT1_AB_SPEC_ADDR3_TOP_ADDR_MSBS  0xffff
#define BPORT1_AB_SPEC_ADDR3_TOP_ADDR_MSBS_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_SPEC_ADDR4_BOT_POFFSET  0xa0
#define BPORT1_AB_SPEC_ADDR4_BOT        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR4_BOT_POFFSET)

#define BPORT1_AB_SPEC_ADDR4_TOP_POFFSET  0xa4
#define BPORT1_AB_SPEC_ADDR4_TOP        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR4_TOP_POFFSET)
#define BPORT1_AB_SPEC_ADDR4_TOP_ADDR_MSBS  0xffff
#define BPORT1_AB_SPEC_ADDR4_TOP_ADDR_MSBS_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_TYPE_ID_MATCH1_POFFSET  0xa8
#define BPORT1_AB_TYPE_ID_MATCH1        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TYPE_ID_MATCH1_POFFSET)
#define BPORT1_AB_TYPE_ID_MATCH1_COPY_EN  (0x1 << 31)
#define BPORT1_AB_TYPE_ID_MATCH1_COPY_EN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_TYPE_ID_MATCH1_TYPE_ID_MATCH1  0xffff
#define BPORT1_AB_TYPE_ID_MATCH1_TYPE_ID_MATCH1_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_TYPE_ID_MATCH2_POFFSET  0xac
#define BPORT1_AB_TYPE_ID_MATCH2        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TYPE_ID_MATCH2_POFFSET)
#define BPORT1_AB_TYPE_ID_MATCH2_COPY_EN  (0x1 << 31)
#define BPORT1_AB_TYPE_ID_MATCH2_COPY_EN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_TYPE_ID_MATCH2_TYPE_ID_MATCH2  0xffff
#define BPORT1_AB_TYPE_ID_MATCH2_TYPE_ID_MATCH2_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_TYPE_ID_MATCH3_POFFSET  0xb0
#define BPORT1_AB_TYPE_ID_MATCH3        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TYPE_ID_MATCH3_POFFSET)
#define BPORT1_AB_TYPE_ID_MATCH3_COPY_EN  (0x1 << 31)
#define BPORT1_AB_TYPE_ID_MATCH3_COPY_EN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_TYPE_ID_MATCH3_TYPE_ID_MATCH3  0xffff
#define BPORT1_AB_TYPE_ID_MATCH3_TYPE_ID_MATCH3_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_TYPE_ID_MATCH4_POFFSET  0xb4
#define BPORT1_AB_TYPE_ID_MATCH4        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TYPE_ID_MATCH4_POFFSET)
#define BPORT1_AB_TYPE_ID_MATCH4_COPY_EN  (0x1 << 31)
#define BPORT1_AB_TYPE_ID_MATCH4_COPY_EN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_TYPE_ID_MATCH4_TYPE_ID_MATCH4  0xffff
#define BPORT1_AB_TYPE_ID_MATCH4_TYPE_ID_MATCH4_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_WAKE_ON_LAN_POFFSET   0xb8
#define BPORT1_AB_WAKE_ON_LAN           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_WAKE_ON_LAN_POFFSET)
#define BPORT1_AB_WAKE_ON_LAN_MULTI_HASH_EN  (0x1 << 19)
#define BPORT1_AB_WAKE_ON_LAN_MULTI_HASH_EN_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_WAKE_ON_LAN_SPEC_ADDR_REG1_EN  (0x1 << 18)
#define BPORT1_AB_WAKE_ON_LAN_SPEC_ADDR_REG1_EN_GET(_v)  ((_v >> 18) & 0x1)
#define BPORT1_AB_WAKE_ON_LAN_ARP_REQ_EN  (0x1 << 17)
#define BPORT1_AB_WAKE_ON_LAN_ARP_REQ_EN_GET(_v)  ((_v >> 17) & 0x1)
#define BPORT1_AB_WAKE_ON_LAN_MAGIC_PKT_EN  (0x1 << 16)
#define BPORT1_AB_WAKE_ON_LAN_MAGIC_PKT_EN_GET(_v)  ((_v >> 16) & 0x1)
#define BPORT1_AB_WAKE_ON_LAN_ARP_REQ_IP_ADDR  0xffff
#define BPORT1_AB_WAKE_ON_LAN_ARP_REQ_IP_ADDR_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_IPG_STRETCH_POFFSET   0xbc
#define BPORT1_AB_IPG_STRETCH           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_IPG_STRETCH_POFFSET)
#define BPORT1_AB_IPG_STRETCH_IPG_STRETCH  0xffff
#define BPORT1_AB_IPG_STRETCH_IPG_STRETCH_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_STACKED_VLAN_POFFSET  0xc0
#define BPORT1_AB_STACKED_VLAN          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_STACKED_VLAN_POFFSET)
#define BPORT1_AB_STACKED_VLAN_STACKED_VLAN_EN  (0x1 << 31)
#define BPORT1_AB_STACKED_VLAN_STACKED_VLAN_EN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_STACKED_VLAN_USER_DEF_VLAN_TYPE  0xffff
#define BPORT1_AB_STACKED_VLAN_USER_DEF_VLAN_TYPE_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_TX_PFC_PAUSE_POFFSET  0xc4
#define BPORT1_AB_TX_PFC_PAUSE          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TX_PFC_PAUSE_POFFSET)
#define BPORT1_AB_TX_PFC_PAUSE_PAUSEQ_SEL  (0xff << 8)
#define BPORT1_AB_TX_PFC_PAUSE_PAUSEQ_SEL_GET(_v)  ((_v >> 8) & 0xff)
#define BPORT1_AB_TX_PFC_PAUSE_PRI_EN_VEC_VAL  0xff
#define BPORT1_AB_TX_PFC_PAUSE_PRI_EN_VEC_VAL_GET(_v)  (_v & 0xff)

#define BPORT1_AB_SPEC_ADDR1_MASK_BOT_POFFSET  0xc8
#define BPORT1_AB_SPEC_ADDR1_MASK_BOT   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR1_MASK_BOT_POFFSET)
#define BPORT1_AB_SPEC_ADDR1_MASK_BOT_MASK_BITS_TOP  0xffffffff
#define BPORT1_AB_SPEC_ADDR1_MASK_BOT_MASK_BITS_TOP_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_SPEC_ADDR1_MASK_TOP_POFFSET  0xcc
#define BPORT1_AB_SPEC_ADDR1_MASK_TOP   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPEC_ADDR1_MASK_TOP_POFFSET)
#define BPORT1_AB_SPEC_ADDR1_MASK_TOP_MASK_BITS_TOP  0xffff
#define BPORT1_AB_SPEC_ADDR1_MASK_TOP_MASK_BITS_TOP_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_RX_PTP_UNI_POFFSET    0xd4
#define BPORT1_AB_RX_PTP_UNI            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_PTP_UNI_POFFSET)

#define BPORT1_AB_TX_PTP_UNI_POFFSET    0xd8
#define BPORT1_AB_TX_PTP_UNI            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TX_PTP_UNI_POFFSET)

#define BPORT1_AB_MODULE_ID_POFFSET     0xfc
#define BPORT1_AB_MODULE_ID             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MODULE_ID_POFFSET)
#define BPORT1_AB_MODULE_ID_MODULE_ID   (0xffff << 16)
#define BPORT1_AB_MODULE_ID_MODULE_ID_GET(_v)  ((_v >> 16) & 0xffff)
#define BPORT1_AB_MODULE_ID_MODULE_REV  0xffff
#define BPORT1_AB_MODULE_ID_MODULE_REV_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_OCTETS_TX_BOT_POFFSET  0x100
#define BPORT1_AB_OCTETS_TX_BOT         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_OCTETS_TX_BOT_POFFSET)
#define BPORT1_AB_OCTETS_TX_BOT_OCTETS_TX_BOT  0xffffffff
#define BPORT1_AB_OCTETS_TX_BOT_OCTETS_TX_BOT_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_OCTETS_TX_TOP_POFFSET  0x104
#define BPORT1_AB_OCTETS_TX_TOP         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_OCTETS_TX_TOP_POFFSET)
#define BPORT1_AB_OCTETS_TX_TOP_OCTETS_TX_TOP  0xffff
#define BPORT1_AB_OCTETS_TX_TOP_OCTETS_TX_TOP_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_FRAMES_TX_POFFSET     0x108
#define BPORT1_AB_FRAMES_TX             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_TX_POFFSET)
#define BPORT1_AB_FRAMES_TX_FRAMES_TX   0xffffffff
#define BPORT1_AB_FRAMES_TX_FRAMES_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_BROADCAST_FRAMES_TX_POFFSET  0x10c
#define BPORT1_AB_BROADCAST_FRAMES_TX   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BROADCAST_FRAMES_TX_POFFSET)
#define BPORT1_AB_BROADCAST_FRAMES_TX_BROADCASR_FRAMES_TX  0xffffffff
#define BPORT1_AB_BROADCAST_FRAMES_TX_BROADCASR_FRAMES_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_MULTI_FRAMES_TX_POFFSET  0x110
#define BPORT1_AB_MULTI_FRAMES_TX       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MULTI_FRAMES_TX_POFFSET)
#define BPORT1_AB_MULTI_FRAMES_TX_MULTI_FRAMES_TX  0xffffffff
#define BPORT1_AB_MULTI_FRAMES_TX_MULTI_FRAMES_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_PAUSE_FRAMES_TX_POFFSET  0x114
#define BPORT1_AB_PAUSE_FRAMES_TX       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PAUSE_FRAMES_TX_POFFSET)
#define BPORT1_AB_PAUSE_FRAMES_TX_PAUSE_FRAMES_TX  0xffff
#define BPORT1_AB_PAUSE_FRAMES_TX_PAUSE_FRAMES_TX_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_FRAMES_64B_TX_POFFSET  0x118
#define BPORT1_AB_FRAMES_64B_TX         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_64B_TX_POFFSET)
#define BPORT1_AB_FRAMES_64B_TX_FRAMES_64B_TX  0xffffffff
#define BPORT1_AB_FRAMES_64B_TX_FRAMES_64B_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_65TO127B_TX_POFFSET  0x11c
#define BPORT1_AB_FRAMES_65TO127B_TX    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_65TO127B_TX_POFFSET)
#define BPORT1_AB_FRAMES_65TO127B_TX_FRAMES_65TO127B_TX  0xffffffff
#define BPORT1_AB_FRAMES_65TO127B_TX_FRAMES_65TO127B_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_128TO255B_TX_POFFSET  0x120
#define BPORT1_AB_FRAMES_128TO255B_TX   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_128TO255B_TX_POFFSET)
#define BPORT1_AB_FRAMES_128TO255B_TX_FRAMES_128TO255B_TX  0xffffffff
#define BPORT1_AB_FRAMES_128TO255B_TX_FRAMES_128TO255B_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_256TO511B_TX_POFFSET  0x124
#define BPORT1_AB_FRAMES_256TO511B_TX   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_256TO511B_TX_POFFSET)
#define BPORT1_AB_FRAMES_256TO511B_TX_FRAMES_256TO511B_TX  0xffffffff
#define BPORT1_AB_FRAMES_256TO511B_TX_FRAMES_256TO511B_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_512TO1023B_TX_POFFSET  0x128
#define BPORT1_AB_FRAMES_512TO1023B_TX  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_512TO1023B_TX_POFFSET)
#define BPORT1_AB_FRAMES_512TO1023B_TX_FRAMES_512TO1023B_TX  0xffffffff
#define BPORT1_AB_FRAMES_512TO1023B_TX_FRAMES_512TO1023B_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_1024TO1518B_TX_POFFSET  0x12c
#define BPORT1_AB_FRAMES_1024TO1518B_TX  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_1024TO1518B_TX_POFFSET)
#define BPORT1_AB_FRAMES_1024TO1518B_TX_FRAMES_1023TO11518B_TX  0xffffffff
#define BPORT1_AB_FRAMES_1024TO1518B_TX_FRAMES_1023TO11518B_TX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_1519BPLUS_TX_POFFSET  0x130
#define BPORT1_AB_FRAMES_1519BPLUS_TX   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_1519BPLUS_TX_POFFSET)

#define BPORT1_AB_TX_UNDER_RUNS_POFFSET  0x134
#define BPORT1_AB_TX_UNDER_RUNS         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TX_UNDER_RUNS_POFFSET)
#define BPORT1_AB_TX_UNDER_RUNS_TX_UNDER_RUNS  0x3ff
#define BPORT1_AB_TX_UNDER_RUNS_TX_UNDER_RUNS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_SINGLE_COLLISN_FRAMES_POFFSET  0x138
#define BPORT1_AB_SINGLE_COLLISN_FRAMES  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SINGLE_COLLISN_FRAMES_POFFSET)
#define BPORT1_AB_SINGLE_COLLISN_FRAMES_SINGLE_COLLISN  0x3ffff
#define BPORT1_AB_SINGLE_COLLISN_FRAMES_SINGLE_COLLISN_GET(_v)  (_v & 0x3ffff)

#define BPORT1_AB_MULTI_COLLISN_FRAMES_POFFSET  0x13c
#define BPORT1_AB_MULTI_COLLISN_FRAMES  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MULTI_COLLISN_FRAMES_POFFSET)
#define BPORT1_AB_MULTI_COLLISN_FRAMES_MULTI_COLLISN  0x3ffff
#define BPORT1_AB_MULTI_COLLISN_FRAMES_MULTI_COLLISN_GET(_v)  (_v & 0x3ffff)

#define BPORT1_AB_EXCESSIVE_COLLISNS_POFFSET  0x140
#define BPORT1_AB_EXCESSIVE_COLLISNS    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_EXCESSIVE_COLLISNS_POFFSET)
#define BPORT1_AB_EXCESSIVE_COLLISNS_EXCESSIVE_COLLISNS  0x3ff
#define BPORT1_AB_EXCESSIVE_COLLISNS_EXCESSIVE_COLLISNS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_LATE_COLLISNS_POFFSET  0x144
#define BPORT1_AB_LATE_COLLISNS         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_LATE_COLLISNS_POFFSET)
#define BPORT1_AB_LATE_COLLISNS_LATE_COLLISNS  0x3ff
#define BPORT1_AB_LATE_COLLISNS_LATE_COLLISNS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_DEFERRED_TX_FRAMES_POFFSET  0x148
#define BPORT1_AB_DEFERRED_TX_FRAMES    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DEFERRED_TX_FRAMES_POFFSET)
#define BPORT1_AB_DEFERRED_TX_FRAMES_DEFERRED_TX_FRAMES  0x3ff
#define BPORT1_AB_DEFERRED_TX_FRAMES_DEFERRED_TX_FRAMES_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_CARRIER_SENSE_ERRS_POFFSET  0x14c
#define BPORT1_AB_CARRIER_SENSE_ERRS    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_CARRIER_SENSE_ERRS_POFFSET)
#define BPORT1_AB_CARRIER_SENSE_ERRS_CARRIER_SENSE_ERRS  0x3ff
#define BPORT1_AB_CARRIER_SENSE_ERRS_CARRIER_SENSE_ERRS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_OCTETS_RX_BOT_POFFSET  0x150
#define BPORT1_AB_OCTETS_RX_BOT         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_OCTETS_RX_BOT_POFFSET)
#define BPORT1_AB_OCTETS_RX_BOT_OCTETS_RX_BOT  0xffffffff
#define BPORT1_AB_OCTETS_RX_BOT_OCTETS_RX_BOT_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_OCTETS_RX_TOP_POFFSET  0x154
#define BPORT1_AB_OCTETS_RX_TOP         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_OCTETS_RX_TOP_POFFSET)
#define BPORT1_AB_OCTETS_RX_TOP_OCTETS_RX_TOP  0xffff
#define BPORT1_AB_OCTETS_RX_TOP_OCTETS_RX_TOP_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_FRAMES_RX_POFFSET     0x158
#define BPORT1_AB_FRAMES_RX             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_RX_POFFSET)
#define BPORT1_AB_FRAMES_RX_FRAMES_RX   0xffffffff
#define BPORT1_AB_FRAMES_RX_FRAMES_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_BDCAST_FRAMES_RX_POFFSET  0x15c
#define BPORT1_AB_BDCAST_FRAMES_RX      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BDCAST_FRAMES_RX_POFFSET)
#define BPORT1_AB_BDCAST_FRAMES_RX_BDCAST_FRAMES_RX  0xffffffff
#define BPORT1_AB_BDCAST_FRAMES_RX_BDCAST_FRAMES_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_MULTI_FRAMES_RX_POFFSET  0x160
#define BPORT1_AB_MULTI_FRAMES_RX       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MULTI_FRAMES_RX_POFFSET)
#define BPORT1_AB_MULTI_FRAMES_RX_MULTI_FRAMES_RX  0xffffffff
#define BPORT1_AB_MULTI_FRAMES_RX_MULTI_FRAMES_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_PAUSE_RX_POFFSET      0x164
#define BPORT1_AB_PAUSE_RX              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PAUSE_RX_POFFSET)
#define BPORT1_AB_PAUSE_RX_PAUSE_RX     0xffff
#define BPORT1_AB_PAUSE_RX_PAUSE_RX_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_FRAMES_64B_RX_POFFSET  0x168
#define BPORT1_AB_FRAMES_64B_RX         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_64B_RX_POFFSET)
#define BPORT1_AB_FRAMES_64B_RX_FRAMES_64B_RX  0xffffffff
#define BPORT1_AB_FRAMES_64B_RX_FRAMES_64B_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_65TO127B_RX_POFFSET  0x16c
#define BPORT1_AB_FRAMES_65TO127B_RX    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_65TO127B_RX_POFFSET)
#define BPORT1_AB_FRAMES_65TO127B_RX_FRAMES_65TO127B_RX  0xffffffff
#define BPORT1_AB_FRAMES_65TO127B_RX_FRAMES_65TO127B_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_128TO255B_RX_POFFSET  0x170
#define BPORT1_AB_FRAMES_128TO255B_RX   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_128TO255B_RX_POFFSET)
#define BPORT1_AB_FRAMES_128TO255B_RX_FRAMES_128TO255B_RX  0xffffffff
#define BPORT1_AB_FRAMES_128TO255B_RX_FRAMES_128TO255B_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_256TO511B_RX_POFFSET  0x174
#define BPORT1_AB_FRAMES_256TO511B_RX   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_256TO511B_RX_POFFSET)
#define BPORT1_AB_FRAMES_256TO511B_RX_FRAMES_256TO511B_RX  0xffffffff
#define BPORT1_AB_FRAMES_256TO511B_RX_FRAMES_256TO511B_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_512TO1023B_RX_POFFSET  0x178
#define BPORT1_AB_FRAMES_512TO1023B_RX  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_512TO1023B_RX_POFFSET)
#define BPORT1_AB_FRAMES_512TO1023B_RX_FRAMES_512TO1023B_RX  0xffffffff
#define BPORT1_AB_FRAMES_512TO1023B_RX_FRAMES_512TO1023B_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_1024TO1518B_RX_POFFSET  0x17c
#define BPORT1_AB_FRAMES_1024TO1518B_RX  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_1024TO1518B_RX_POFFSET)
#define BPORT1_AB_FRAMES_1024TO1518B_RX_FRAMES_1023TO11518B_RX  0xffffffff
#define BPORT1_AB_FRAMES_1024TO1518B_RX_FRAMES_1023TO11518B_RX_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_FRAMES_1519BPLUS_RX_POFFSET  0x180
#define BPORT1_AB_FRAMES_1519BPLUS_RX   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FRAMES_1519BPLUS_RX_POFFSET)

#define BPORT1_AB_UNDERSZ_RX_POFFSET    0x184
#define BPORT1_AB_UNDERSZ_RX            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_UNDERSZ_RX_POFFSET)
#define BPORT1_AB_UNDERSZ_RX_UNDERSZ_RX  0x3ff
#define BPORT1_AB_UNDERSZ_RX_UNDERSZ_RX_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_OVERSZ_RX_POFFSET     0x188
#define BPORT1_AB_OVERSZ_RX             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_OVERSZ_RX_POFFSET)
#define BPORT1_AB_OVERSZ_RX_OVERSZ_RX   0x3ff
#define BPORT1_AB_OVERSZ_RX_OVERSZ_RX_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_JAB_RX_POFFSET        0x18c
#define BPORT1_AB_JAB_RX                (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_JAB_RX_POFFSET)
#define BPORT1_AB_JAB_RX_JAB_RX         0x3ff
#define BPORT1_AB_JAB_RX_JAB_RX_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_FCS_ERRORS_POFFSET    0x190
#define BPORT1_AB_FCS_ERRORS            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FCS_ERRORS_POFFSET)
#define BPORT1_AB_FCS_ERRORS_FCS_ERROS  0x3ff
#define BPORT1_AB_FCS_ERRORS_FCS_ERROS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_LENGTH_FIELD_ERRORS_POFFSET  0x194
#define BPORT1_AB_LENGTH_FIELD_ERRORS   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_LENGTH_FIELD_ERRORS_POFFSET)
#define BPORT1_AB_LENGTH_FIELD_ERRORS_LENGTH_FIELD_ERRORS  0x3ff
#define BPORT1_AB_LENGTH_FIELD_ERRORS_LENGTH_FIELD_ERRORS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_RX_SYMBOL_ERRORS_POFFSET  0x198
#define BPORT1_AB_RX_SYMBOL_ERRORS      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_SYMBOL_ERRORS_POFFSET)
#define BPORT1_AB_RX_SYMBOL_ERRORS_RX_SYMBOL_ERRORS  0x3ff
#define BPORT1_AB_RX_SYMBOL_ERRORS_RX_SYMBOL_ERRORS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_ALIGN_ERRORS_POFFSET  0x19c
#define BPORT1_AB_ALIGN_ERRORS          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_ALIGN_ERRORS_POFFSET)
#define BPORT1_AB_ALIGN_ERRORS_ALIGN_ERRORS  0x3ff
#define BPORT1_AB_ALIGN_ERRORS_ALIGN_ERRORS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_RX_RESOURCE_ERRORS_POFFSET  0x1a0
#define BPORT1_AB_RX_RESOURCE_ERRORS    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_RESOURCE_ERRORS_POFFSET)
#define BPORT1_AB_RX_RESOURCE_ERRORS_RX_RESOURCE_ERRORS  0x3ffff
#define BPORT1_AB_RX_RESOURCE_ERRORS_RX_RESOURCE_ERRORS_GET(_v)  (_v & 0x3ffff)

#define BPORT1_AB_RX_OVERRUN_ERRORS_POFFSET  0x1a4
#define BPORT1_AB_RX_OVERRUN_ERRORS     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_OVERRUN_ERRORS_POFFSET)
#define BPORT1_AB_RX_OVERRUN_ERRORS_RX_OVERRUN_ERRORS  0x3ff
#define BPORT1_AB_RX_OVERRUN_ERRORS_RX_OVERRUN_ERRORS_GET(_v)  (_v & 0x3ff)

#define BPORT1_AB_IP_HDR_CSUM_ERRORS_POFFSET  0x1a8
#define BPORT1_AB_IP_HDR_CSUM_ERRORS    (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_IP_HDR_CSUM_ERRORS_POFFSET)
#define BPORT1_AB_IP_HDR_CSUM_ERRORS_IP_HDR_CSUM_ERRORS  0xff
#define BPORT1_AB_IP_HDR_CSUM_ERRORS_IP_HDR_CSUM_ERRORS_GET(_v)  (_v & 0xff)

#define BPORT1_AB_TCP_CSUM_ERRORS_POFFSET  0x1ac
#define BPORT1_AB_TCP_CSUM_ERRORS       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TCP_CSUM_ERRORS_POFFSET)
#define BPORT1_AB_TCP_CSUM_ERRORS_TCP_CSUM_ERRORS  0xff
#define BPORT1_AB_TCP_CSUM_ERRORS_TCP_CSUM_ERRORS_GET(_v)  (_v & 0xff)

#define BPORT1_AB_UDP_CSUM_ERRORS_POFFSET  0x1b0
#define BPORT1_AB_UDP_CSUM_ERRORS       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_UDP_CSUM_ERRORS_POFFSET)
#define BPORT1_AB_UDP_CSUM_ERRORS_UDP_CSUM_ERRORS  0xff
#define BPORT1_AB_UDP_CSUM_ERRORS_UDP_CSUM_ERRORS_GET(_v)  (_v & 0xff)

#define BPORT1_AB_TIMER_STROBE_S_POFFSET  0x1c8
#define BPORT1_AB_TIMER_STROBE_S        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TIMER_STROBE_S_POFFSET)
#define BPORT1_AB_TIMER_STROBE_S_TIMER_STROBE_S  0xffffffff
#define BPORT1_AB_TIMER_STROBE_S_TIMER_STROBE_S_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_TIMER_STROBE_NS_POFFSET  0x1cc
#define BPORT1_AB_TIMER_STROBE_NS       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TIMER_STROBE_NS_POFFSET)
#define BPORT1_AB_TIMER_STROBE_NS_NS_REG_VAL  0x3fffffff
#define BPORT1_AB_TIMER_STROBE_NS_NS_REG_VAL_GET(_v)  (_v & 0x3fffffff)

#define BPORT1_AB_TIMER_S_POFFSET       0x1d0
#define BPORT1_AB_TIMER_S               (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TIMER_S_POFFSET)
#define BPORT1_AB_TIMER_S_TIMER_S       0xffffffff
#define BPORT1_AB_TIMER_S_TIMER_S_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_TIMER_NS_POFFSET      0x1d4
#define BPORT1_AB_TIMER_NS              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TIMER_NS_POFFSET)
#define BPORT1_AB_TIMER_NS_TIMER_CT_NS  0x3fffffff
#define BPORT1_AB_TIMER_NS_TIMER_CT_NS_GET(_v)  (_v & 0x3fffffff)

#define BPORT1_AB_TIMER_ADJUST_POFFSET  0x1d8
#define BPORT1_AB_TIMER_ADJUST          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TIMER_ADJUST_POFFSET)
#define BPORT1_AB_TIMER_ADJUST_ADD_SUBN  (0x1 << 31)
#define BPORT1_AB_TIMER_ADJUST_ADD_SUBN_GET(_v)  ((_v >> 31) & 0x1)
#define BPORT1_AB_TIMER_ADJUST_NS_DELTA  0x3fffffff
#define BPORT1_AB_TIMER_ADJUST_NS_DELTA_GET(_v)  (_v & 0x3fffffff)

#define BPORT1_AB_TIMER_INCR_POFFSET    0x1dc
#define BPORT1_AB_TIMER_INCR            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TIMER_INCR_POFFSET)
#define BPORT1_AB_TIMER_INCR_INCR_B4_ALT  (0xff << 16)
#define BPORT1_AB_TIMER_INCR_INCR_B4_ALT_GET(_v)  ((_v >> 16) & 0xff)
#define BPORT1_AB_TIMER_INCR_ALT_CT_NS_DELTA  (0xff << 8)
#define BPORT1_AB_TIMER_INCR_ALT_CT_NS_DELTA_GET(_v)  ((_v >> 8) & 0xff)
#define BPORT1_AB_TIMER_INCR_NS_DELTA   0xff
#define BPORT1_AB_TIMER_INCR_NS_DELTA_GET(_v)  (_v & 0xff)

#define BPORT1_AB_PTP_TX_S_POFFSET      0x1e0
#define BPORT1_AB_PTP_TX_S              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_TX_S_POFFSET)
#define BPORT1_AB_PTP_TX_S_PTP_TX_S     0xffffffff
#define BPORT1_AB_PTP_TX_S_PTP_TX_S_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_PTP_TX_NS_POFFSET     0x1e4
#define BPORT1_AB_PTP_TX_NS             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_TX_NS_POFFSET)
#define BPORT1_AB_PTP_TX_NS_NS_REG_VAL  0x3fffffff
#define BPORT1_AB_PTP_TX_NS_NS_REG_VAL_GET(_v)  (_v & 0x3fffffff)

#define BPORT1_AB_PTP_RX_S_POFFSET      0x1e8
#define BPORT1_AB_PTP_RX_S              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_RX_S_POFFSET)
#define BPORT1_AB_PTP_RX_S_PTP_RX_S     0xffffffff
#define BPORT1_AB_PTP_RX_S_PTP_RX_S_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_PTP_RX_NS_POFFSET     0x1ec
#define BPORT1_AB_PTP_RX_NS             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_RX_NS_POFFSET)
#define BPORT1_AB_PTP_RX_NS_NS_REG_VAL  0x3fffffff
#define BPORT1_AB_PTP_RX_NS_NS_REG_VAL_GET(_v)  (_v & 0x3fffffff)

#define BPORT1_AB_PTP_PEER_TX_S_POFFSET  0x1f0
#define BPORT1_AB_PTP_PEER_TX_S         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_PEER_TX_S_POFFSET)
#define BPORT1_AB_PTP_PEER_TX_S_PTP_PEER_TX_S  0xffffffff
#define BPORT1_AB_PTP_PEER_TX_S_PTP_PEER_TX_S_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_PTP_PEER_TX_NS_POFFSET  0x1f4
#define BPORT1_AB_PTP_PEER_TX_NS        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_PEER_TX_NS_POFFSET)
#define BPORT1_AB_PTP_PEER_TX_NS_NS_REG_VAL  0x3fffffff
#define BPORT1_AB_PTP_PEER_TX_NS_NS_REG_VAL_GET(_v)  (_v & 0x3fffffff)

#define BPORT1_AB_PTP_PEER_RX_S_POFFSET  0x1f8
#define BPORT1_AB_PTP_PEER_RX_S         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_PEER_RX_S_POFFSET)
#define BPORT1_AB_PTP_PEER_RX_S_PTP_PEER_RX_S  0xffffffff
#define BPORT1_AB_PTP_PEER_RX_S_PTP_PEER_RX_S_GET(_v)  (_v & 0xffffffff)

#define BPORT1_AB_PTP_PEER_RX_NS_POFFSET  0x1fc
#define BPORT1_AB_PTP_PEER_RX_NS        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PTP_PEER_RX_NS_POFFSET)
#define BPORT1_AB_PTP_PEER_RX_NS_NS_REG_VAL  0x3fffffff
#define BPORT1_AB_PTP_PEER_RX_NS_NS_REG_VAL_GET(_v)  (_v & 0x3fffffff)

#define BPORT1_AB_DESIGN_CFG1_POFFSET   0x280
#define BPORT1_AB_DESIGN_CFG1           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DESIGN_CFG1_POFFSET)

#define BPORT1_AB_DESIGN_CFG2_POFFSET   0x284
#define BPORT1_AB_DESIGN_CFG2           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DESIGN_CFG2_POFFSET)
#define BPORT1_AB_DESIGN_CFG2_GEM_TX_PBUF_ADDR  (0xf << 26)
#define BPORT1_AB_DESIGN_CFG2_GEM_TX_PBUF_ADDR_GET(_v)  ((_v >> 26) & 0xf)
#define BPORT1_AB_DESIGN_CFG2_GEM_RX_PBUF_ADDR  (0xf << 22)
#define BPORT1_AB_DESIGN_CFG2_GEM_RX_PBUF_ADDR_GET(_v)  ((_v >> 22) & 0xf)
#define BPORT1_AB_DESIGN_CFG2_GEM_TX_PKT_BUFFER  (0x1 << 21)
#define BPORT1_AB_DESIGN_CFG2_GEM_TX_PKT_BUFFER_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_DESIGN_CFG2_GEM_RX_PKT_BUFFER  (0x1 << 20)
#define BPORT1_AB_DESIGN_CFG2_GEM_RX_PKT_BUFFER_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_DESIGN_CFG2_GEM_HPROT_VALUE  (0xf << 16)
#define BPORT1_AB_DESIGN_CFG2_GEM_HPROT_VALUE_GET(_v)  ((_v >> 16) & 0xf)
#define BPORT1_AB_DESIGN_CFG2_GEM_JUMBO_MAX_LENGTH  0xffff
#define BPORT1_AB_DESIGN_CFG2_GEM_JUMBO_MAX_LENGTH_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_DESIGN_CFG3_POFFSET   0x288
#define BPORT1_AB_DESIGN_CFG3           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DESIGN_CFG3_POFFSET)
#define BPORT1_AB_DESIGN_CFG3_GEM_RX_BASE2_FIFO_SIZ  (0xffff << 16)
#define BPORT1_AB_DESIGN_CFG3_GEM_RX_BASE2_FIFO_SIZ_GET(_v)  ((_v >> 16) & 0xffff)
#define BPORT1_AB_DESIGN_CFG3_GEM_RX_FIFO_SIZE  0xffff
#define BPORT1_AB_DESIGN_CFG3_GEM_RX_FIFO_SIZE_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_DESIGN_CFG4_POFFSET   0x28c
#define BPORT1_AB_DESIGN_CFG4           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DESIGN_CFG4_POFFSET)
#define BPORT1_AB_DESIGN_CFG4_GEM_TX_BASE2_FIFO_SIZE  (0xffff << 16)
#define BPORT1_AB_DESIGN_CFG4_GEM_TX_BASE2_FIFO_SIZE_GET(_v)  ((_v >> 16) & 0xffff)
#define BPORT1_AB_DESIGN_CFG4_GEM_TX_FIFO_SIZE  0xffff
#define BPORT1_AB_DESIGN_CFG4_GEM_TX_FIFO_SIZE_GET(_v)  (_v & 0xffff)

#define BPORT1_AB_DESIGN_CFG5_POFFSET   0x290
#define BPORT1_AB_DESIGN_CFG5           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DESIGN_CFG5_POFFSET)
#define BPORT1_AB_DESIGN_CFG5_GEM_TSU_CLK  (0x1 << 28)
#define BPORT1_AB_DESIGN_CFG5_GEM_TSU_CLK_GET(_v)  ((_v >> 28) & 0x1)
#define BPORT1_AB_DESIGN_CFG5_GEM_RX_BUFFER_LENGTH_  (0xff << 20)
#define BPORT1_AB_DESIGN_CFG5_GEM_RX_BUFFER_LENGTH__GET(_v)  ((_v >> 20) & 0xff)
#define BPORT1_AB_DESIGN_CFG5_GEM_TX_PBUF_SIZE_DEF  (0x1 << 19)
#define BPORT1_AB_DESIGN_CFG5_GEM_TX_PBUF_SIZE_DEF_GET(_v)  ((_v >> 19) & 0x1)
#define BPORT1_AB_DESIGN_CFG5_GEM_RX_PBUF_SIZE_DEF  (0x3 << 17)
#define BPORT1_AB_DESIGN_CFG5_GEM_RX_PBUF_SIZE_DEF_GET(_v)  ((_v >> 17) & 0x3)
#define BPORT1_AB_DESIGN_CFG5_GEM_ENDIAN_SWAP_DEF  (0x3 << 15)
#define BPORT1_AB_DESIGN_CFG5_GEM_ENDIAN_SWAP_DEF_GET(_v)  ((_v >> 15) & 0x3)
#define BPORT1_AB_DESIGN_CFG5_GEM_MDC_CLOCK_DIV  (0x7 << 12)
#define BPORT1_AB_DESIGN_CFG5_GEM_MDC_CLOCK_DIV_GET(_v)  ((_v >> 12) & 0x7)
#define BPORT1_AB_DESIGN_CFG5_GEM_DMA_BUS_WIDTH  (0x3 << 10)
#define BPORT1_AB_DESIGN_CFG5_GEM_DMA_BUS_WIDTH_GET(_v)  ((_v >> 10) & 0x3)
#define BPORT1_AB_DESIGN_CFG5_GEM_PHY_IDENT  (0x1 << 9)
#define BPORT1_AB_DESIGN_CFG5_GEM_PHY_IDENT_GET(_v)  ((_v >> 9) & 0x1)
#define BPORT1_AB_DESIGN_CFG5_GEM_TSU   (0x1 << 8)
#define BPORT1_AB_DESIGN_CFG5_GEM_TSU_GET(_v)  ((_v >> 8) & 0x1)
#define BPORT1_AB_DESIGN_CFG5_GEM_TX_FIFO_CNT_WIDTH  (0xf << 4)
#define BPORT1_AB_DESIGN_CFG5_GEM_TX_FIFO_CNT_WIDTH_GET(_v)  ((_v >> 4) & 0xf)
#define BPORT1_AB_DESIGN_CFG5_GEM_RX_FIFO_CNT_WIDTH  0xf
#define BPORT1_AB_DESIGN_CFG5_GEM_RX_FIFO_CNT_WIDTH_GET(_v)  (_v & 0xf)

#define BPORT1_AB_DESIGN_CFG6_POFFSET   0x294
#define BPORT1_AB_DESIGN_CFG6           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DESIGN_CFG6_POFFSET)

#define BPORT1_AB_TX_BD_CNTRL_POFFSET   0x4cc
#define BPORT1_AB_TX_BD_CNTRL           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TX_BD_CNTRL_POFFSET)

#define BPORT1_AB_RX_BD_CNTRL_POFFSET   0x4d0
#define BPORT1_AB_RX_BD_CNTRL           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RX_BD_CNTRL_POFFSET)

#define BPORT1_AB_BUFFER_POFFSET        0x0
#define BPORT1_AB_BUFFER                (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER_POFFSET)
#define BPORT1_AB_BUFFER_BYTES          0x1000


#define PHYPORT_AB_POFFSET              0x0
#define PHYPORT_AB_MII_BMCR_POFFSET     0x0
#define PHYPORT_AB_MII_BMCR             (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_BMCR_POFFSET)

#define PHYPORT_AB_MII_BMSR_POFFSET     0x2
#define PHYPORT_AB_MII_BMSR             (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_BMSR_POFFSET)

#define PHYPORT_AB_MII_PHYSID1_POFFSET  0x4
#define PHYPORT_AB_MII_PHYSID1          (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_PHYSID1_POFFSET)

#define PHYPORT_AB_MII_PHYSID2_POFFSET  0x6
#define PHYPORT_AB_MII_PHYSID2          (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_PHYSID2_POFFSET)

#define PHYPORT_AB_MII_ADVERTISE_POFFSET  0x8
#define PHYPORT_AB_MII_ADVERTISE        (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_ADVERTISE_POFFSET)

#define PHYPORT_AB_MII_LPA_POFFSET      0xa
#define PHYPORT_AB_MII_LPA              (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_LPA_POFFSET)

#define PHYPORT_AB_MII_EXPANSION_POFFSET  0xc
#define PHYPORT_AB_MII_EXPANSION        (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_EXPANSION_POFFSET)

#define PHYPORT_AB_MII_DUMMY1_POFFSET   0xe
#define PHYPORT_AB_MII_DUMMY1           (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_DUMMY1_POFFSET)

#define PHYPORT_AB_MII_DUMMY2_POFFSET   0x10
#define PHYPORT_AB_MII_DUMMY2           (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_DUMMY2_POFFSET)

#define PHYPORT_AB_MII_CTRL1000_POFFSET  0x12
#define PHYPORT_AB_MII_CTRL1000         (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_CTRL1000_POFFSET)

#define PHYPORT_AB_MII_STAT1000_POFFSET  0x14
#define PHYPORT_AB_MII_STAT1000         (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_STAT1000_POFFSET)

#define PHYPORT_AB_MII_DUMMY3_POFFSET   0x16
#define PHYPORT_AB_MII_DUMMY3           (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_DUMMY3_POFFSET)

#define PHYPORT_AB_MII_DUMMY4_POFFSET   0x18
#define PHYPORT_AB_MII_DUMMY4           (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_DUMMY4_POFFSET)

#define PHYPORT_AB_MII_MMD_CTRL_POFFSET  0x1a
#define PHYPORT_AB_MII_MMD_CTRL         (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_MMD_CTRL_POFFSET)

#define PHYPORT_AB_MII_MMD_DATA_POFFSET  0x1c
#define PHYPORT_AB_MII_MMD_DATA         (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_MMD_DATA_POFFSET)

#define PHYPORT_AB_MII_ESTATUS_POFFSET  0x1e
#define PHYPORT_AB_MII_ESTATUS          (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_ESTATUS_POFFSET)

#define PHYPORT_AB_MII_DUMMY5_POFFSET   0x20
#define PHYPORT_AB_MII_DUMMY5           (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_DUMMY5_POFFSET)

#define PHYPORT_AB_MII_STS_POFFSET      0x22
#define PHYPORT_AB_MII_STS              (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_STS_POFFSET)

#define PHYPORT_AB_MII_DCOUNTER_POFFSET  0x24
#define PHYPORT_AB_MII_DCOUNTER         (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_DCOUNTER_POFFSET)

#define PHYPORT_AB_MII_FCSCOUNTER_POFFSET  0x26
#define PHYPORT_AB_MII_FCSCOUNTER       (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_FCSCOUNTER_POFFSET)

#define PHYPORT_AB_MII_NWAYTEST_POFFSET  0x28
#define PHYPORT_AB_MII_NWAYTEST         (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_NWAYTEST_POFFSET)

#define PHYPORT_AB_MII_RERRCOUNTER_POFFSET  0x2a
#define PHYPORT_AB_MII_RERRCOUNTER      (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_RERRCOUNTER_POFFSET)

#define PHYPORT_AB_MII_SREVISION_POFFSET  0x2c
#define PHYPORT_AB_MII_SREVISION        (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_SREVISION_POFFSET)

#define PHYPORT_AB_MII_LBRERROR_POFFSET  0x30
#define PHYPORT_AB_MII_LBRERROR         (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_LBRERROR_POFFSET)

#define PHYPORT_AB_MII_PHYADDR_POFFSET  0x32
#define PHYPORT_AB_MII_PHYADDR          (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_PHYADDR_POFFSET)

#define PHYPORT_AB_MII_TPISTATUS_POFFSET  0x36
#define PHYPORT_AB_MII_TPISTATUS        (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_TPISTATUS_POFFSET)

#define PHYPORT_AB_MII_NCONFIG_POFFSET  0x38
#define PHYPORT_AB_MII_NCONFIG          (PHYPORT + PHYPORT_AB_POFFSET + PHYPORT_AB_MII_NCONFIG_POFFSET)


#endif
