IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")

CFLAGS+=-I$(IMPERAS_HOME)/ImperasLib/source/arm.ovpworld.org/peripheral/LcdPL110/1.0/model
IMPERAS_PSE=PSE_RV64
include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.pse
