/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORTS' to the base of port 'bportS'
#ifndef BPORTS
#error BPORTS is undefined. It needs to be set to the port base address
#endif
// Set the macro 'BPORTNS' to the base of port 'bportNS'
#ifndef BPORTNS
#error BPORTNS is undefined. It needs to be set to the port base address
#endif


#define BPORTS_ABS_POFFSET              0x0
#define BPORTS_ABS_DSR_POFFSET          0x0
#define BPORTS_ABS_DSR                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DSR_POFFSET)

#define BPORTS_ABS_DPC_POFFSET          0x4
#define BPORTS_ABS_DPC                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DPC_POFFSET)

#define BPORTS_ABS_INTEN_POFFSET        0x20
#define BPORTS_ABS_INTEN                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_INTEN_POFFSET)

#define BPORTS_ABS_INT_EVENT_RIS_POFFSET  0x24
#define BPORTS_ABS_INT_EVENT_RIS        (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_INT_EVENT_RIS_POFFSET)

#define BPORTS_ABS_INTMIS_POFFSET       0x28
#define BPORTS_ABS_INTMIS               (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_INTMIS_POFFSET)

#define BPORTS_ABS_INTCLR_POFFSET       0x2c
#define BPORTS_ABS_INTCLR               (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_INTCLR_POFFSET)

#define BPORTS_ABS_FSRD_POFFSET         0x30
#define BPORTS_ABS_FSRD                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FSRD_POFFSET)

#define BPORTS_ABS_FSRC_POFFSET         0x34
#define BPORTS_ABS_FSRC                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FSRC_POFFSET)

#define BPORTS_ABS_FTRD_POFFSET         0x38
#define BPORTS_ABS_FTRD                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTRD_POFFSET)

#define BPORTS_ABS_FTR0_POFFSET         0x40
#define BPORTS_ABS_FTR0                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR0_POFFSET)

#define BPORTS_ABS_FTR1_POFFSET         0x44
#define BPORTS_ABS_FTR1                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR1_POFFSET)

#define BPORTS_ABS_FTR2_POFFSET         0x48
#define BPORTS_ABS_FTR2                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR2_POFFSET)

#define BPORTS_ABS_FTR3_POFFSET         0x4c
#define BPORTS_ABS_FTR3                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR3_POFFSET)

#define BPORTS_ABS_FTR4_POFFSET         0x50
#define BPORTS_ABS_FTR4                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR4_POFFSET)

#define BPORTS_ABS_FTR5_POFFSET         0x54
#define BPORTS_ABS_FTR5                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR5_POFFSET)

#define BPORTS_ABS_FTR6_POFFSET         0x58
#define BPORTS_ABS_FTR6                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR6_POFFSET)

#define BPORTS_ABS_FTR7_POFFSET         0x5c
#define BPORTS_ABS_FTR7                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_FTR7_POFFSET)

#define BPORTS_ABS_CSR0_POFFSET         0x100
#define BPORTS_ABS_CSR0                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR0_POFFSET)

#define BPORTS_ABS_CPC0_POFFSET         0x104
#define BPORTS_ABS_CPC0                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC0_POFFSET)

#define BPORTS_ABS_CSR1_POFFSET         0x108
#define BPORTS_ABS_CSR1                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR1_POFFSET)

#define BPORTS_ABS_CPC1_POFFSET         0x10c
#define BPORTS_ABS_CPC1                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC1_POFFSET)

#define BPORTS_ABS_CSR2_POFFSET         0x110
#define BPORTS_ABS_CSR2                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR2_POFFSET)

#define BPORTS_ABS_CPC2_POFFSET         0x114
#define BPORTS_ABS_CPC2                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC2_POFFSET)

#define BPORTS_ABS_CSR3_POFFSET         0x118
#define BPORTS_ABS_CSR3                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR3_POFFSET)

#define BPORTS_ABS_CPC3_POFFSET         0x11c
#define BPORTS_ABS_CPC3                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC3_POFFSET)

#define BPORTS_ABS_CSR4_POFFSET         0x120
#define BPORTS_ABS_CSR4                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR4_POFFSET)

#define BPORTS_ABS_CPC4_POFFSET         0x124
#define BPORTS_ABS_CPC4                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC4_POFFSET)

#define BPORTS_ABS_CSR5_POFFSET         0x128
#define BPORTS_ABS_CSR5                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR5_POFFSET)

#define BPORTS_ABS_CPC5_POFFSET         0x12c
#define BPORTS_ABS_CPC5                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC5_POFFSET)

#define BPORTS_ABS_CSR6_POFFSET         0x130
#define BPORTS_ABS_CSR6                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR6_POFFSET)

#define BPORTS_ABS_CPC6_POFFSET         0x134
#define BPORTS_ABS_CPC6                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC6_POFFSET)

#define BPORTS_ABS_CSR7_POFFSET         0x138
#define BPORTS_ABS_CSR7                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CSR7_POFFSET)

#define BPORTS_ABS_CPC7_POFFSET         0x13c
#define BPORTS_ABS_CPC7                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CPC7_POFFSET)

#define BPORTS_ABS_SAR0_POFFSET         0x400
#define BPORTS_ABS_SAR0                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR0_POFFSET)

#define BPORTS_ABS_DAR0_POFFSET         0x404
#define BPORTS_ABS_DAR0                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR0_POFFSET)

#define BPORTS_ABS_CCR0_POFFSET         0x408
#define BPORTS_ABS_CCR0                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR0_POFFSET)

#define BPORTS_ABS_LC0_0_POFFSET        0x40c
#define BPORTS_ABS_LC0_0                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_0_POFFSET)

#define BPORTS_ABS_LC1_0_POFFSET        0x410
#define BPORTS_ABS_LC1_0                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_0_POFFSET)

#define BPORTS_ABS_SAR1_POFFSET         0x420
#define BPORTS_ABS_SAR1                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR1_POFFSET)

#define BPORTS_ABS_DAR1_POFFSET         0x424
#define BPORTS_ABS_DAR1                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR1_POFFSET)

#define BPORTS_ABS_CCR1_POFFSET         0x428
#define BPORTS_ABS_CCR1                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR1_POFFSET)

#define BPORTS_ABS_LC0_1_POFFSET        0x42c
#define BPORTS_ABS_LC0_1                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_1_POFFSET)

#define BPORTS_ABS_LC1_1_POFFSET        0x430
#define BPORTS_ABS_LC1_1                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_1_POFFSET)

#define BPORTS_ABS_SAR2_POFFSET         0x440
#define BPORTS_ABS_SAR2                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR2_POFFSET)

#define BPORTS_ABS_DAR2_POFFSET         0x444
#define BPORTS_ABS_DAR2                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR2_POFFSET)

#define BPORTS_ABS_CCR2_POFFSET         0x448
#define BPORTS_ABS_CCR2                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR2_POFFSET)

#define BPORTS_ABS_LC0_2_POFFSET        0x44c
#define BPORTS_ABS_LC0_2                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_2_POFFSET)

#define BPORTS_ABS_LC1_2_POFFSET        0x450
#define BPORTS_ABS_LC1_2                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_2_POFFSET)

#define BPORTS_ABS_SAR3_POFFSET         0x460
#define BPORTS_ABS_SAR3                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR3_POFFSET)

#define BPORTS_ABS_DAR3_POFFSET         0x464
#define BPORTS_ABS_DAR3                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR3_POFFSET)

#define BPORTS_ABS_CCR3_POFFSET         0x468
#define BPORTS_ABS_CCR3                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR3_POFFSET)

#define BPORTS_ABS_LC0_3_POFFSET        0x46c
#define BPORTS_ABS_LC0_3                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_3_POFFSET)

#define BPORTS_ABS_LC1_3_POFFSET        0x470
#define BPORTS_ABS_LC1_3                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_3_POFFSET)

#define BPORTS_ABS_SAR4_POFFSET         0x480
#define BPORTS_ABS_SAR4                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR4_POFFSET)

#define BPORTS_ABS_DAR4_POFFSET         0x484
#define BPORTS_ABS_DAR4                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR4_POFFSET)

#define BPORTS_ABS_CCR4_POFFSET         0x488
#define BPORTS_ABS_CCR4                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR4_POFFSET)

#define BPORTS_ABS_LC0_4_POFFSET        0x48c
#define BPORTS_ABS_LC0_4                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_4_POFFSET)

#define BPORTS_ABS_LC1_4_POFFSET        0x490
#define BPORTS_ABS_LC1_4                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_4_POFFSET)

#define BPORTS_ABS_SAR5_POFFSET         0x4a0
#define BPORTS_ABS_SAR5                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR5_POFFSET)

#define BPORTS_ABS_DAR5_POFFSET         0x4a4
#define BPORTS_ABS_DAR5                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR5_POFFSET)

#define BPORTS_ABS_CCR5_POFFSET         0x4a8
#define BPORTS_ABS_CCR5                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR5_POFFSET)

#define BPORTS_ABS_LC0_5_POFFSET        0x4ac
#define BPORTS_ABS_LC0_5                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_5_POFFSET)

#define BPORTS_ABS_LC1_5_POFFSET        0x4b0
#define BPORTS_ABS_LC1_5                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_5_POFFSET)

#define BPORTS_ABS_SAR6_POFFSET         0x4c0
#define BPORTS_ABS_SAR6                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR6_POFFSET)

#define BPORTS_ABS_DAR6_POFFSET         0x4c4
#define BPORTS_ABS_DAR6                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR6_POFFSET)

#define BPORTS_ABS_CCR6_POFFSET         0x4c8
#define BPORTS_ABS_CCR6                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR6_POFFSET)

#define BPORTS_ABS_LC0_6_POFFSET        0x4cc
#define BPORTS_ABS_LC0_6                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_6_POFFSET)

#define BPORTS_ABS_LC1_6_POFFSET        0x4d0
#define BPORTS_ABS_LC1_6                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_6_POFFSET)

#define BPORTS_ABS_SAR7_POFFSET         0x4e0
#define BPORTS_ABS_SAR7                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_SAR7_POFFSET)

#define BPORTS_ABS_DAR7_POFFSET         0x4e4
#define BPORTS_ABS_DAR7                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DAR7_POFFSET)

#define BPORTS_ABS_CCR7_POFFSET         0x4e8
#define BPORTS_ABS_CCR7                 (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CCR7_POFFSET)

#define BPORTS_ABS_LC0_7_POFFSET        0x4ec
#define BPORTS_ABS_LC0_7                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC0_7_POFFSET)

#define BPORTS_ABS_LC1_7_POFFSET        0x4f0
#define BPORTS_ABS_LC1_7                (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_LC1_7_POFFSET)

#define BPORTS_ABS_DBGSTATUS_POFFSET    0xd00
#define BPORTS_ABS_DBGSTATUS            (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DBGSTATUS_POFFSET)

#define BPORTS_ABS_DBGCMD_POFFSET       0xd04
#define BPORTS_ABS_DBGCMD               (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DBGCMD_POFFSET)

#define BPORTS_ABS_DBGINST0_POFFSET     0xd08
#define BPORTS_ABS_DBGINST0             (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DBGINST0_POFFSET)

#define BPORTS_ABS_DBGINST1_POFFSET     0xd0c
#define BPORTS_ABS_DBGINST1             (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_DBGINST1_POFFSET)

#define BPORTS_ABS_CR0_POFFSET          0xe00
#define BPORTS_ABS_CR0                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CR0_POFFSET)

#define BPORTS_ABS_CR1_POFFSET          0xe04
#define BPORTS_ABS_CR1                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CR1_POFFSET)

#define BPORTS_ABS_CR2_POFFSET          0xe08
#define BPORTS_ABS_CR2                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CR2_POFFSET)

#define BPORTS_ABS_CR3_POFFSET          0xe0c
#define BPORTS_ABS_CR3                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CR3_POFFSET)

#define BPORTS_ABS_CR4_POFFSET          0xe10
#define BPORTS_ABS_CR4                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CR4_POFFSET)

#define BPORTS_ABS_CRD_POFFSET          0xe14
#define BPORTS_ABS_CRD                  (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_CRD_POFFSET)

#define BPORTS_ABS_WD_POFFSET           0xe80
#define BPORTS_ABS_WD                   (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_WD_POFFSET)

#define BPORTS_ABS_PERIPH_ID_0_POFFSET  0xfe0
#define BPORTS_ABS_PERIPH_ID_0          (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PERIPH_ID_0_POFFSET)

#define BPORTS_ABS_PERIPH_ID_1_POFFSET  0xfe4
#define BPORTS_ABS_PERIPH_ID_1          (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PERIPH_ID_1_POFFSET)

#define BPORTS_ABS_PERIPH_ID_2_POFFSET  0xfe8
#define BPORTS_ABS_PERIPH_ID_2          (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PERIPH_ID_2_POFFSET)

#define BPORTS_ABS_PERIPH_ID_3_POFFSET  0xfec
#define BPORTS_ABS_PERIPH_ID_3          (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PERIPH_ID_3_POFFSET)

#define BPORTS_ABS_PCELL_ID_0_POFFSET   0xff0
#define BPORTS_ABS_PCELL_ID_0           (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PCELL_ID_0_POFFSET)

#define BPORTS_ABS_PCELL_ID_1_POFFSET   0xff4
#define BPORTS_ABS_PCELL_ID_1           (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PCELL_ID_1_POFFSET)

#define BPORTS_ABS_PCELL_ID_2_POFFSET   0xff8
#define BPORTS_ABS_PCELL_ID_2           (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PCELL_ID_2_POFFSET)

#define BPORTS_ABS_PCELL_ID_3_POFFSET   0xffc
#define BPORTS_ABS_PCELL_ID_3           (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_PCELL_ID_3_POFFSET)

#define BPORTS_ABS_BUFFER_POFFSET       0x0
#define BPORTS_ABS_BUFFER               (BPORTS + BPORTS_ABS_POFFSET + BPORTS_ABS_BUFFER_POFFSET)
#define BPORTS_ABS_BUFFER_BYTES         0x1000


#define BPORTNS_ABNS_POFFSET            0x0
#define BPORTNS_ABNS_DSR_POFFSET        0x0
#define BPORTNS_ABNS_DSR                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DSR_POFFSET)

#define BPORTNS_ABNS_DPC_POFFSET        0x4
#define BPORTNS_ABNS_DPC                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DPC_POFFSET)

#define BPORTNS_ABNS_INTEN_POFFSET      0x20
#define BPORTNS_ABNS_INTEN              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_INTEN_POFFSET)

#define BPORTNS_ABNS_INT_EVENT_RIS_POFFSET  0x24
#define BPORTNS_ABNS_INT_EVENT_RIS      (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_INT_EVENT_RIS_POFFSET)

#define BPORTNS_ABNS_INTMIS_POFFSET     0x28
#define BPORTNS_ABNS_INTMIS             (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_INTMIS_POFFSET)

#define BPORTNS_ABNS_INTCLR_POFFSET     0x2c
#define BPORTNS_ABNS_INTCLR             (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_INTCLR_POFFSET)

#define BPORTNS_ABNS_FSRD_POFFSET       0x30
#define BPORTNS_ABNS_FSRD               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FSRD_POFFSET)

#define BPORTNS_ABNS_FSRC_POFFSET       0x34
#define BPORTNS_ABNS_FSRC               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FSRC_POFFSET)

#define BPORTNS_ABNS_FTRD_POFFSET       0x38
#define BPORTNS_ABNS_FTRD               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTRD_POFFSET)

#define BPORTNS_ABNS_FTR0_POFFSET       0x40
#define BPORTNS_ABNS_FTR0               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR0_POFFSET)

#define BPORTNS_ABNS_FTR1_POFFSET       0x44
#define BPORTNS_ABNS_FTR1               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR1_POFFSET)

#define BPORTNS_ABNS_FTR2_POFFSET       0x48
#define BPORTNS_ABNS_FTR2               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR2_POFFSET)

#define BPORTNS_ABNS_FTR3_POFFSET       0x4c
#define BPORTNS_ABNS_FTR3               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR3_POFFSET)

#define BPORTNS_ABNS_FTR4_POFFSET       0x50
#define BPORTNS_ABNS_FTR4               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR4_POFFSET)

#define BPORTNS_ABNS_FTR5_POFFSET       0x54
#define BPORTNS_ABNS_FTR5               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR5_POFFSET)

#define BPORTNS_ABNS_FTR6_POFFSET       0x58
#define BPORTNS_ABNS_FTR6               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR6_POFFSET)

#define BPORTNS_ABNS_FTR7_POFFSET       0x5c
#define BPORTNS_ABNS_FTR7               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_FTR7_POFFSET)

#define BPORTNS_ABNS_CSR0_POFFSET       0x100
#define BPORTNS_ABNS_CSR0               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR0_POFFSET)

#define BPORTNS_ABNS_CPC0_POFFSET       0x104
#define BPORTNS_ABNS_CPC0               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC0_POFFSET)

#define BPORTNS_ABNS_CSR1_POFFSET       0x108
#define BPORTNS_ABNS_CSR1               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR1_POFFSET)

#define BPORTNS_ABNS_CPC1_POFFSET       0x10c
#define BPORTNS_ABNS_CPC1               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC1_POFFSET)

#define BPORTNS_ABNS_CSR2_POFFSET       0x110
#define BPORTNS_ABNS_CSR2               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR2_POFFSET)

#define BPORTNS_ABNS_CPC2_POFFSET       0x114
#define BPORTNS_ABNS_CPC2               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC2_POFFSET)

#define BPORTNS_ABNS_CSR3_POFFSET       0x118
#define BPORTNS_ABNS_CSR3               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR3_POFFSET)

#define BPORTNS_ABNS_CPC3_POFFSET       0x11c
#define BPORTNS_ABNS_CPC3               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC3_POFFSET)

#define BPORTNS_ABNS_CSR4_POFFSET       0x120
#define BPORTNS_ABNS_CSR4               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR4_POFFSET)

#define BPORTNS_ABNS_CPC4_POFFSET       0x124
#define BPORTNS_ABNS_CPC4               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC4_POFFSET)

#define BPORTNS_ABNS_CSR5_POFFSET       0x128
#define BPORTNS_ABNS_CSR5               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR5_POFFSET)

#define BPORTNS_ABNS_CPC5_POFFSET       0x12c
#define BPORTNS_ABNS_CPC5               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC5_POFFSET)

#define BPORTNS_ABNS_CSR6_POFFSET       0x130
#define BPORTNS_ABNS_CSR6               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR6_POFFSET)

#define BPORTNS_ABNS_CPC6_POFFSET       0x134
#define BPORTNS_ABNS_CPC6               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC6_POFFSET)

#define BPORTNS_ABNS_CSR7_POFFSET       0x138
#define BPORTNS_ABNS_CSR7               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CSR7_POFFSET)

#define BPORTNS_ABNS_CPC7_POFFSET       0x13c
#define BPORTNS_ABNS_CPC7               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CPC7_POFFSET)

#define BPORTNS_ABNS_SAR0_POFFSET       0x400
#define BPORTNS_ABNS_SAR0               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR0_POFFSET)

#define BPORTNS_ABNS_DAR0_POFFSET       0x404
#define BPORTNS_ABNS_DAR0               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR0_POFFSET)

#define BPORTNS_ABNS_CCR0_POFFSET       0x408
#define BPORTNS_ABNS_CCR0               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR0_POFFSET)

#define BPORTNS_ABNS_LC0_0_POFFSET      0x40c
#define BPORTNS_ABNS_LC0_0              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_0_POFFSET)

#define BPORTNS_ABNS_LC1_0_POFFSET      0x410
#define BPORTNS_ABNS_LC1_0              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_0_POFFSET)

#define BPORTNS_ABNS_SAR1_POFFSET       0x420
#define BPORTNS_ABNS_SAR1               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR1_POFFSET)

#define BPORTNS_ABNS_DAR1_POFFSET       0x424
#define BPORTNS_ABNS_DAR1               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR1_POFFSET)

#define BPORTNS_ABNS_CCR1_POFFSET       0x428
#define BPORTNS_ABNS_CCR1               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR1_POFFSET)

#define BPORTNS_ABNS_LC0_1_POFFSET      0x42c
#define BPORTNS_ABNS_LC0_1              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_1_POFFSET)

#define BPORTNS_ABNS_LC1_1_POFFSET      0x430
#define BPORTNS_ABNS_LC1_1              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_1_POFFSET)

#define BPORTNS_ABNS_SAR2_POFFSET       0x440
#define BPORTNS_ABNS_SAR2               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR2_POFFSET)

#define BPORTNS_ABNS_DAR2_POFFSET       0x444
#define BPORTNS_ABNS_DAR2               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR2_POFFSET)

#define BPORTNS_ABNS_CCR2_POFFSET       0x448
#define BPORTNS_ABNS_CCR2               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR2_POFFSET)

#define BPORTNS_ABNS_LC0_2_POFFSET      0x44c
#define BPORTNS_ABNS_LC0_2              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_2_POFFSET)

#define BPORTNS_ABNS_LC1_2_POFFSET      0x450
#define BPORTNS_ABNS_LC1_2              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_2_POFFSET)

#define BPORTNS_ABNS_SAR3_POFFSET       0x460
#define BPORTNS_ABNS_SAR3               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR3_POFFSET)

#define BPORTNS_ABNS_DAR3_POFFSET       0x464
#define BPORTNS_ABNS_DAR3               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR3_POFFSET)

#define BPORTNS_ABNS_CCR3_POFFSET       0x468
#define BPORTNS_ABNS_CCR3               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR3_POFFSET)

#define BPORTNS_ABNS_LC0_3_POFFSET      0x46c
#define BPORTNS_ABNS_LC0_3              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_3_POFFSET)

#define BPORTNS_ABNS_LC1_3_POFFSET      0x470
#define BPORTNS_ABNS_LC1_3              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_3_POFFSET)

#define BPORTNS_ABNS_SAR4_POFFSET       0x480
#define BPORTNS_ABNS_SAR4               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR4_POFFSET)

#define BPORTNS_ABNS_DAR4_POFFSET       0x484
#define BPORTNS_ABNS_DAR4               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR4_POFFSET)

#define BPORTNS_ABNS_CCR4_POFFSET       0x488
#define BPORTNS_ABNS_CCR4               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR4_POFFSET)

#define BPORTNS_ABNS_LC0_4_POFFSET      0x48c
#define BPORTNS_ABNS_LC0_4              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_4_POFFSET)

#define BPORTNS_ABNS_LC1_4_POFFSET      0x490
#define BPORTNS_ABNS_LC1_4              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_4_POFFSET)

#define BPORTNS_ABNS_SAR5_POFFSET       0x4a0
#define BPORTNS_ABNS_SAR5               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR5_POFFSET)

#define BPORTNS_ABNS_DAR5_POFFSET       0x4a4
#define BPORTNS_ABNS_DAR5               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR5_POFFSET)

#define BPORTNS_ABNS_CCR5_POFFSET       0x4a8
#define BPORTNS_ABNS_CCR5               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR5_POFFSET)

#define BPORTNS_ABNS_LC0_5_POFFSET      0x4ac
#define BPORTNS_ABNS_LC0_5              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_5_POFFSET)

#define BPORTNS_ABNS_LC1_5_POFFSET      0x4b0
#define BPORTNS_ABNS_LC1_5              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_5_POFFSET)

#define BPORTNS_ABNS_SAR6_POFFSET       0x4c0
#define BPORTNS_ABNS_SAR6               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR6_POFFSET)

#define BPORTNS_ABNS_DAR6_POFFSET       0x4c4
#define BPORTNS_ABNS_DAR6               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR6_POFFSET)

#define BPORTNS_ABNS_CCR6_POFFSET       0x4c8
#define BPORTNS_ABNS_CCR6               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR6_POFFSET)

#define BPORTNS_ABNS_LC0_6_POFFSET      0x4cc
#define BPORTNS_ABNS_LC0_6              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_6_POFFSET)

#define BPORTNS_ABNS_LC1_6_POFFSET      0x4d0
#define BPORTNS_ABNS_LC1_6              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_6_POFFSET)

#define BPORTNS_ABNS_SAR7_POFFSET       0x4e0
#define BPORTNS_ABNS_SAR7               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_SAR7_POFFSET)

#define BPORTNS_ABNS_DAR7_POFFSET       0x4e4
#define BPORTNS_ABNS_DAR7               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DAR7_POFFSET)

#define BPORTNS_ABNS_CCR7_POFFSET       0x4e8
#define BPORTNS_ABNS_CCR7               (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CCR7_POFFSET)

#define BPORTNS_ABNS_LC0_7_POFFSET      0x4ec
#define BPORTNS_ABNS_LC0_7              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC0_7_POFFSET)

#define BPORTNS_ABNS_LC1_7_POFFSET      0x4f0
#define BPORTNS_ABNS_LC1_7              (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_LC1_7_POFFSET)

#define BPORTNS_ABNS_DBGSTATUS_POFFSET  0xd00
#define BPORTNS_ABNS_DBGSTATUS          (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DBGSTATUS_POFFSET)

#define BPORTNS_ABNS_DBGCMD_POFFSET     0xd04
#define BPORTNS_ABNS_DBGCMD             (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DBGCMD_POFFSET)

#define BPORTNS_ABNS_DBGINST0_POFFSET   0xd08
#define BPORTNS_ABNS_DBGINST0           (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DBGINST0_POFFSET)

#define BPORTNS_ABNS_DBGINST1_POFFSET   0xd0c
#define BPORTNS_ABNS_DBGINST1           (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_DBGINST1_POFFSET)

#define BPORTNS_ABNS_CR0_POFFSET        0xe00
#define BPORTNS_ABNS_CR0                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CR0_POFFSET)

#define BPORTNS_ABNS_CR1_POFFSET        0xe04
#define BPORTNS_ABNS_CR1                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CR1_POFFSET)

#define BPORTNS_ABNS_CR2_POFFSET        0xe08
#define BPORTNS_ABNS_CR2                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CR2_POFFSET)

#define BPORTNS_ABNS_CR3_POFFSET        0xe0c
#define BPORTNS_ABNS_CR3                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CR3_POFFSET)

#define BPORTNS_ABNS_CR4_POFFSET        0xe10
#define BPORTNS_ABNS_CR4                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CR4_POFFSET)

#define BPORTNS_ABNS_CRD_POFFSET        0xe14
#define BPORTNS_ABNS_CRD                (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_CRD_POFFSET)

#define BPORTNS_ABNS_WD_POFFSET         0xe80
#define BPORTNS_ABNS_WD                 (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_WD_POFFSET)

#define BPORTNS_ABNS_PERIPH_ID_0_POFFSET  0xfe0
#define BPORTNS_ABNS_PERIPH_ID_0        (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PERIPH_ID_0_POFFSET)

#define BPORTNS_ABNS_PERIPH_ID_1_POFFSET  0xfe4
#define BPORTNS_ABNS_PERIPH_ID_1        (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PERIPH_ID_1_POFFSET)

#define BPORTNS_ABNS_PERIPH_ID_2_POFFSET  0xfe8
#define BPORTNS_ABNS_PERIPH_ID_2        (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PERIPH_ID_2_POFFSET)

#define BPORTNS_ABNS_PERIPH_ID_3_POFFSET  0xfec
#define BPORTNS_ABNS_PERIPH_ID_3        (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PERIPH_ID_3_POFFSET)

#define BPORTNS_ABNS_PCELL_ID_0_POFFSET  0xff0
#define BPORTNS_ABNS_PCELL_ID_0         (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PCELL_ID_0_POFFSET)

#define BPORTNS_ABNS_PCELL_ID_1_POFFSET  0xff4
#define BPORTNS_ABNS_PCELL_ID_1         (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PCELL_ID_1_POFFSET)

#define BPORTNS_ABNS_PCELL_ID_2_POFFSET  0xff8
#define BPORTNS_ABNS_PCELL_ID_2         (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PCELL_ID_2_POFFSET)

#define BPORTNS_ABNS_PCELL_ID_3_POFFSET  0xffc
#define BPORTNS_ABNS_PCELL_ID_3         (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_PCELL_ID_3_POFFSET)

#define BPORTNS_ABNS_BUFFER_POFFSET     0x0
#define BPORTNS_ABNS_BUFFER             (BPORTNS + BPORTNS_ABNS_POFFSET + BPORTNS_ABNS_BUFFER_POFFSET)
#define BPORTNS_ABNS_BUFFER_BYTES       0x1000


#endif
