/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORT1' to the base of port 'bport1'
#ifndef BPORT1
#error BPORT1 is undefined. It needs to be set to the port base address
#endif


#define BPORT1_AB_POFFSET               0x0
#define BPORT1_AB_MMDC_MDCTL_POFFSET    0x0
#define BPORT1_AB_MMDC_MDCTL            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDCTL_POFFSET)

#define BPORT1_AB_MMDC_MDPDC_POFFSET    0x4
#define BPORT1_AB_MMDC_MDPDC            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDPDC_POFFSET)

#define BPORT1_AB_MMDC_MDOTC_POFFSET    0x8
#define BPORT1_AB_MMDC_MDOTC            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDOTC_POFFSET)

#define BPORT1_AB_MMDC_MDCFG0_POFFSET   0xc
#define BPORT1_AB_MMDC_MDCFG0           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDCFG0_POFFSET)

#define BPORT1_AB_MMDC_MDCFG1_POFFSET   0x10
#define BPORT1_AB_MMDC_MDCFG1           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDCFG1_POFFSET)

#define BPORT1_AB_MMDC_MDCFG2_POFFSET   0x14
#define BPORT1_AB_MMDC_MDCFG2           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDCFG2_POFFSET)

#define BPORT1_AB_MMDC_MDMISC_POFFSET   0x18
#define BPORT1_AB_MMDC_MDMISC           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDMISC_POFFSET)

#define BPORT1_AB_MMDC_MDSCR_POFFSET    0x1c
#define BPORT1_AB_MMDC_MDSCR            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDSCR_POFFSET)

#define BPORT1_AB_MMDC_MDREF_POFFSET    0x20
#define BPORT1_AB_MMDC_MDREF            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDREF_POFFSET)

#define BPORT1_AB_MMDC_MDRWD_POFFSET    0x2c
#define BPORT1_AB_MMDC_MDRWD            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDRWD_POFFSET)

#define BPORT1_AB_MMDC_MDOR_POFFSET     0x30
#define BPORT1_AB_MMDC_MDOR             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDOR_POFFSET)

#define BPORT1_AB_MMDC_MDMRR_POFFSET    0x34
#define BPORT1_AB_MMDC_MDMRR            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDMRR_POFFSET)

#define BPORT1_AB_MMDC_MDCFG3LP_POFFSET  0x38
#define BPORT1_AB_MMDC_MDCFG3LP         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDCFG3LP_POFFSET)

#define BPORT1_AB_MMDC_MDMR4_POFFSET    0x3c
#define BPORT1_AB_MMDC_MDMR4            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDMR4_POFFSET)

#define BPORT1_AB_MMDC_MDASP_POFFSET    0x40
#define BPORT1_AB_MMDC_MDASP            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MDASP_POFFSET)

#define BPORT1_AB_MMDC_MAARCR_POFFSET   0x400
#define BPORT1_AB_MMDC_MAARCR           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MAARCR_POFFSET)

#define BPORT1_AB_MMDC_MAPSR_POFFSET    0x404
#define BPORT1_AB_MMDC_MAPSR            (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MAPSR_POFFSET)
#define BPORT1_AB_MMDC_MAPSR_DVACK      (0x1 << 25)
#define BPORT1_AB_MMDC_MAPSR_DVACK_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_MMDC_MAPSR_LPACK      (0x1 << 24)
#define BPORT1_AB_MMDC_MAPSR_LPACK_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_MMDC_MAPSR_DVFS       (0x1 << 21)
#define BPORT1_AB_MMDC_MAPSR_DVFS_GET(_v)  ((_v >> 21) & 0x1)
#define BPORT1_AB_MMDC_MAPSR_LPMD       (0x1 << 20)
#define BPORT1_AB_MMDC_MAPSR_LPMD_GET(_v)  ((_v >> 20) & 0x1)
#define BPORT1_AB_MMDC_MAPSR_PST        (0xff << 8)
#define BPORT1_AB_MMDC_MAPSR_PST_GET(_v)  ((_v >> 8) & 0xff)
#define BPORT1_AB_MMDC_MAPSR_WIS        (0x1 << 6)
#define BPORT1_AB_MMDC_MAPSR_WIS_GET(_v)  ((_v >> 6) & 0x1)
#define BPORT1_AB_MMDC_MAPSR_RIS        (0x1 << 5)
#define BPORT1_AB_MMDC_MAPSR_RIS_GET(_v)  ((_v >> 5) & 0x1)
#define BPORT1_AB_MMDC_MAPSR_PSS        (0x1 << 4)
#define BPORT1_AB_MMDC_MAPSR_PSS_GET(_v)  ((_v >> 4) & 0x1)
#define BPORT1_AB_MMDC_MAPSR_PSD        0x1
#define BPORT1_AB_MMDC_MAPSR_PSD_GET(_v)  (_v & 0x1)

#define BPORT1_AB_MMDC_MAEXIDR0_POFFSET  0x408
#define BPORT1_AB_MMDC_MAEXIDR0         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MAEXIDR0_POFFSET)

#define BPORT1_AB_MMDC_MAEXIDR1_POFFSET  0x40c
#define BPORT1_AB_MMDC_MAEXIDR1         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MAEXIDR1_POFFSET)

#define BPORT1_AB_MMDC_MADPCR0_POFFSET  0x410
#define BPORT1_AB_MMDC_MADPCR0          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPCR0_POFFSET)

#define BPORT1_AB_MMDC_MADPCR1_POFFSET  0x414
#define BPORT1_AB_MMDC_MADPCR1          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPCR1_POFFSET)

#define BPORT1_AB_MMDC_MADPSR0_POFFSET  0x418
#define BPORT1_AB_MMDC_MADPSR0          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPSR0_POFFSET)

#define BPORT1_AB_MMDC_MADPSR1_POFFSET  0x41c
#define BPORT1_AB_MMDC_MADPSR1          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPSR1_POFFSET)

#define BPORT1_AB_MMDC_MADPSR2_POFFSET  0x420
#define BPORT1_AB_MMDC_MADPSR2          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPSR2_POFFSET)

#define BPORT1_AB_MMDC_MADPSR3_POFFSET  0x424
#define BPORT1_AB_MMDC_MADPSR3          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPSR3_POFFSET)

#define BPORT1_AB_MMDC_MADPSR4_POFFSET  0x428
#define BPORT1_AB_MMDC_MADPSR4          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPSR4_POFFSET)

#define BPORT1_AB_MMDC_MADPSR5_POFFSET  0x42c
#define BPORT1_AB_MMDC_MADPSR5          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MADPSR5_POFFSET)

#define BPORT1_AB_MMDC_MASBS0_POFFSET   0x430
#define BPORT1_AB_MMDC_MASBS0           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MASBS0_POFFSET)

#define BPORT1_AB_MMDC_MASBS1_POFFSET   0x434
#define BPORT1_AB_MMDC_MASBS1           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MASBS1_POFFSET)

#define BPORT1_AB_MMDC_MAGENP_POFFSET   0x440
#define BPORT1_AB_MMDC_MAGENP           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MAGENP_POFFSET)

#define BPORT1_AB_MMDC_MPZQHWCTRL_POFFSET  0x800
#define BPORT1_AB_MMDC_MPZQHWCTRL       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPZQHWCTRL_POFFSET)

#define BPORT1_AB_MMDC_MPZQSWCTRL_POFFSET  0x804
#define BPORT1_AB_MMDC_MPZQSWCTRL       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPZQSWCTRL_POFFSET)

#define BPORT1_AB_MMDC_MPWLGCR_POFFSET  0x808
#define BPORT1_AB_MMDC_MPWLGCR          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWLGCR_POFFSET)

#define BPORT1_AB_MMDC_MPWLDECTRL0_POFFSET  0x80c
#define BPORT1_AB_MMDC_MPWLDECTRL0      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWLDECTRL0_POFFSET)

#define BPORT1_AB_MMDC_MPWLDECTRL1_POFFSET  0x810
#define BPORT1_AB_MMDC_MPWLDECTRL1      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWLDECTRL1_POFFSET)

#define BPORT1_AB_MMDC_MPWLDLST_POFFSET  0x814
#define BPORT1_AB_MMDC_MPWLDLST         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWLDLST_POFFSET)

#define BPORT1_AB_MMDC_MPODTCTRL_POFFSET  0x818
#define BPORT1_AB_MMDC_MPODTCTRL        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPODTCTRL_POFFSET)

#define BPORT1_AB_MMDC_MPRDDQBY0DL_POFFSET  0x81c
#define BPORT1_AB_MMDC_MPRDDQBY0DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDQBY0DL_POFFSET)

#define BPORT1_AB_MMDC_MPRDDQBY1DL_POFFSET  0x820
#define BPORT1_AB_MMDC_MPRDDQBY1DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDQBY1DL_POFFSET)

#define BPORT1_AB_MMDC_MPRDDQBY2DL_POFFSET  0x824
#define BPORT1_AB_MMDC_MPRDDQBY2DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDQBY2DL_POFFSET)

#define BPORT1_AB_MMDC_MPRDDQBY3DL_POFFSET  0x828
#define BPORT1_AB_MMDC_MPRDDQBY3DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDQBY3DL_POFFSET)

#define BPORT1_AB_MMDC_MPWRDQBY0DL_POFFSET  0x82c
#define BPORT1_AB_MMDC_MPWRDQBY0DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDQBY0DL_POFFSET)

#define BPORT1_AB_MMDC_MPWRDQBY1DL_POFFSET  0x830
#define BPORT1_AB_MMDC_MPWRDQBY1DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDQBY1DL_POFFSET)

#define BPORT1_AB_MMDC_MPWRDQBY2DL_POFFSET  0x834
#define BPORT1_AB_MMDC_MPWRDQBY2DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDQBY2DL_POFFSET)

#define BPORT1_AB_MMDC_MPWRDQBY3DL_POFFSET  0x838
#define BPORT1_AB_MMDC_MPWRDQBY3DL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDQBY3DL_POFFSET)

#define BPORT1_AB_MMDC_MPDGCTRL0_POFFSET  0x83c
#define BPORT1_AB_MMDC_MPDGCTRL0        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDGCTRL0_POFFSET)

#define BPORT1_AB_MMDC_MPDGCTRL1_POFFSET  0x840
#define BPORT1_AB_MMDC_MPDGCTRL1        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDGCTRL1_POFFSET)

#define BPORT1_AB_MMDC_MPDGDLST0_POFFSET  0x844
#define BPORT1_AB_MMDC_MPDGDLST0        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDGDLST0_POFFSET)

#define BPORT1_AB_MMDC_MPRDDLCTL_POFFSET  0x848
#define BPORT1_AB_MMDC_MPRDDLCTL        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDLCTL_POFFSET)

#define BPORT1_AB_MMDC_MPRDDLST_POFFSET  0x84c
#define BPORT1_AB_MMDC_MPRDDLST         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDLST_POFFSET)

#define BPORT1_AB_MMDC_MPWRDLCTL_POFFSET  0x850
#define BPORT1_AB_MMDC_MPWRDLCTL        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDLCTL_POFFSET)

#define BPORT1_AB_MMDC_MPWRDLST_POFFSET  0x854
#define BPORT1_AB_MMDC_MPWRDLST         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDLST_POFFSET)

#define BPORT1_AB_MMDC_MPSDCTRL_POFFSET  0x858
#define BPORT1_AB_MMDC_MPSDCTRL         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSDCTRL_POFFSET)

#define BPORT1_AB_MMDC_MPZQLP2CTL_POFFSET  0x85c
#define BPORT1_AB_MMDC_MPZQLP2CTL       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPZQLP2CTL_POFFSET)

#define BPORT1_AB_MMDC_MPRDDLHWCTL_POFFSET  0x860
#define BPORT1_AB_MMDC_MPRDDLHWCTL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDLHWCTL_POFFSET)

#define BPORT1_AB_MMDC_MPWRDLHWCTL_POFFSET  0x864
#define BPORT1_AB_MMDC_MPWRDLHWCTL      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDLHWCTL_POFFSET)

#define BPORT1_AB_MMDC_MPRDDLHWST0_POFFSET  0x868
#define BPORT1_AB_MMDC_MPRDDLHWST0      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDLHWST0_POFFSET)

#define BPORT1_AB_MMDC_MPRDDLHWST1_POFFSET  0x86c
#define BPORT1_AB_MMDC_MPRDDLHWST1      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPRDDLHWST1_POFFSET)

#define BPORT1_AB_MMDC_MPWRDLHWST0_POFFSET  0x870
#define BPORT1_AB_MMDC_MPWRDLHWST0      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDLHWST0_POFFSET)

#define BPORT1_AB_MMDC_MPWRDLHWST1_POFFSET  0x874
#define BPORT1_AB_MMDC_MPWRDLHWST1      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRDLHWST1_POFFSET)

#define BPORT1_AB_MMDC_MPWLHWERR_POFFSET  0x878
#define BPORT1_AB_MMDC_MPWLHWERR        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWLHWERR_POFFSET)

#define BPORT1_AB_MMDC_MPDGHWST0_POFFSET  0x87c
#define BPORT1_AB_MMDC_MPDGHWST0        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDGHWST0_POFFSET)

#define BPORT1_AB_MMDC_MPDGHWST1_POFFSET  0x880
#define BPORT1_AB_MMDC_MPDGHWST1        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDGHWST1_POFFSET)

#define BPORT1_AB_MMDC_MPDGHWST2_POFFSET  0x884
#define BPORT1_AB_MMDC_MPDGHWST2        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDGHWST2_POFFSET)

#define BPORT1_AB_MMDC_MPDGHWST3_POFFSET  0x888
#define BPORT1_AB_MMDC_MPDGHWST3        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDGHWST3_POFFSET)

#define BPORT1_AB_MMDC_MPPDCMPR1_POFFSET  0x88c
#define BPORT1_AB_MMDC_MPPDCMPR1        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPPDCMPR1_POFFSET)

#define BPORT1_AB_MMDC_MPPDCMPR2_POFFSET  0x890
#define BPORT1_AB_MMDC_MPPDCMPR2        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPPDCMPR2_POFFSET)

#define BPORT1_AB_MMDC_MPSWDAR0_POFFSET  0x894
#define BPORT1_AB_MMDC_MPSWDAR0         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDAR0_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR0_POFFSET  0x898
#define BPORT1_AB_MMDC_MPSWDRDR0        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR0_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR1_POFFSET  0x89c
#define BPORT1_AB_MMDC_MPSWDRDR1        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR1_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR2_POFFSET  0x8a0
#define BPORT1_AB_MMDC_MPSWDRDR2        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR2_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR3_POFFSET  0x8a4
#define BPORT1_AB_MMDC_MPSWDRDR3        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR3_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR4_POFFSET  0x8a8
#define BPORT1_AB_MMDC_MPSWDRDR4        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR4_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR5_POFFSET  0x8ac
#define BPORT1_AB_MMDC_MPSWDRDR5        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR5_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR6_POFFSET  0x8b0
#define BPORT1_AB_MMDC_MPSWDRDR6        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR6_POFFSET)

#define BPORT1_AB_MMDC_MPSWDRDR7_POFFSET  0x8b4
#define BPORT1_AB_MMDC_MPSWDRDR7        (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPSWDRDR7_POFFSET)

#define BPORT1_AB_MMDC_MPMUR0_POFFSET   0x8b8
#define BPORT1_AB_MMDC_MPMUR0           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPMUR0_POFFSET)

#define BPORT1_AB_MMDC_MPWRCADL_POFFSET  0x8bc
#define BPORT1_AB_MMDC_MPWRCADL         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPWRCADL_POFFSET)

#define BPORT1_AB_MMDC_MPDCCR_POFFSET   0x8c0
#define BPORT1_AB_MMDC_MPDCCR           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MMDC_MPDCCR_POFFSET)

#define BPORT1_AB_BUFFER_POFFSET        0x0
#define BPORT1_AB_BUFFER                (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER_POFFSET)
#define BPORT1_AB_BUFFER_BYTES          0x4000


#endif
