/*
 * Copyright (c) 2005-2021 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20211118.0
//
////////////////////////////////////////////////////////////////////////////////

#ifndef PSE_MACROS_IGEN_H
#define PSE_MACROS_IGEN_H               

// Before including this file in the application, define the indicated macros
// to fix the base address of each slave port.

// Set the macro 'BPORT1' to the base of port 'bport1'
#ifndef BPORT1
#error BPORT1 is undefined. It needs to be set to the port base address
#endif


#define BPORT1_AB_POFFSET               0x0
#define BPORT1_AB_SDMA_SYSTEM_ADDRESS_REGISTER_POFFSET  0x0
#define BPORT1_AB_SDMA_SYSTEM_ADDRESS_REGISTER  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SDMA_SYSTEM_ADDRESS_REGISTER_POFFSET)

#define BPORT1_AB_BLOCK_SIZE_BLOCK_COUNT_POFFSET  0x4
#define BPORT1_AB_BLOCK_SIZE_BLOCK_COUNT  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BLOCK_SIZE_BLOCK_COUNT_POFFSET)

#define BPORT1_AB_ARGUMENT_POFFSET      0x8
#define BPORT1_AB_ARGUMENT              (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_ARGUMENT_POFFSET)

#define BPORT1_AB_TRANSFER_MODE_COMMAND_POFFSET  0xc
#define BPORT1_AB_TRANSFER_MODE_COMMAND  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_TRANSFER_MODE_COMMAND_POFFSET)

#define BPORT1_AB_RESPONSE0_POFFSET     0x10
#define BPORT1_AB_RESPONSE0             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RESPONSE0_POFFSET)

#define BPORT1_AB_RESPONSE1_POFFSET     0x14
#define BPORT1_AB_RESPONSE1             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RESPONSE1_POFFSET)

#define BPORT1_AB_RESPONSE2_POFFSET     0x18
#define BPORT1_AB_RESPONSE2             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RESPONSE2_POFFSET)

#define BPORT1_AB_RESPONSE3_POFFSET     0x1c
#define BPORT1_AB_RESPONSE3             (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_RESPONSE3_POFFSET)

#define BPORT1_AB_BUFFER_DATA_PORT_POFFSET  0x20
#define BPORT1_AB_BUFFER_DATA_PORT      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER_DATA_PORT_POFFSET)

#define BPORT1_AB_PRESENT_STATE_POFFSET  0x24
#define BPORT1_AB_PRESENT_STATE         (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_PRESENT_STATE_POFFSET)

#define BPORT1_AB_HOST_POWER_BLOCK_GAP_WAKEUP_CONTROL_POFFSET  0x28
#define BPORT1_AB_HOST_POWER_BLOCK_GAP_WAKEUP_CONTROL  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_HOST_POWER_BLOCK_GAP_WAKEUP_CONTROL_POFFSET)
#define BPORT1_AB_HOST_POWER_BLOCK_GAP_WAKEUP_CONTROL_LED  0x1
#define BPORT1_AB_HOST_POWER_BLOCK_GAP_WAKEUP_CONTROL_LED_GET(_v)  (_v & 0x1)

#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_POFFSET  0x2c
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_POFFSET)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_SWRST_DAT  (0x1 << 26)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_SWRST_DAT_GET(_v)  ((_v >> 26) & 0x1)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_SWRST_CMD  (0x1 << 25)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_SWRST_CMD_GET(_v)  ((_v >> 25) & 0x1)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_SWRST_ALL  (0x1 << 24)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_SWRST_ALL_GET(_v)  ((_v >> 24) & 0x1)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_ICLKST  (0x1 << 1)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_ICLKST_GET(_v)  ((_v >> 1) & 0x1)
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_ICLKEN  0x1
#define BPORT1_AB_CLOCK_TIMEOUT_CONTROL_SOFTWARE_RESET_ICLKEN_GET(_v)  (_v & 0x1)

#define BPORT1_AB_INTERRUPT_STATUS_POFFSET  0x30
#define BPORT1_AB_INTERRUPT_STATUS      (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_STATUS_POFFSET)

#define BPORT1_AB_INTERRUPT_STATUS_ENABLE_POFFSET  0x34
#define BPORT1_AB_INTERRUPT_STATUS_ENABLE  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_STATUS_ENABLE_POFFSET)

#define BPORT1_AB_INTERRUPT_SIGNAL_ENABLE_POFFSET  0x38
#define BPORT1_AB_INTERRUPT_SIGNAL_ENABLE  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_INTERRUPT_SIGNAL_ENABLE_POFFSET)

#define BPORT1_AB_AUTO_CMD12_ERROR_STATUS_POFFSET  0x3c
#define BPORT1_AB_AUTO_CMD12_ERROR_STATUS  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_AUTO_CMD12_ERROR_STATUS_POFFSET)

#define BPORT1_AB_CAPABILITIES_POFFSET  0x40
#define BPORT1_AB_CAPABILITIES          (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_CAPABILITIES_POFFSET)

#define BPORT1_AB_MAXIMUM_CURRENT_CAPABILITIES_POFFSET  0x48
#define BPORT1_AB_MAXIMUM_CURRENT_CAPABILITIES  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_MAXIMUM_CURRENT_CAPABILITIES_POFFSET)

#define BPORT1_AB_FORCE_EVENT_POFFSET   0x50
#define BPORT1_AB_FORCE_EVENT           (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_FORCE_EVENT_POFFSET)

#define BPORT1_AB_ADMA_ERROR_STATUS_POFFSET  0x54
#define BPORT1_AB_ADMA_ERROR_STATUS     (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_ADMA_ERROR_STATUS_POFFSET)

#define BPORT1_AB_ADMA_SYSTEM_ADDRESS_POFFSET  0x58
#define BPORT1_AB_ADMA_SYSTEM_ADDRESS   (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_ADMA_SYSTEM_ADDRESS_POFFSET)

#define BPORT1_AB_BOOT_TIMEOUT_CONTROL_POFFSET  0x60
#define BPORT1_AB_BOOT_TIMEOUT_CONTROL  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BOOT_TIMEOUT_CONTROL_POFFSET)

#define BPORT1_AB_DEBUG_SELECTION_POFFSET  0x64
#define BPORT1_AB_DEBUG_SELECTION       (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_DEBUG_SELECTION_POFFSET)

#define BPORT1_AB_SPI_INTERRUPT_SUPPORT_POFFSET  0xf0
#define BPORT1_AB_SPI_INTERRUPT_SUPPORT  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SPI_INTERRUPT_SUPPORT_POFFSET)

#define BPORT1_AB_SLOT_STATUS_HOST_VERSION_POFFSET  0xfc
#define BPORT1_AB_SLOT_STATUS_HOST_VERSION  (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_SLOT_STATUS_HOST_VERSION_POFFSET)

#define BPORT1_AB_BUFFER_POFFSET        0x0
#define BPORT1_AB_BUFFER                (BPORT1 + BPORT1_AB_POFFSET + BPORT1_AB_BUFFER_POFFSET)
#define BPORT1_AB_BUFFER_BYTES          0x1000


#endif
